image:
  repository: 954976298234.dkr.ecr.us-east-1.amazonaws.com/patient-service
  tag: latest
  pullPolicy: IfNotPresent
replicaCount: 1
ports:
  - containerPort: 9093
    name: grpc
env:
  - name: ENVIRONMENT
    valueFrom:
      configMapKeyRef:
        key: ENVIRONMENT
        name: app-config
  - name: JAEGER_ENDPOINT
    valueFrom:
      configMapKeyRef:
        key: JAEGER_ENDPOINT
        name: app-config
  - name: PATIENT_SERVICE_HTTP_ADDR
    valueFrom:
      configMapKeyRef:
        key: PATIENT_SERVICE_HTTP_ADDR
        name: app-config
  - name: PATIENT_SERVICE_GRPC_ADDR
    valueFrom:
      configMapKeyRef:
        key: PATIENT_SERVICE_GRPC_ADDR
        name: app-config
  - name: AUTH_SERVICE_GRPC_ADDR
    valueFrom:
      configMapKeyRef:
        key: AUTH_SERVICE_GRPC_ADDR
        name: app-config
  - name: AUDIT_SERVICE_GRPC_ADDR
    valueFrom:
      configMapKeyRef:
        key: AUDIT_SERVICE_GRPC_ADDR
        name: app-config
  - name: INTERNAL_SERVICE_SECRET
    valueFrom:
      secretKeyRef:
        key: INTERNAL_SERVICE_SECRET
        name: app-secrets
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        key: DATABASE_URL
        name: app-secrets
  - name: PATIENT_SERVICE_JWT_SECRET
    valueFrom:
      secretKeyRef:
        key: PATIENT_SERVICE_JWT_SECRET
        name: app-secrets
  - name: AUTH_SERVICE_JWT_SECRET
    valueFrom:
      secretKeyRef:
        key: AUTH_SERVICE_JWT_SECRET
        name: app-secrets
  - name: REDIS_ADDR
    valueFrom:
      configMapKeyRef:
        key: REDIS_ADDR
        name: app-config
  - name: RABBITMQ_URI
    valueFrom:
      secretKeyRef:
        key: uri
        name: rabbitmq-credentials
  - name: LIVEKIT_URL
    valueFrom:
      configMapKeyRef:
        key: LIVEKIT_URL
        name: app-config
  - name: LIVEKIT_WS_URL
    valueFrom:
      configMapKeyRef:
        key: LIVEKIT_WS_URL
        name: app-config
  - name: LIVEKIT_PUBLIC_WS_URL
    valueFrom:
      configMapKeyRef:
        key: LIVEKIT_PUBLIC_WS_URL
        name: app-config
  - name: LIVEKIT_API_KEY
    valueFrom:
      secretKeyRef:
        key: apiKey
        name: livekit-credentials
  - name: LIVEKIT_API_SECRET
    valueFrom:
      secretKeyRef:
        key: apiSecret
        name: livekit-credentials
resources:
  requests:
    memory: 128Mi
    cpu: 125m
  limits:
    memory: 256Mi
    cpu: 250m
service:
  type: ClusterIP
  ports:
    - port: 9093
      targetPort: 9093
      name: grpc
