// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: patient.auth.proto

package patient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_patient_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_patient_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	PatientID     string                 `protobuf:"bytes,3,opt,name=PatientID,proto3" json:"PatientID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_patient_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_patient_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetPatientID() string {
	if x != nil {
		return x.PatientID
	}
	return ""
}

var File_patient_auth_proto protoreflect.FileDescriptor

const file_patient_auth_proto_rawDesc = "" +
	"\n" +
	"\x12patient.auth.proto\x12\fpatient.auth\"b\n" +
	"\fLoginRequest\x12 \n" +
	"\vPhoneNumber\x18\x01 \x01(\tR\vPhoneNumber\x12\x14\n" +
	"\x05Email\x18\x02 \x01(\tR\x05Email\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bPassword\"i\n" +
	"\rLoginResponse\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12 \n" +
	"\vAccessToken\x18\x02 \x01(\tR\vAccessToken\x12\x1c\n" +
	"\tPatientID\x18\x03 \x01(\tR\tPatientID2P\n" +
	"\fLoginService\x12@\n" +
	"\x05Login\x12\x1a.patient.auth.LoginRequest\x1a\x1b.patient.auth.LoginResponseB\x1eZ\x1cshared/proto/patient;patientb\x06proto3"

var (
	file_patient_auth_proto_rawDescOnce sync.Once
	file_patient_auth_proto_rawDescData []byte
)

func file_patient_auth_proto_rawDescGZIP() []byte {
	file_patient_auth_proto_rawDescOnce.Do(func() {
		file_patient_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_patient_auth_proto_rawDesc), len(file_patient_auth_proto_rawDesc)))
	})
	return file_patient_auth_proto_rawDescData
}

var file_patient_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_patient_auth_proto_goTypes = []any{
	(*LoginRequest)(nil),  // 0: patient.auth.LoginRequest
	(*LoginResponse)(nil), // 1: patient.auth.LoginResponse
}
var file_patient_auth_proto_depIdxs = []int32{
	0, // 0: patient.auth.LoginService.Login:input_type -> patient.auth.LoginRequest
	1, // 1: patient.auth.LoginService.Login:output_type -> patient.auth.LoginResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_patient_auth_proto_init() }
func file_patient_auth_proto_init() {
	if File_patient_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patient_auth_proto_rawDesc), len(file_patient_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_patient_auth_proto_goTypes,
		DependencyIndexes: file_patient_auth_proto_depIdxs,
		MessageInfos:      file_patient_auth_proto_msgTypes,
	}.Build()
	File_patient_auth_proto = out.File
	file_patient_auth_proto_goTypes = nil
	file_patient_auth_proto_depIdxs = nil
}
