// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: analytics/analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HospitalSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HospitalId    string                 `protobuf:"bytes,1,opt,name=hospital_id,json=hospitalId,proto3" json:"hospital_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HospitalSummaryRequest) Reset() {
	*x = HospitalSummaryRequest{}
	mi := &file_analytics_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HospitalSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HospitalSummaryRequest) ProtoMessage() {}

func (x *HospitalSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HospitalSummaryRequest.ProtoReflect.Descriptor instead.
func (*HospitalSummaryRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *HospitalSummaryRequest) GetHospitalId() string {
	if x != nil {
		return x.HospitalId
	}
	return ""
}

type HospitalSummaryResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TotalConsentedPatients int32                  `protobuf:"varint,1,opt,name=total_consented_patients,json=totalConsentedPatients,proto3" json:"total_consented_patients,omitempty"`
	ActiveSessionsToday    int32                  `protobuf:"varint,2,opt,name=active_sessions_today,json=activeSessionsToday,proto3" json:"active_sessions_today,omitempty"`
	RecordsIndexed         int32                  `protobuf:"varint,3,opt,name=records_indexed,json=recordsIndexed,proto3" json:"records_indexed,omitempty"`
	EmergencyEvents_30D    int32                  `protobuf:"varint,4,opt,name=emergency_events_30d,json=emergencyEvents30d,proto3" json:"emergency_events_30d,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HospitalSummaryResponse) Reset() {
	*x = HospitalSummaryResponse{}
	mi := &file_analytics_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HospitalSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HospitalSummaryResponse) ProtoMessage() {}

func (x *HospitalSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HospitalSummaryResponse.ProtoReflect.Descriptor instead.
func (*HospitalSummaryResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *HospitalSummaryResponse) GetTotalConsentedPatients() int32 {
	if x != nil {
		return x.TotalConsentedPatients
	}
	return 0
}

func (x *HospitalSummaryResponse) GetActiveSessionsToday() int32 {
	if x != nil {
		return x.ActiveSessionsToday
	}
	return 0
}

func (x *HospitalSummaryResponse) GetRecordsIndexed() int32 {
	if x != nil {
		return x.RecordsIndexed
	}
	return 0
}

func (x *HospitalSummaryResponse) GetEmergencyEvents_30D() int32 {
	if x != nil {
		return x.EmergencyEvents_30D
	}
	return 0
}

type RecentActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HospitalId    string                 `protobuf:"bytes,1,opt,name=hospital_id,json=hospitalId,proto3" json:"hospital_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentActivityRequest) Reset() {
	*x = RecentActivityRequest{}
	mi := &file_analytics_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentActivityRequest) ProtoMessage() {}

func (x *RecentActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentActivityRequest.ProtoReflect.Descriptor instead.
func (*RecentActivityRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *RecentActivityRequest) GetHospitalId() string {
	if x != nil {
		return x.HospitalId
	}
	return ""
}

func (x *RecentActivityRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecentActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ActivityEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentActivityResponse) Reset() {
	*x = RecentActivityResponse{}
	mi := &file_analytics_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentActivityResponse) ProtoMessage() {}

func (x *RecentActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentActivityResponse.ProtoReflect.Descriptor instead.
func (*RecentActivityResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *RecentActivityResponse) GetEvents() []*ActivityEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ActivityEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	PatientId     string                 `protobuf:"bytes,3,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityEvent) Reset() {
	*x = ActivityEvent{}
	mi := &file_analytics_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityEvent) ProtoMessage() {}

func (x *ActivityEvent) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityEvent.ProtoReflect.Descriptor instead.
func (*ActivityEvent) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *ActivityEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ActivityEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ActivityEvent) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ActivityEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_analytics_analytics_proto protoreflect.FileDescriptor

const file_analytics_analytics_proto_rawDesc = "" +
	"\n" +
	"\x19analytics/analytics.proto\x12\tanalytics\"9\n" +
	"\x16HospitalSummaryRequest\x12\x1f\n" +
	"\vhospital_id\x18\x01 \x01(\tR\n" +
	"hospitalId\"\xe2\x01\n" +
	"\x17HospitalSummaryResponse\x128\n" +
	"\x18total_consented_patients\x18\x01 \x01(\x05R\x16totalConsentedPatients\x122\n" +
	"\x15active_sessions_today\x18\x02 \x01(\x05R\x13activeSessionsToday\x12'\n" +
	"\x0frecords_indexed\x18\x03 \x01(\x05R\x0erecordsIndexed\x120\n" +
	"\x14emergency_events_30d\x18\x04 \x01(\x05R\x12emergencyEvents30d\"N\n" +
	"\x15RecentActivityRequest\x12\x1f\n" +
	"\vhospital_id\x18\x01 \x01(\tR\n" +
	"hospitalId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"J\n" +
	"\x16RecentActivityResponse\x120\n" +
	"\x06events\x18\x01 \x03(\v2\x18.analytics.ActivityEventR\x06events\"\x8d\x01\n" +
	"\rActivityEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x03 \x01(\tR\tpatientId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription2\xc9\x01\n" +
	"\x10AnalyticsService\x12[\n" +
	"\x12GetHospitalSummary\x12!.analytics.HospitalSummaryRequest\x1a\".analytics.HospitalSummaryResponse\x12X\n" +
	"\x11GetRecentActivity\x12 .analytics.RecentActivityRequest\x1a!.analytics.RecentActivityResponseB\"Z shared/proto/analytics;analyticsb\x06proto3"

var (
	file_analytics_analytics_proto_rawDescOnce sync.Once
	file_analytics_analytics_proto_rawDescData []byte
)

func file_analytics_analytics_proto_rawDescGZIP() []byte {
	file_analytics_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_analytics_proto_rawDesc), len(file_analytics_analytics_proto_rawDesc)))
	})
	return file_analytics_analytics_proto_rawDescData
}

var file_analytics_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_analytics_analytics_proto_goTypes = []any{
	(*HospitalSummaryRequest)(nil),  // 0: analytics.HospitalSummaryRequest
	(*HospitalSummaryResponse)(nil), // 1: analytics.HospitalSummaryResponse
	(*RecentActivityRequest)(nil),   // 2: analytics.RecentActivityRequest
	(*RecentActivityResponse)(nil),  // 3: analytics.RecentActivityResponse
	(*ActivityEvent)(nil),           // 4: analytics.ActivityEvent
}
var file_analytics_analytics_proto_depIdxs = []int32{
	4, // 0: analytics.RecentActivityResponse.events:type_name -> analytics.ActivityEvent
	0, // 1: analytics.AnalyticsService.GetHospitalSummary:input_type -> analytics.HospitalSummaryRequest
	2, // 2: analytics.AnalyticsService.GetRecentActivity:input_type -> analytics.RecentActivityRequest
	1, // 3: analytics.AnalyticsService.GetHospitalSummary:output_type -> analytics.HospitalSummaryResponse
	3, // 4: analytics.AnalyticsService.GetRecentActivity:output_type -> analytics.RecentActivityResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_analytics_analytics_proto_init() }
func file_analytics_analytics_proto_init() {
	if File_analytics_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_analytics_proto_rawDesc), len(file_analytics_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_analytics_proto_msgTypes,
	}.Build()
	File_analytics_analytics_proto = out.File
	file_analytics_analytics_proto_goTypes = nil
	file_analytics_analytics_proto_depIdxs = nil
}
