// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: action_item.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateActionItemsParams struct {
	CallID          int64            `json:"call_id"`
	TaskDescription pgtype.Text      `json:"task_description"`
	IsCompleted     pgtype.Bool      `json:"is_completed"`
	DueDate         pgtype.Timestamp `json:"due_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

const countActionItemsByCallID = `-- name: CountActionItemsByCallID :one
SELECT COUNT(*) FROM action_items
WHERE call_id = $1
`

func (q *Queries) CountActionItemsByCallID(ctx context.Context, callID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActionItemsByCallID, callID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingActionItems = `-- name: CountPendingActionItems :one
SELECT COUNT(*) FROM action_items
WHERE is_completed = false
`

func (q *Queries) CountPendingActionItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingActionItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActionItem = `-- name: CreateActionItem :one
INSERT INTO action_items (
  call_id,
  task_description,
  is_completed,
  due_date,
  created_at
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, call_id, task_description, is_completed, due_date, created_at
`

type CreateActionItemParams struct {
	CallID          int64            `json:"call_id"`
	TaskDescription pgtype.Text      `json:"task_description"`
	IsCompleted     pgtype.Bool      `json:"is_completed"`
	DueDate         pgtype.Timestamp `json:"due_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateActionItem(ctx context.Context, arg CreateActionItemParams) (ActionItem, error) {
	row := q.db.QueryRow(ctx, createActionItem,
		arg.CallID,
		arg.TaskDescription,
		arg.IsCompleted,
		arg.DueDate,
		arg.CreatedAt,
	)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.TaskDescription,
		&i.IsCompleted,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteActionItem = `-- name: DeleteActionItem :exec
DELETE FROM action_items
WHERE id = $1
`

func (q *Queries) DeleteActionItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteActionItem, id)
	return err
}

const getActionItemByID = `-- name: GetActionItemByID :one
SELECT id, call_id, task_description, is_completed, due_date, created_at FROM action_items
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetActionItemByID(ctx context.Context, id int64) (ActionItem, error) {
	row := q.db.QueryRow(ctx, getActionItemByID, id)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.TaskDescription,
		&i.IsCompleted,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}

const getActionItemWithCallInfo = `-- name: GetActionItemWithCallInfo :one
SELECT 
  ai.id, ai.call_id, ai.task_description, ai.is_completed, ai.due_date, ai.created_at,
  c.patient_id,
  c.livekit_room_id,
  c.started_at as call_started_at,
  p.full_name as patient_name,
  p.phone_number as patient_phone
FROM action_items ai
INNER JOIN calls c ON ai.call_id = c.id
INNER JOIN patients p ON c.patient_id = p.id
WHERE ai.id = $1
LIMIT 1
`

type GetActionItemWithCallInfoRow struct {
	ID              int64            `json:"id"`
	CallID          int64            `json:"call_id"`
	TaskDescription pgtype.Text      `json:"task_description"`
	IsCompleted     pgtype.Bool      `json:"is_completed"`
	DueDate         pgtype.Timestamp `json:"due_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	PatientID       pgtype.UUID      `json:"patient_id"`
	LivekitRoomID   pgtype.Text      `json:"livekit_room_id"`
	CallStartedAt   pgtype.Timestamp `json:"call_started_at"`
	PatientName     pgtype.Text      `json:"patient_name"`
	PatientPhone    string           `json:"patient_phone"`
}

func (q *Queries) GetActionItemWithCallInfo(ctx context.Context, id int64) (GetActionItemWithCallInfoRow, error) {
	row := q.db.QueryRow(ctx, getActionItemWithCallInfo, id)
	var i GetActionItemWithCallInfoRow
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.TaskDescription,
		&i.IsCompleted,
		&i.DueDate,
		&i.CreatedAt,
		&i.PatientID,
		&i.LivekitRoomID,
		&i.CallStartedAt,
		&i.PatientName,
		&i.PatientPhone,
	)
	return i, err
}

const getActionItemsByPatient = `-- name: GetActionItemsByPatient :many
SELECT ai.id, ai.call_id, ai.task_description, ai.is_completed, ai.due_date, ai.created_at
FROM action_items ai
INNER JOIN calls c ON ai.call_id = c.id
WHERE c.patient_id = $1
ORDER BY ai.created_at DESC
LIMIT $2 OFFSET $3
`

type GetActionItemsByPatientParams struct {
	PatientID pgtype.UUID `json:"patient_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) GetActionItemsByPatient(ctx context.Context, arg GetActionItemsByPatientParams) ([]ActionItem, error) {
	rows, err := q.db.Query(ctx, getActionItemsByPatient, arg.PatientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionItem{}
	for rows.Next() {
		var i ActionItem
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.TaskDescription,
			&i.IsCompleted,
			&i.DueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActionItemsDueByDate = `-- name: GetActionItemsDueByDate :many
SELECT id, call_id, task_description, is_completed, due_date, created_at FROM action_items
WHERE is_completed = false
  AND due_date <= $1
ORDER BY due_date ASC
`

func (q *Queries) GetActionItemsDueByDate(ctx context.Context, dueDate pgtype.Timestamp) ([]ActionItem, error) {
	rows, err := q.db.Query(ctx, getActionItemsDueByDate, dueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionItem{}
	for rows.Next() {
		var i ActionItem
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.TaskDescription,
			&i.IsCompleted,
			&i.DueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverdueActionItems = `-- name: GetOverdueActionItems :many
SELECT id, call_id, task_description, is_completed, due_date, created_at FROM action_items
WHERE is_completed = false
  AND due_date < NOW()
ORDER BY due_date ASC
`

func (q *Queries) GetOverdueActionItems(ctx context.Context) ([]ActionItem, error) {
	rows, err := q.db.Query(ctx, getOverdueActionItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionItem{}
	for rows.Next() {
		var i ActionItem
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.TaskDescription,
			&i.IsCompleted,
			&i.DueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingActionItems = `-- name: GetPendingActionItems :many
SELECT id, call_id, task_description, is_completed, due_date, created_at FROM action_items
WHERE is_completed = false
ORDER BY due_date ASC NULLS LAST
LIMIT $1 OFFSET $2
`

type GetPendingActionItemsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetPendingActionItems(ctx context.Context, arg GetPendingActionItemsParams) ([]ActionItem, error) {
	rows, err := q.db.Query(ctx, getPendingActionItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionItem{}
	for rows.Next() {
		var i ActionItem
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.TaskDescription,
			&i.IsCompleted,
			&i.DueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingActionItemsByPatient = `-- name: GetPendingActionItemsByPatient :many
SELECT ai.id, ai.call_id, ai.task_description, ai.is_completed, ai.due_date, ai.created_at
FROM action_items ai
INNER JOIN calls c ON ai.call_id = c.id
WHERE c.patient_id = $1
  AND ai.is_completed = false
ORDER BY ai.due_date ASC NULLS LAST
`

func (q *Queries) GetPendingActionItemsByPatient(ctx context.Context, patientID pgtype.UUID) ([]ActionItem, error) {
	rows, err := q.db.Query(ctx, getPendingActionItemsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionItem{}
	for rows.Next() {
		var i ActionItem
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.TaskDescription,
			&i.IsCompleted,
			&i.DueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionItemsByCallID = `-- name: ListActionItemsByCallID :many
SELECT id, call_id, task_description, is_completed, due_date, created_at FROM action_items
WHERE call_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListActionItemsByCallID(ctx context.Context, callID int64) ([]ActionItem, error) {
	rows, err := q.db.Query(ctx, listActionItemsByCallID, callID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionItem{}
	for rows.Next() {
		var i ActionItem
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.TaskDescription,
			&i.IsCompleted,
			&i.DueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markActionItemComplete = `-- name: MarkActionItemComplete :one
UPDATE action_items
SET is_completed = true
WHERE id = $1
RETURNING id, call_id, task_description, is_completed, due_date, created_at
`

func (q *Queries) MarkActionItemComplete(ctx context.Context, id int64) (ActionItem, error) {
	row := q.db.QueryRow(ctx, markActionItemComplete, id)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.TaskDescription,
		&i.IsCompleted,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}

const markActionItemIncomplete = `-- name: MarkActionItemIncomplete :one
UPDATE action_items
SET is_completed = false
WHERE id = $1
RETURNING id, call_id, task_description, is_completed, due_date, created_at
`

func (q *Queries) MarkActionItemIncomplete(ctx context.Context, id int64) (ActionItem, error) {
	row := q.db.QueryRow(ctx, markActionItemIncomplete, id)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.TaskDescription,
		&i.IsCompleted,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}

const updateActionItem = `-- name: UpdateActionItem :one
UPDATE action_items
SET
  task_description = COALESCE($2, task_description),
  due_date = COALESCE($3, due_date),
  is_completed = COALESCE($4, is_completed)
WHERE id = $1
RETURNING id, call_id, task_description, is_completed, due_date, created_at
`

type UpdateActionItemParams struct {
	ID              int64            `json:"id"`
	TaskDescription pgtype.Text      `json:"task_description"`
	DueDate         pgtype.Timestamp `json:"due_date"`
	IsCompleted     pgtype.Bool      `json:"is_completed"`
}

func (q *Queries) UpdateActionItem(ctx context.Context, arg UpdateActionItemParams) (ActionItem, error) {
	row := q.db.QueryRow(ctx, updateActionItem,
		arg.ID,
		arg.TaskDescription,
		arg.DueDate,
		arg.IsCompleted,
	)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.TaskDescription,
		&i.IsCompleted,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}
