// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BulkCreateActionItems(ctx context.Context, arg []BulkCreateActionItemsParams) (int64, error)
	CountActionItemsByCallID(ctx context.Context, callID int64) (int64, error)
	CountCallsByPatientID(ctx context.Context, patientID pgtype.UUID) (int64, error)
	CountPatients(ctx context.Context) (int64, error)
	CountPendingActionItems(ctx context.Context) (int64, error)
	CreateActionItem(ctx context.Context, arg CreateActionItemParams) (ActionItem, error)
	CreateCall(ctx context.Context, arg CreateCallParams) (Call, error)
	CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error)
	// Inserts a minimal user row to satisfy patients.user_id FK. Canonical user (with password) lives in auth_service.
	CreateUserStub(ctx context.Context, arg CreateUserStubParams) (User, error)
	DeleteActionItem(ctx context.Context, id int64) error
	DeleteCall(ctx context.Context, id int64) error
	DeletePatient(ctx context.Context, id pgtype.UUID) error
	EndCall(ctx context.Context, arg EndCallParams) (Call, error)
	GetActionItemByID(ctx context.Context, id int64) (ActionItem, error)
	GetActionItemWithCallInfo(ctx context.Context, id int64) (GetActionItemWithCallInfoRow, error)
	GetActionItemsByPatient(ctx context.Context, arg GetActionItemsByPatientParams) ([]ActionItem, error)
	GetActionItemsDueByDate(ctx context.Context, dueDate pgtype.Timestamp) ([]ActionItem, error)
	GetCallByID(ctx context.Context, id int64) (Call, error)
	GetCallByLivekitRoomID(ctx context.Context, livekitRoomID pgtype.Text) (Call, error)
	GetCallWithPatient(ctx context.Context, id int64) (GetCallWithPatientRow, error)
	GetCallsInDateRange(ctx context.Context, arg GetCallsInDateRangeParams) ([]Call, error)
	GetOverdueActionItems(ctx context.Context) ([]ActionItem, error)
	GetPatientByEmail(ctx context.Context, email pgtype.Text) (Patient, error)
	GetPatientByID(ctx context.Context, id pgtype.UUID) (Patient, error)
	GetPatientByPhoneNumber(ctx context.Context, phoneNumber string) (Patient, error)
	GetPatientByUserID(ctx context.Context, userID pgtype.UUID) (Patient, error)
	GetPatientsWithRecentCalls(ctx context.Context, startedAt pgtype.Timestamp) ([]Patient, error)
	GetPendingActionItems(ctx context.Context, arg GetPendingActionItemsParams) ([]ActionItem, error)
	GetPendingActionItemsByPatient(ctx context.Context, patientID pgtype.UUID) ([]ActionItem, error)
	GetRecentCalls(ctx context.Context, arg GetRecentCallsParams) ([]Call, error)
	ListActionItemsByCallID(ctx context.Context, callID int64) ([]ActionItem, error)
	ListCallsByPatientID(ctx context.Context, arg ListCallsByPatientIDParams) ([]Call, error)
	ListCallsByStatus(ctx context.Context, arg ListCallsByStatusParams) ([]Call, error)
	ListPatients(ctx context.Context, arg ListPatientsParams) ([]Patient, error)
	MarkActionItemComplete(ctx context.Context, id int64) (ActionItem, error)
	MarkActionItemIncomplete(ctx context.Context, id int64) (ActionItem, error)
	SearchPatientsByName(ctx context.Context, arg SearchPatientsByNameParams) ([]Patient, error)
	UpdateActionItem(ctx context.Context, arg UpdateActionItemParams) (ActionItem, error)
	UpdateCallRecordingURL(ctx context.Context, arg UpdateCallRecordingURLParams) (Call, error)
	UpdateCallStatus(ctx context.Context, arg UpdateCallStatusParams) (Call, error)
	UpdateCallSummary(ctx context.Context, arg UpdateCallSummaryParams) (Call, error)
	UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error)
	UpdatePatientMedicalNotes(ctx context.Context, arg UpdatePatientMedicalNotesParams) (Patient, error)
}

var _ Querier = (*Queries)(nil)
