import { Platform, StyleSheet } from "react-native";
import { colors } from "./tokens";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.canvas,
  },
  shell: {
    flex: 1,
    backgroundColor: colors.background,
  },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  brandContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  brandIconContainer: {
    width: 42,
    height: 42,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOpacity: 0.22,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  header: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  brand: {
    fontSize: 18,
    fontWeight: "900",
    color: colors.text,
    letterSpacing: 0,
  },
  headerSub: {
    marginTop: 1,
    fontSize: 11,
    color: colors.mutedText,
    fontWeight: "500",
  },
  headerActions: {
    flexShrink: 1,
    alignItems: "flex-end",
  },
  authScroll: {
    flexGrow: 1,
    padding: 16,
    justifyContent: "center",
  },
  authPanel: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.primaryTintStrong,
    backgroundColor: colors.surface,
    padding: 24,
    gap: 20,
    shadowColor: colors.primary,
    shadowOpacity: 0.12,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 5,
  },
  portal: {
    flex: 1,
  },
  content: {
    padding: 16,
    paddingBottom: 32,
  },
  stack: {
    gap: 14,
  },
  screenTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: colors.text,
    letterSpacing: 0,
  },
  largeTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: colors.surface,
    marginTop: 4,
    letterSpacing: 0,
  },
  screenCopy: {
    marginTop: 4,
    color: colors.mutedText,
    lineHeight: 18,
    fontSize: 13,
  },
  headingBlock: {
    marginBottom: 6,
  },
  heroPanel: {
    borderRadius: 24,
    padding: 22,
    backgroundColor: colors.primaryDeep,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    gap: 12,
    shadowColor: colors.primary,
    shadowOpacity: 0.28,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  eyebrow: {
    color: colors.primaryTintStrong,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  heroCopy: {
    color: colors.canvas,
    fontSize: 13,
    fontWeight: "600",
  },
  heroActions: {
    flexDirection: "row",
    gap: 10,
    flexWrap: "wrap",
    marginTop: 4,
  },
  heroCallBtn: {
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  heroCallBtnText: {
    color: colors.primaryDeep,
    fontWeight: "800",
    fontSize: 13,
  },
  refreshIcon: {
    padding: 4,
  },
  gridTwo: {
    flexDirection: "row",
    gap: 12,
  },
  infoCard: {
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.primaryTintStrong,
    backgroundColor: colors.surfaceMuted,
    padding: 14,
    gap: 6,
    shadowColor: colors.text,
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  infoCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  infoCardTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.text,
  },
  infoCardBody: {
    color: colors.subtleText,
    fontSize: 12,
    lineHeight: 16,
  },
  card: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.primaryTintStrong,
    backgroundColor: colors.surface,
    padding: 16,
    gap: 8,
    shadowColor: colors.primary,
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  cardActive: {
    borderColor: colors.primaryTint,
    backgroundColor: colors.canvas,
  },
  emailNoticeCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.primaryTint,
    backgroundColor: colors.canvas,
    padding: 14,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  cardAlert: {
    borderColor: colors.errorBorder,
    backgroundColor: colors.errorBg,
  },
  textAlert: {
    color: colors.error,
  },
  subCard: {
    borderRadius: 16,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    gap: 6,
  },
  section: {
    gap: 10,
    marginTop: 8,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "900",
    color: colors.text,
    letterSpacing: -0.2,
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: colors.text,
    textTransform: "capitalize",
  },
  cardBody: {
    color: colors.subtleText,
    fontSize: 13,
    lineHeight: 18,
  },
  bodyText: {
    color: "#334155",
    fontSize: 14,
    lineHeight: 20,
  },
  meta: {
    color: colors.placeholder,
    fontSize: 11,
    fontWeight: "600",
  },
  muted: {
    color: colors.placeholder,
  },
  emptyText: {
    color: colors.placeholder,
    fontSize: 13,
    paddingVertical: 6,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 12,
  },
  rowBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  flex: {
    flex: 1,
  },
  field: {
    gap: 6,
  },
  dateTimeRow: {
    flexDirection: "row",
    gap: 10,
  },
  dateTimeChip: {
    flex: 1,
    minHeight: 64,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.primaryTintStrong,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  dateTimeChipEyebrow: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.mutedText,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  dateTimeChipValue: {
    marginTop: 2,
    fontSize: 14,
    fontWeight: "800",
    color: colors.text,
  },
  filterPanel: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.primaryTintStrong,
    backgroundColor: colors.background,
    padding: 14,
    gap: 12,
  },
  label: {
    color: colors.subtleText,
    fontWeight: "800",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  input: {
    minHeight: 52,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.primaryTint,
    backgroundColor: colors.surface,
    paddingHorizontal: 16,
    color: colors.text,
    fontSize: 15,
  },
  selectButton: {
    minHeight: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.primaryTint,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  selectButtonText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "800",
    textTransform: "capitalize",
  },
  selectMenu: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.primaryTintStrong,
    backgroundColor: colors.surface,
    overflow: "hidden",
  },
  selectOption: {
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  selectOptionActive: {
    backgroundColor: colors.canvas,
  },
  selectOptionText: {
    color: colors.subtleText,
    fontWeight: "700",
    textTransform: "capitalize",
  },
  selectOptionTextActive: {
    color: colors.primary,
  },
  textArea: {
    minHeight: 110,
    textAlignVertical: "top",
    paddingTop: 12,
  },
  primaryButton: {
    minHeight: 52,
    borderRadius: 18,
    paddingHorizontal: 18,
    backgroundColor: colors.primary,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: colors.primary,
    shadowOpacity: 0.28,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  primaryText: {
    color: colors.surface,
    fontWeight: "800",
    fontSize: 14,
  },
  disabled: {
    opacity: 0.6,
  },
  iconButton: {
    minHeight: 38,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  iconAccent: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  iconButtonText: {
    color: colors.subtleText,
    fontWeight: "800",
    fontSize: 12,
  },
  iconAccentText: {
    color: colors.surface,
  },
  textButton: {
    paddingVertical: 4,
  },
  textButtonLabel: {
    color: colors.primary,
    fontWeight: "800",
    fontSize: 13,
  },
  inlineActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
    marginTop: 4,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  chip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  chipActive: {
    borderColor: colors.primaryTint,
    backgroundColor: colors.canvas,
  },
  chipText: {
    color: colors.subtleText,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "capitalize",
  },
  chipTextActive: {
    color: colors.primary,
  },
  qrCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.primaryTintStrong,
    backgroundColor: colors.surface,
    padding: 16,
    alignItems: "center",
    gap: 10,
  },
  qrImage: {
    width: 220,
    height: 220,
    borderRadius: 12,
  },
  cameraFrame: {
    height: 320,
    overflow: "hidden",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.primaryTint,
    backgroundColor: colors.text,
  },
  cameraPreview: {
    flex: 1,
  },
  segmented: {
    flexDirection: "row",
    gap: 4,
    borderRadius: 16,
    backgroundColor: colors.canvas,
    padding: 3,
  },
  segment: {
    minHeight: 32,
    borderRadius: 9,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  segmentActive: {
    backgroundColor: colors.surface,
    shadowColor: colors.primary,
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  segmentText: {
    color: colors.mutedText,
    fontWeight: "800",
    fontSize: 12,
    textTransform: "capitalize",
  },
  segmentTextActive: {
    color: colors.text,
  },
  tabBarFrame: {
    height: 78,
    borderBottomWidth: 1,
    borderBottomColor: colors.primaryTintStrong,
    backgroundColor: colors.surfaceMuted,
    justifyContent: "center",
  },

  tabBar: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    alignItems: "center",
  },

  tab: {
    width: 84,
    height: 52,
    minWidth: 84,
    maxWidth: 84,
    minHeight: 52,
    maxHeight: 52,

    marginRight: 8,

    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.primaryTintStrong,
    backgroundColor: colors.surface,

    overflow: "hidden",

    justifyContent: "center",
    alignItems: "center",

    flexGrow: 0,
    flexShrink: 0,
    alignSelf: "center",
  },

  tabInner: {
    width: "100%",
    height: "100%",

    justifyContent: "center",
    alignItems: "center",
  },

  tabActive: {
    backgroundColor: colors.primaryDeep,
    borderColor: colors.primaryDeep,
  },

  tabText: {
    marginTop: 4,
    fontSize: 13,
    lineHeight: 14,
    fontWeight: "700",
    color: colors.subtleText,

    includeFontPadding: false,
    textAlignVertical: "center",
  },

  tabTextActive: {
    color: colors.surface,
  },
  badge: {
    overflow: "hidden",
    borderRadius: 999,
    backgroundColor: colors.successBg,
    color: colors.success,
    paddingHorizontal: 10,
    paddingVertical: Platform.select({ ios: 4, default: 3 }),
    fontSize: 11,
    fontWeight: "800",
    textTransform: "capitalize",
  },
  badgeWarn: {
    backgroundColor: "#fee2e2",
    color: "#991b1b",
  },
  switchTrack: {
    width: 52,
    height: 30,
    borderRadius: 999,
    padding: 2,
    justifyContent: "center",
  },
  switchOn: {
    backgroundColor: colors.primary,
  },
  switchOff: {
    backgroundColor: "#cbd5e1",
  },
  switchThumb: {
    width: 24,
    height: 24,
    borderRadius: 999,
    backgroundColor: colors.surface,
  },
  switchThumbOn: {
    alignSelf: "flex-end",
  },
  switchThumbOff: {
    alignSelf: "flex-start",
  },
  feedback: {
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    marginTop: 4,
  },
  feedbackError: {
    backgroundColor: "#fef2f2",
    borderColor: colors.errorBorder,
  },
  feedbackNotice: {
    backgroundColor: colors.successBg,
    borderColor: "#bbf7d0",
  },
  errorText: {
    color: colors.error,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
  },
  noticeText: {
    color: colors.primary,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
  },
  playRecordBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 6,
    marginTop: 4,
  },
  playRecordBtnText: {
    color: colors.primary,
    fontWeight: "800",
    fontSize: 12,
  },
  playIcon: {
    padding: 4,
  },
  failureReasonBox: {
    backgroundColor: "#fef2f2",
    padding: 10,
    borderRadius: 10,
    marginTop: 4,
  },
});
