// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoginService_Login_FullMethodName = "/auth.LoginService/Login"
)

// LoginServiceClient is the client API for LoginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type loginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginServiceClient(cc grpc.ClientConnInterface) LoginServiceClient {
	return &loginServiceClient{cc}
}

func (c *loginServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, LoginService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServiceServer is the server API for LoginService service.
// All implementations must embed UnimplementedLoginServiceServer
// for forward compatibility.
type LoginServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedLoginServiceServer()
}

// UnimplementedLoginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoginServiceServer struct{}

func (UnimplementedLoginServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedLoginServiceServer) mustEmbedUnimplementedLoginServiceServer() {}
func (UnimplementedLoginServiceServer) testEmbeddedByValue()                      {}

// UnsafeLoginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginServiceServer will
// result in compilation errors.
type UnsafeLoginServiceServer interface {
	mustEmbedUnimplementedLoginServiceServer()
}

func RegisterLoginServiceServer(s grpc.ServiceRegistrar, srv LoginServiceServer) {
	// If the following call panics, it indicates UnimplementedLoginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoginService_ServiceDesc, srv)
}

func _LoginService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoginService_ServiceDesc is the grpc.ServiceDesc for LoginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.LoginService",
	HandlerType: (*LoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _LoginService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

const (
	RegisterPatientService_RegisterPatient_FullMethodName = "/auth.RegisterPatientService/RegisterPatient"
)

// RegisterPatientServiceClient is the client API for RegisterPatientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegisterPatientServiceClient interface {
	RegisterPatient(ctx context.Context, in *RegisterPatientRequest, opts ...grpc.CallOption) (*RegisterPatientResponse, error)
}

type registerPatientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegisterPatientServiceClient(cc grpc.ClientConnInterface) RegisterPatientServiceClient {
	return &registerPatientServiceClient{cc}
}

func (c *registerPatientServiceClient) RegisterPatient(ctx context.Context, in *RegisterPatientRequest, opts ...grpc.CallOption) (*RegisterPatientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterPatientResponse)
	err := c.cc.Invoke(ctx, RegisterPatientService_RegisterPatient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterPatientServiceServer is the server API for RegisterPatientService service.
// All implementations must embed UnimplementedRegisterPatientServiceServer
// for forward compatibility.
type RegisterPatientServiceServer interface {
	RegisterPatient(context.Context, *RegisterPatientRequest) (*RegisterPatientResponse, error)
	mustEmbedUnimplementedRegisterPatientServiceServer()
}

// UnimplementedRegisterPatientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegisterPatientServiceServer struct{}

func (UnimplementedRegisterPatientServiceServer) RegisterPatient(context.Context, *RegisterPatientRequest) (*RegisterPatientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterPatient not implemented")
}
func (UnimplementedRegisterPatientServiceServer) mustEmbedUnimplementedRegisterPatientServiceServer() {
}
func (UnimplementedRegisterPatientServiceServer) testEmbeddedByValue() {}

// UnsafeRegisterPatientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegisterPatientServiceServer will
// result in compilation errors.
type UnsafeRegisterPatientServiceServer interface {
	mustEmbedUnimplementedRegisterPatientServiceServer()
}

func RegisterRegisterPatientServiceServer(s grpc.ServiceRegistrar, srv RegisterPatientServiceServer) {
	// If the following call panics, it indicates UnimplementedRegisterPatientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegisterPatientService_ServiceDesc, srv)
}

func _RegisterPatientService_RegisterPatient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPatientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterPatientServiceServer).RegisterPatient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegisterPatientService_RegisterPatient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterPatientServiceServer).RegisterPatient(ctx, req.(*RegisterPatientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterPatientService_ServiceDesc is the grpc.ServiceDesc for RegisterPatientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegisterPatientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.RegisterPatientService",
	HandlerType: (*RegisterPatientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterPatient",
			Handler:    _RegisterPatientService_RegisterPatient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

const (
	RegisterHealthProviderService_RegisterHealthProvider_FullMethodName = "/auth.RegisterHealthProviderService/RegisterHealthProvider"
)

// RegisterHealthProviderServiceClient is the client API for RegisterHealthProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegisterHealthProviderServiceClient interface {
	RegisterHealthProvider(ctx context.Context, in *RegisterHealthProviderRequest, opts ...grpc.CallOption) (*RegisterHealthProviderResponse, error)
}

type registerHealthProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegisterHealthProviderServiceClient(cc grpc.ClientConnInterface) RegisterHealthProviderServiceClient {
	return &registerHealthProviderServiceClient{cc}
}

func (c *registerHealthProviderServiceClient) RegisterHealthProvider(ctx context.Context, in *RegisterHealthProviderRequest, opts ...grpc.CallOption) (*RegisterHealthProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterHealthProviderResponse)
	err := c.cc.Invoke(ctx, RegisterHealthProviderService_RegisterHealthProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterHealthProviderServiceServer is the server API for RegisterHealthProviderService service.
// All implementations must embed UnimplementedRegisterHealthProviderServiceServer
// for forward compatibility.
type RegisterHealthProviderServiceServer interface {
	RegisterHealthProvider(context.Context, *RegisterHealthProviderRequest) (*RegisterHealthProviderResponse, error)
	mustEmbedUnimplementedRegisterHealthProviderServiceServer()
}

// UnimplementedRegisterHealthProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegisterHealthProviderServiceServer struct{}

func (UnimplementedRegisterHealthProviderServiceServer) RegisterHealthProvider(context.Context, *RegisterHealthProviderRequest) (*RegisterHealthProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterHealthProvider not implemented")
}
func (UnimplementedRegisterHealthProviderServiceServer) mustEmbedUnimplementedRegisterHealthProviderServiceServer() {
}
func (UnimplementedRegisterHealthProviderServiceServer) testEmbeddedByValue() {}

// UnsafeRegisterHealthProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegisterHealthProviderServiceServer will
// result in compilation errors.
type UnsafeRegisterHealthProviderServiceServer interface {
	mustEmbedUnimplementedRegisterHealthProviderServiceServer()
}

func RegisterRegisterHealthProviderServiceServer(s grpc.ServiceRegistrar, srv RegisterHealthProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedRegisterHealthProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegisterHealthProviderService_ServiceDesc, srv)
}

func _RegisterHealthProviderService_RegisterHealthProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterHealthProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterHealthProviderServiceServer).RegisterHealthProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegisterHealthProviderService_RegisterHealthProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterHealthProviderServiceServer).RegisterHealthProvider(ctx, req.(*RegisterHealthProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterHealthProviderService_ServiceDesc is the grpc.ServiceDesc for RegisterHealthProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegisterHealthProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.RegisterHealthProviderService",
	HandlerType: (*RegisterHealthProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterHealthProvider",
			Handler:    _RegisterHealthProviderService_RegisterHealthProvider_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

const (
	VerifyTokenService_VerifyToken_FullMethodName = "/auth.VerifyTokenService/VerifyToken"
)

// VerifyTokenServiceClient is the client API for VerifyTokenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --- Middleware as a service: other services call this to verify JWT and get claims ---
type VerifyTokenServiceClient interface {
	VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error)
}

type verifyTokenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVerifyTokenServiceClient(cc grpc.ClientConnInterface) VerifyTokenServiceClient {
	return &verifyTokenServiceClient{cc}
}

func (c *verifyTokenServiceClient) VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyTokenResponse)
	err := c.cc.Invoke(ctx, VerifyTokenService_VerifyToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifyTokenServiceServer is the server API for VerifyTokenService service.
// All implementations must embed UnimplementedVerifyTokenServiceServer
// for forward compatibility.
//
// --- Middleware as a service: other services call this to verify JWT and get claims ---
type VerifyTokenServiceServer interface {
	VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error)
	mustEmbedUnimplementedVerifyTokenServiceServer()
}

// UnimplementedVerifyTokenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVerifyTokenServiceServer struct{}

func (UnimplementedVerifyTokenServiceServer) VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedVerifyTokenServiceServer) mustEmbedUnimplementedVerifyTokenServiceServer() {}
func (UnimplementedVerifyTokenServiceServer) testEmbeddedByValue()                            {}

// UnsafeVerifyTokenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerifyTokenServiceServer will
// result in compilation errors.
type UnsafeVerifyTokenServiceServer interface {
	mustEmbedUnimplementedVerifyTokenServiceServer()
}

func RegisterVerifyTokenServiceServer(s grpc.ServiceRegistrar, srv VerifyTokenServiceServer) {
	// If the following call panics, it indicates UnimplementedVerifyTokenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VerifyTokenService_ServiceDesc, srv)
}

func _VerifyTokenService_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifyTokenServiceServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerifyTokenService_VerifyToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifyTokenServiceServer).VerifyToken(ctx, req.(*VerifyTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VerifyTokenService_ServiceDesc is the grpc.ServiceDesc for VerifyTokenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VerifyTokenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.VerifyTokenService",
	HandlerType: (*VerifyTokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyToken",
			Handler:    _VerifyTokenService_VerifyToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

const (
	LogoutService_Logout_FullMethodName = "/auth.LogoutService/Logout"
)

// LogoutServiceClient is the client API for LogoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --- Logout: invalidate session (delete auth row) ---
type LogoutServiceClient interface {
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
}

type logoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogoutServiceClient(cc grpc.ClientConnInterface) LogoutServiceClient {
	return &logoutServiceClient{cc}
}

func (c *logoutServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, LogoutService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogoutServiceServer is the server API for LogoutService service.
// All implementations must embed UnimplementedLogoutServiceServer
// for forward compatibility.
//
// --- Logout: invalidate session (delete auth row) ---
type LogoutServiceServer interface {
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	mustEmbedUnimplementedLogoutServiceServer()
}

// UnimplementedLogoutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogoutServiceServer struct{}

func (UnimplementedLogoutServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedLogoutServiceServer) mustEmbedUnimplementedLogoutServiceServer() {}
func (UnimplementedLogoutServiceServer) testEmbeddedByValue()                       {}

// UnsafeLogoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogoutServiceServer will
// result in compilation errors.
type UnsafeLogoutServiceServer interface {
	mustEmbedUnimplementedLogoutServiceServer()
}

func RegisterLogoutServiceServer(s grpc.ServiceRegistrar, srv LogoutServiceServer) {
	// If the following call panics, it indicates UnimplementedLogoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogoutService_ServiceDesc, srv)
}

func _LogoutService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogoutServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogoutService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogoutServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogoutService_ServiceDesc is the grpc.ServiceDesc for LogoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.LogoutService",
	HandlerType: (*LogoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Logout",
			Handler:    _LogoutService_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
