// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: patient.scheduling.proto

package scheduling

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchedulingService_ScheduleHealthStaffMeeting_FullMethodName   = "/patient.scheduling.SchedulingService/ScheduleHealthStaffMeeting"
	SchedulingService_AcceptScheduledMeeting_FullMethodName       = "/patient.scheduling.SchedulingService/AcceptScheduledMeeting"
	SchedulingService_RescheduleScheduledMeeting_FullMethodName   = "/patient.scheduling.SchedulingService/RescheduleScheduledMeeting"
	SchedulingService_ListScheduledMeetings_FullMethodName        = "/patient.scheduling.SchedulingService/ListScheduledMeetings"
	SchedulingService_CancelScheduledMeeting_FullMethodName       = "/patient.scheduling.SchedulingService/CancelScheduledMeeting"
	SchedulingService_ListSchedulableStaff_FullMethodName         = "/patient.scheduling.SchedulingService/ListSchedulableStaff"
	SchedulingService_RequestBridgedCallTransfer_FullMethodName   = "/patient.scheduling.SchedulingService/RequestBridgedCallTransfer"
	SchedulingService_ConnectBridgedCall_FullMethodName           = "/patient.scheduling.SchedulingService/ConnectBridgedCall"
	SchedulingService_GetBridgedCallSession_FullMethodName        = "/patient.scheduling.SchedulingService/GetBridgedCallSession"
	SchedulingService_ListBridgedCallSessions_FullMethodName      = "/patient.scheduling.SchedulingService/ListBridgedCallSessions"
	SchedulingService_UpdateBridgedCallTranslation_FullMethodName = "/patient.scheduling.SchedulingService/UpdateBridgedCallTranslation"
	SchedulingService_EndBridgedCall_FullMethodName               = "/patient.scheduling.SchedulingService/EndBridgedCall"
)

// SchedulingServiceClient is the client API for SchedulingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedulingServiceClient interface {
	ScheduleHealthStaffMeeting(ctx context.Context, in *ScheduleHealthStaffMeetingRequest, opts ...grpc.CallOption) (*ScheduleHealthStaffMeetingResponse, error)
	AcceptScheduledMeeting(ctx context.Context, in *AcceptScheduledMeetingRequest, opts ...grpc.CallOption) (*AcceptScheduledMeetingResponse, error)
	RescheduleScheduledMeeting(ctx context.Context, in *RescheduleScheduledMeetingRequest, opts ...grpc.CallOption) (*RescheduleScheduledMeetingResponse, error)
	ListScheduledMeetings(ctx context.Context, in *ListScheduledMeetingsRequest, opts ...grpc.CallOption) (*ListScheduledMeetingsResponse, error)
	CancelScheduledMeeting(ctx context.Context, in *CancelScheduledMeetingRequest, opts ...grpc.CallOption) (*CancelScheduledMeetingResponse, error)
	ListSchedulableStaff(ctx context.Context, in *ListSchedulableStaffRequest, opts ...grpc.CallOption) (*ListSchedulableStaffResponse, error)
	RequestBridgedCallTransfer(ctx context.Context, in *RequestBridgedCallTransferRequest, opts ...grpc.CallOption) (*RequestBridgedCallTransferResponse, error)
	ConnectBridgedCall(ctx context.Context, in *ConnectBridgedCallRequest, opts ...grpc.CallOption) (*ConnectBridgedCallResponse, error)
	GetBridgedCallSession(ctx context.Context, in *GetBridgedCallSessionRequest, opts ...grpc.CallOption) (*GetBridgedCallSessionResponse, error)
	ListBridgedCallSessions(ctx context.Context, in *ListBridgedCallSessionsRequest, opts ...grpc.CallOption) (*ListBridgedCallSessionsResponse, error)
	UpdateBridgedCallTranslation(ctx context.Context, in *UpdateBridgedCallTranslationRequest, opts ...grpc.CallOption) (*UpdateBridgedCallTranslationResponse, error)
	EndBridgedCall(ctx context.Context, in *EndBridgedCallRequest, opts ...grpc.CallOption) (*EndBridgedCallResponse, error)
}

type schedulingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulingServiceClient(cc grpc.ClientConnInterface) SchedulingServiceClient {
	return &schedulingServiceClient{cc}
}

func (c *schedulingServiceClient) ScheduleHealthStaffMeeting(ctx context.Context, in *ScheduleHealthStaffMeetingRequest, opts ...grpc.CallOption) (*ScheduleHealthStaffMeetingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleHealthStaffMeetingResponse)
	err := c.cc.Invoke(ctx, SchedulingService_ScheduleHealthStaffMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) AcceptScheduledMeeting(ctx context.Context, in *AcceptScheduledMeetingRequest, opts ...grpc.CallOption) (*AcceptScheduledMeetingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptScheduledMeetingResponse)
	err := c.cc.Invoke(ctx, SchedulingService_AcceptScheduledMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) RescheduleScheduledMeeting(ctx context.Context, in *RescheduleScheduledMeetingRequest, opts ...grpc.CallOption) (*RescheduleScheduledMeetingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RescheduleScheduledMeetingResponse)
	err := c.cc.Invoke(ctx, SchedulingService_RescheduleScheduledMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) ListScheduledMeetings(ctx context.Context, in *ListScheduledMeetingsRequest, opts ...grpc.CallOption) (*ListScheduledMeetingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScheduledMeetingsResponse)
	err := c.cc.Invoke(ctx, SchedulingService_ListScheduledMeetings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) CancelScheduledMeeting(ctx context.Context, in *CancelScheduledMeetingRequest, opts ...grpc.CallOption) (*CancelScheduledMeetingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelScheduledMeetingResponse)
	err := c.cc.Invoke(ctx, SchedulingService_CancelScheduledMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) ListSchedulableStaff(ctx context.Context, in *ListSchedulableStaffRequest, opts ...grpc.CallOption) (*ListSchedulableStaffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchedulableStaffResponse)
	err := c.cc.Invoke(ctx, SchedulingService_ListSchedulableStaff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) RequestBridgedCallTransfer(ctx context.Context, in *RequestBridgedCallTransferRequest, opts ...grpc.CallOption) (*RequestBridgedCallTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestBridgedCallTransferResponse)
	err := c.cc.Invoke(ctx, SchedulingService_RequestBridgedCallTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) ConnectBridgedCall(ctx context.Context, in *ConnectBridgedCallRequest, opts ...grpc.CallOption) (*ConnectBridgedCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectBridgedCallResponse)
	err := c.cc.Invoke(ctx, SchedulingService_ConnectBridgedCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) GetBridgedCallSession(ctx context.Context, in *GetBridgedCallSessionRequest, opts ...grpc.CallOption) (*GetBridgedCallSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBridgedCallSessionResponse)
	err := c.cc.Invoke(ctx, SchedulingService_GetBridgedCallSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) ListBridgedCallSessions(ctx context.Context, in *ListBridgedCallSessionsRequest, opts ...grpc.CallOption) (*ListBridgedCallSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBridgedCallSessionsResponse)
	err := c.cc.Invoke(ctx, SchedulingService_ListBridgedCallSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) UpdateBridgedCallTranslation(ctx context.Context, in *UpdateBridgedCallTranslationRequest, opts ...grpc.CallOption) (*UpdateBridgedCallTranslationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBridgedCallTranslationResponse)
	err := c.cc.Invoke(ctx, SchedulingService_UpdateBridgedCallTranslation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) EndBridgedCall(ctx context.Context, in *EndBridgedCallRequest, opts ...grpc.CallOption) (*EndBridgedCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndBridgedCallResponse)
	err := c.cc.Invoke(ctx, SchedulingService_EndBridgedCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulingServiceServer is the server API for SchedulingService service.
// All implementations must embed UnimplementedSchedulingServiceServer
// for forward compatibility.
type SchedulingServiceServer interface {
	ScheduleHealthStaffMeeting(context.Context, *ScheduleHealthStaffMeetingRequest) (*ScheduleHealthStaffMeetingResponse, error)
	AcceptScheduledMeeting(context.Context, *AcceptScheduledMeetingRequest) (*AcceptScheduledMeetingResponse, error)
	RescheduleScheduledMeeting(context.Context, *RescheduleScheduledMeetingRequest) (*RescheduleScheduledMeetingResponse, error)
	ListScheduledMeetings(context.Context, *ListScheduledMeetingsRequest) (*ListScheduledMeetingsResponse, error)
	CancelScheduledMeeting(context.Context, *CancelScheduledMeetingRequest) (*CancelScheduledMeetingResponse, error)
	ListSchedulableStaff(context.Context, *ListSchedulableStaffRequest) (*ListSchedulableStaffResponse, error)
	RequestBridgedCallTransfer(context.Context, *RequestBridgedCallTransferRequest) (*RequestBridgedCallTransferResponse, error)
	ConnectBridgedCall(context.Context, *ConnectBridgedCallRequest) (*ConnectBridgedCallResponse, error)
	GetBridgedCallSession(context.Context, *GetBridgedCallSessionRequest) (*GetBridgedCallSessionResponse, error)
	ListBridgedCallSessions(context.Context, *ListBridgedCallSessionsRequest) (*ListBridgedCallSessionsResponse, error)
	UpdateBridgedCallTranslation(context.Context, *UpdateBridgedCallTranslationRequest) (*UpdateBridgedCallTranslationResponse, error)
	EndBridgedCall(context.Context, *EndBridgedCallRequest) (*EndBridgedCallResponse, error)
	mustEmbedUnimplementedSchedulingServiceServer()
}

// UnimplementedSchedulingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulingServiceServer struct{}

func (UnimplementedSchedulingServiceServer) ScheduleHealthStaffMeeting(context.Context, *ScheduleHealthStaffMeetingRequest) (*ScheduleHealthStaffMeetingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScheduleHealthStaffMeeting not implemented")
}
func (UnimplementedSchedulingServiceServer) AcceptScheduledMeeting(context.Context, *AcceptScheduledMeetingRequest) (*AcceptScheduledMeetingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptScheduledMeeting not implemented")
}
func (UnimplementedSchedulingServiceServer) RescheduleScheduledMeeting(context.Context, *RescheduleScheduledMeetingRequest) (*RescheduleScheduledMeetingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RescheduleScheduledMeeting not implemented")
}
func (UnimplementedSchedulingServiceServer) ListScheduledMeetings(context.Context, *ListScheduledMeetingsRequest) (*ListScheduledMeetingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScheduledMeetings not implemented")
}
func (UnimplementedSchedulingServiceServer) CancelScheduledMeeting(context.Context, *CancelScheduledMeetingRequest) (*CancelScheduledMeetingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelScheduledMeeting not implemented")
}
func (UnimplementedSchedulingServiceServer) ListSchedulableStaff(context.Context, *ListSchedulableStaffRequest) (*ListSchedulableStaffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSchedulableStaff not implemented")
}
func (UnimplementedSchedulingServiceServer) RequestBridgedCallTransfer(context.Context, *RequestBridgedCallTransferRequest) (*RequestBridgedCallTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestBridgedCallTransfer not implemented")
}
func (UnimplementedSchedulingServiceServer) ConnectBridgedCall(context.Context, *ConnectBridgedCallRequest) (*ConnectBridgedCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectBridgedCall not implemented")
}
func (UnimplementedSchedulingServiceServer) GetBridgedCallSession(context.Context, *GetBridgedCallSessionRequest) (*GetBridgedCallSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBridgedCallSession not implemented")
}
func (UnimplementedSchedulingServiceServer) ListBridgedCallSessions(context.Context, *ListBridgedCallSessionsRequest) (*ListBridgedCallSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBridgedCallSessions not implemented")
}
func (UnimplementedSchedulingServiceServer) UpdateBridgedCallTranslation(context.Context, *UpdateBridgedCallTranslationRequest) (*UpdateBridgedCallTranslationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBridgedCallTranslation not implemented")
}
func (UnimplementedSchedulingServiceServer) EndBridgedCall(context.Context, *EndBridgedCallRequest) (*EndBridgedCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EndBridgedCall not implemented")
}
func (UnimplementedSchedulingServiceServer) mustEmbedUnimplementedSchedulingServiceServer() {}
func (UnimplementedSchedulingServiceServer) testEmbeddedByValue()                           {}

// UnsafeSchedulingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulingServiceServer will
// result in compilation errors.
type UnsafeSchedulingServiceServer interface {
	mustEmbedUnimplementedSchedulingServiceServer()
}

func RegisterSchedulingServiceServer(s grpc.ServiceRegistrar, srv SchedulingServiceServer) {
	// If the following call panics, it indicates UnimplementedSchedulingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchedulingService_ServiceDesc, srv)
}

func _SchedulingService_ScheduleHealthStaffMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleHealthStaffMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).ScheduleHealthStaffMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_ScheduleHealthStaffMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).ScheduleHealthStaffMeeting(ctx, req.(*ScheduleHealthStaffMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_AcceptScheduledMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptScheduledMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).AcceptScheduledMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_AcceptScheduledMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).AcceptScheduledMeeting(ctx, req.(*AcceptScheduledMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_RescheduleScheduledMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RescheduleScheduledMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).RescheduleScheduledMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_RescheduleScheduledMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).RescheduleScheduledMeeting(ctx, req.(*RescheduleScheduledMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_ListScheduledMeetings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScheduledMeetingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).ListScheduledMeetings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_ListScheduledMeetings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).ListScheduledMeetings(ctx, req.(*ListScheduledMeetingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_CancelScheduledMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelScheduledMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).CancelScheduledMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_CancelScheduledMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).CancelScheduledMeeting(ctx, req.(*CancelScheduledMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_ListSchedulableStaff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchedulableStaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).ListSchedulableStaff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_ListSchedulableStaff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).ListSchedulableStaff(ctx, req.(*ListSchedulableStaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_RequestBridgedCallTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestBridgedCallTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).RequestBridgedCallTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_RequestBridgedCallTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).RequestBridgedCallTransfer(ctx, req.(*RequestBridgedCallTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_ConnectBridgedCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectBridgedCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).ConnectBridgedCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_ConnectBridgedCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).ConnectBridgedCall(ctx, req.(*ConnectBridgedCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_GetBridgedCallSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBridgedCallSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).GetBridgedCallSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_GetBridgedCallSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).GetBridgedCallSession(ctx, req.(*GetBridgedCallSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_ListBridgedCallSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBridgedCallSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).ListBridgedCallSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_ListBridgedCallSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).ListBridgedCallSessions(ctx, req.(*ListBridgedCallSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_UpdateBridgedCallTranslation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBridgedCallTranslationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).UpdateBridgedCallTranslation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_UpdateBridgedCallTranslation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).UpdateBridgedCallTranslation(ctx, req.(*UpdateBridgedCallTranslationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_EndBridgedCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndBridgedCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).EndBridgedCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_EndBridgedCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).EndBridgedCall(ctx, req.(*EndBridgedCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SchedulingService_ServiceDesc is the grpc.ServiceDesc for SchedulingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedulingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "patient.scheduling.SchedulingService",
	HandlerType: (*SchedulingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScheduleHealthStaffMeeting",
			Handler:    _SchedulingService_ScheduleHealthStaffMeeting_Handler,
		},
		{
			MethodName: "AcceptScheduledMeeting",
			Handler:    _SchedulingService_AcceptScheduledMeeting_Handler,
		},
		{
			MethodName: "RescheduleScheduledMeeting",
			Handler:    _SchedulingService_RescheduleScheduledMeeting_Handler,
		},
		{
			MethodName: "ListScheduledMeetings",
			Handler:    _SchedulingService_ListScheduledMeetings_Handler,
		},
		{
			MethodName: "CancelScheduledMeeting",
			Handler:    _SchedulingService_CancelScheduledMeeting_Handler,
		},
		{
			MethodName: "ListSchedulableStaff",
			Handler:    _SchedulingService_ListSchedulableStaff_Handler,
		},
		{
			MethodName: "RequestBridgedCallTransfer",
			Handler:    _SchedulingService_RequestBridgedCallTransfer_Handler,
		},
		{
			MethodName: "ConnectBridgedCall",
			Handler:    _SchedulingService_ConnectBridgedCall_Handler,
		},
		{
			MethodName: "GetBridgedCallSession",
			Handler:    _SchedulingService_GetBridgedCallSession_Handler,
		},
		{
			MethodName: "ListBridgedCallSessions",
			Handler:    _SchedulingService_ListBridgedCallSessions_Handler,
		},
		{
			MethodName: "UpdateBridgedCallTranslation",
			Handler:    _SchedulingService_UpdateBridgedCallTranslation_Handler,
		},
		{
			MethodName: "EndBridgedCall",
			Handler:    _SchedulingService_EndBridgedCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "patient.scheduling.proto",
}
