// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: patient.scheduling.proto

package scheduling

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScheduleHealthStaffMeetingRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PatientId       string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	StaffId         string                 `protobuf:"bytes,2,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	HospitalId      string                 `protobuf:"bytes,3,opt,name=hospital_id,json=hospitalId,proto3" json:"hospital_id,omitempty"`
	StartsAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,5,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	Timezone        string                 `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Title           string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Notes           string                 `protobuf:"bytes,8,opt,name=notes,proto3" json:"notes,omitempty"`
	Channel         string                 `protobuf:"bytes,9,opt,name=channel,proto3" json:"channel,omitempty"` // voice | portal | dashboard
	CorrelationId   string                 `protobuf:"bytes,10,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	VoiceSessionId  string                 `protobuf:"bytes,11,opt,name=voice_session_id,json=voiceSessionId,proto3" json:"voice_session_id,omitempty"`
	SendSms         bool                   `protobuf:"varint,12,opt,name=send_sms,json=sendSms,proto3" json:"send_sms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScheduleHealthStaffMeetingRequest) Reset() {
	*x = ScheduleHealthStaffMeetingRequest{}
	mi := &file_patient_scheduling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleHealthStaffMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleHealthStaffMeetingRequest) ProtoMessage() {}

func (x *ScheduleHealthStaffMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleHealthStaffMeetingRequest.ProtoReflect.Descriptor instead.
func (*ScheduleHealthStaffMeetingRequest) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleHealthStaffMeetingRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ScheduleHealthStaffMeetingRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *ScheduleHealthStaffMeetingRequest) GetHospitalId() string {
	if x != nil {
		return x.HospitalId
	}
	return ""
}

func (x *ScheduleHealthStaffMeetingRequest) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *ScheduleHealthStaffMeetingRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *ScheduleHealthStaffMeetingRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *ScheduleHealthStaffMeetingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ScheduleHealthStaffMeetingRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *ScheduleHealthStaffMeetingRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ScheduleHealthStaffMeetingRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ScheduleHealthStaffMeetingRequest) GetVoiceSessionId() string {
	if x != nil {
		return x.VoiceSessionId
	}
	return ""
}

func (x *ScheduleHealthStaffMeetingRequest) GetSendSms() bool {
	if x != nil {
		return x.SendSms
	}
	return false
}

type ScheduledMeeting struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId       string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	StaffId         string                 `protobuf:"bytes,3,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	HospitalId      string                 `protobuf:"bytes,4,opt,name=hospital_id,json=hospitalId,proto3" json:"hospital_id,omitempty"`
	StartsAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,6,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	Timezone        string                 `protobuf:"bytes,7,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Title           string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	JoinUrl         string                 `protobuf:"bytes,9,opt,name=join_url,json=joinUrl,proto3" json:"join_url,omitempty"`
	Status          string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	CorrelationId   string                 `protobuf:"bytes,11,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	LivekitRoomName string                 `protobuf:"bytes,12,opt,name=livekit_room_name,json=livekitRoomName,proto3" json:"livekit_room_name,omitempty"`
	PatientToken    string                 `protobuf:"bytes,13,opt,name=patient_token,json=patientToken,proto3" json:"patient_token,omitempty"`
	StaffToken      string                 `protobuf:"bytes,14,opt,name=staff_token,json=staffToken,proto3" json:"staff_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScheduledMeeting) Reset() {
	*x = ScheduledMeeting{}
	mi := &file_patient_scheduling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledMeeting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledMeeting) ProtoMessage() {}

func (x *ScheduledMeeting) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledMeeting.ProtoReflect.Descriptor instead.
func (*ScheduledMeeting) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduledMeeting) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScheduledMeeting) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ScheduledMeeting) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *ScheduledMeeting) GetHospitalId() string {
	if x != nil {
		return x.HospitalId
	}
	return ""
}

func (x *ScheduledMeeting) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *ScheduledMeeting) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *ScheduledMeeting) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *ScheduledMeeting) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ScheduledMeeting) GetJoinUrl() string {
	if x != nil {
		return x.JoinUrl
	}
	return ""
}

func (x *ScheduledMeeting) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScheduledMeeting) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ScheduledMeeting) GetLivekitRoomName() string {
	if x != nil {
		return x.LivekitRoomName
	}
	return ""
}

func (x *ScheduledMeeting) GetPatientToken() string {
	if x != nil {
		return x.PatientToken
	}
	return ""
}

func (x *ScheduledMeeting) GetStaffToken() string {
	if x != nil {
		return x.StaffToken
	}
	return ""
}

type ScheduleHealthStaffMeetingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meeting       *ScheduledMeeting      `protobuf:"bytes,1,opt,name=meeting,proto3" json:"meeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleHealthStaffMeetingResponse) Reset() {
	*x = ScheduleHealthStaffMeetingResponse{}
	mi := &file_patient_scheduling_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleHealthStaffMeetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleHealthStaffMeetingResponse) ProtoMessage() {}

func (x *ScheduleHealthStaffMeetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleHealthStaffMeetingResponse.ProtoReflect.Descriptor instead.
func (*ScheduleHealthStaffMeetingResponse) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{2}
}

func (x *ScheduleHealthStaffMeetingResponse) GetMeeting() *ScheduledMeeting {
	if x != nil {
		return x.Meeting
	}
	return nil
}

type AcceptScheduledMeetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptScheduledMeetingRequest) Reset() {
	*x = AcceptScheduledMeetingRequest{}
	mi := &file_patient_scheduling_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptScheduledMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptScheduledMeetingRequest) ProtoMessage() {}

func (x *AcceptScheduledMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptScheduledMeetingRequest.ProtoReflect.Descriptor instead.
func (*AcceptScheduledMeetingRequest) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptScheduledMeetingRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

type AcceptScheduledMeetingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meeting       *ScheduledMeeting      `protobuf:"bytes,1,opt,name=meeting,proto3" json:"meeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptScheduledMeetingResponse) Reset() {
	*x = AcceptScheduledMeetingResponse{}
	mi := &file_patient_scheduling_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptScheduledMeetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptScheduledMeetingResponse) ProtoMessage() {}

func (x *AcceptScheduledMeetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptScheduledMeetingResponse.ProtoReflect.Descriptor instead.
func (*AcceptScheduledMeetingResponse) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptScheduledMeetingResponse) GetMeeting() *ScheduledMeeting {
	if x != nil {
		return x.Meeting
	}
	return nil
}

type RescheduleScheduledMeetingRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MeetingId       string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	StartsAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,3,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	Timezone        string                 `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Title           string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RescheduleScheduledMeetingRequest) Reset() {
	*x = RescheduleScheduledMeetingRequest{}
	mi := &file_patient_scheduling_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescheduleScheduledMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescheduleScheduledMeetingRequest) ProtoMessage() {}

func (x *RescheduleScheduledMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescheduleScheduledMeetingRequest.ProtoReflect.Descriptor instead.
func (*RescheduleScheduledMeetingRequest) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{5}
}

func (x *RescheduleScheduledMeetingRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *RescheduleScheduledMeetingRequest) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *RescheduleScheduledMeetingRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *RescheduleScheduledMeetingRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *RescheduleScheduledMeetingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type RescheduleScheduledMeetingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meeting       *ScheduledMeeting      `protobuf:"bytes,1,opt,name=meeting,proto3" json:"meeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RescheduleScheduledMeetingResponse) Reset() {
	*x = RescheduleScheduledMeetingResponse{}
	mi := &file_patient_scheduling_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescheduleScheduledMeetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescheduleScheduledMeetingResponse) ProtoMessage() {}

func (x *RescheduleScheduledMeetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescheduleScheduledMeetingResponse.ProtoReflect.Descriptor instead.
func (*RescheduleScheduledMeetingResponse) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{6}
}

func (x *RescheduleScheduledMeetingResponse) GetMeeting() *ScheduledMeeting {
	if x != nil {
		return x.Meeting
	}
	return nil
}

type ListScheduledMeetingsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PatientId        string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	StaffId          string                 `protobuf:"bytes,2,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	HospitalId       string                 `protobuf:"bytes,3,opt,name=hospital_id,json=hospitalId,proto3" json:"hospital_id,omitempty"`
	IncludeCancelled bool                   `protobuf:"varint,4,opt,name=include_cancelled,json=includeCancelled,proto3" json:"include_cancelled,omitempty"`
	Limit            int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListScheduledMeetingsRequest) Reset() {
	*x = ListScheduledMeetingsRequest{}
	mi := &file_patient_scheduling_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduledMeetingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledMeetingsRequest) ProtoMessage() {}

func (x *ListScheduledMeetingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledMeetingsRequest.ProtoReflect.Descriptor instead.
func (*ListScheduledMeetingsRequest) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{7}
}

func (x *ListScheduledMeetingsRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ListScheduledMeetingsRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *ListScheduledMeetingsRequest) GetHospitalId() string {
	if x != nil {
		return x.HospitalId
	}
	return ""
}

func (x *ListScheduledMeetingsRequest) GetIncludeCancelled() bool {
	if x != nil {
		return x.IncludeCancelled
	}
	return false
}

func (x *ListScheduledMeetingsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListScheduledMeetingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meetings      []*ScheduledMeeting    `protobuf:"bytes,1,rep,name=meetings,proto3" json:"meetings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduledMeetingsResponse) Reset() {
	*x = ListScheduledMeetingsResponse{}
	mi := &file_patient_scheduling_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduledMeetingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledMeetingsResponse) ProtoMessage() {}

func (x *ListScheduledMeetingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledMeetingsResponse.ProtoReflect.Descriptor instead.
func (*ListScheduledMeetingsResponse) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{8}
}

func (x *ListScheduledMeetingsResponse) GetMeetings() []*ScheduledMeeting {
	if x != nil {
		return x.Meetings
	}
	return nil
}

type CancelScheduledMeetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelScheduledMeetingRequest) Reset() {
	*x = CancelScheduledMeetingRequest{}
	mi := &file_patient_scheduling_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelScheduledMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelScheduledMeetingRequest) ProtoMessage() {}

func (x *CancelScheduledMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelScheduledMeetingRequest.ProtoReflect.Descriptor instead.
func (*CancelScheduledMeetingRequest) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{9}
}

func (x *CancelScheduledMeetingRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *CancelScheduledMeetingRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelScheduledMeetingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meeting       *ScheduledMeeting      `protobuf:"bytes,1,opt,name=meeting,proto3" json:"meeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelScheduledMeetingResponse) Reset() {
	*x = CancelScheduledMeetingResponse{}
	mi := &file_patient_scheduling_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelScheduledMeetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelScheduledMeetingResponse) ProtoMessage() {}

func (x *CancelScheduledMeetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelScheduledMeetingResponse.ProtoReflect.Descriptor instead.
func (*CancelScheduledMeetingResponse) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{10}
}

func (x *CancelScheduledMeetingResponse) GetMeeting() *ScheduledMeeting {
	if x != nil {
		return x.Meeting
	}
	return nil
}

type ListSchedulableStaffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	HospitalId    string                 `protobuf:"bytes,2,opt,name=hospital_id,json=hospitalId,proto3" json:"hospital_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulableStaffRequest) Reset() {
	*x = ListSchedulableStaffRequest{}
	mi := &file_patient_scheduling_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulableStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulableStaffRequest) ProtoMessage() {}

func (x *ListSchedulableStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulableStaffRequest.ProtoReflect.Descriptor instead.
func (*ListSchedulableStaffRequest) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{11}
}

func (x *ListSchedulableStaffRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ListSchedulableStaffRequest) GetHospitalId() string {
	if x != nil {
		return x.HospitalId
	}
	return ""
}

type StaffSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffId       string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	HospitalId    string                 `protobuf:"bytes,2,opt,name=hospital_id,json=hospitalId,proto3" json:"hospital_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaffSummary) Reset() {
	*x = StaffSummary{}
	mi := &file_patient_scheduling_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaffSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffSummary) ProtoMessage() {}

func (x *StaffSummary) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffSummary.ProtoReflect.Descriptor instead.
func (*StaffSummary) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{12}
}

func (x *StaffSummary) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *StaffSummary) GetHospitalId() string {
	if x != nil {
		return x.HospitalId
	}
	return ""
}

func (x *StaffSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StaffSummary) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *StaffSummary) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ListSchedulableStaffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         []*StaffSummary        `protobuf:"bytes,1,rep,name=staff,proto3" json:"staff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulableStaffResponse) Reset() {
	*x = ListSchedulableStaffResponse{}
	mi := &file_patient_scheduling_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulableStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulableStaffResponse) ProtoMessage() {}

func (x *ListSchedulableStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulableStaffResponse.ProtoReflect.Descriptor instead.
func (*ListSchedulableStaffResponse) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{13}
}

func (x *ListSchedulableStaffResponse) GetStaff() []*StaffSummary {
	if x != nil {
		return x.Staff
	}
	return nil
}

type BridgedCallTranslationPreferences struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Enabled             bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	LanguageMode        string                 `protobuf:"bytes,2,opt,name=language_mode,json=languageMode,proto3" json:"language_mode,omitempty"` // auto | manual
	LanguageCode        string                 `protobuf:"bytes,3,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	ParticipantIdentity string                 `protobuf:"bytes,4,opt,name=participant_identity,json=participantIdentity,proto3" json:"participant_identity,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BridgedCallTranslationPreferences) Reset() {
	*x = BridgedCallTranslationPreferences{}
	mi := &file_patient_scheduling_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgedCallTranslationPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgedCallTranslationPreferences) ProtoMessage() {}

func (x *BridgedCallTranslationPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgedCallTranslationPreferences.ProtoReflect.Descriptor instead.
func (*BridgedCallTranslationPreferences) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{14}
}

func (x *BridgedCallTranslationPreferences) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *BridgedCallTranslationPreferences) GetLanguageMode() string {
	if x != nil {
		return x.LanguageMode
	}
	return ""
}

func (x *BridgedCallTranslationPreferences) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *BridgedCallTranslationPreferences) GetParticipantIdentity() string {
	if x != nil {
		return x.ParticipantIdentity
	}
	return ""
}

func (x *BridgedCallTranslationPreferences) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type BridgedCallSession struct {
	state                protoimpl.MessageState             `protogen:"open.v1"`
	SessionId            string                             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomSid              string                             `protobuf:"bytes,2,opt,name=room_sid,json=roomSid,proto3" json:"room_sid,omitempty"`
	PatientId            string                             `protobuf:"bytes,3,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	HospitalId           string                             `protobuf:"bytes,4,opt,name=hospital_id,json=hospitalId,proto3" json:"hospital_id,omitempty"`
	StaffId              string                             `protobuf:"bytes,5,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	Status               string                             `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // transfer_requested | connected | ended
	RequestedByActorType string                             `protobuf:"bytes,7,opt,name=requested_by_actor_type,json=requestedByActorType,proto3" json:"requested_by_actor_type,omitempty"`
	RequestedByActorId   string                             `protobuf:"bytes,8,opt,name=requested_by_actor_id,json=requestedByActorId,proto3" json:"requested_by_actor_id,omitempty"`
	TransferReason       string                             `protobuf:"bytes,9,opt,name=transfer_reason,json=transferReason,proto3" json:"transfer_reason,omitempty"`
	RequestedAt          *timestamppb.Timestamp             `protobuf:"bytes,10,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	ConnectedAt          *timestamppb.Timestamp             `protobuf:"bytes,11,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	EndedAt              *timestamppb.Timestamp             `protobuf:"bytes,12,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	PatientTranslation   *BridgedCallTranslationPreferences `protobuf:"bytes,13,opt,name=patient_translation,json=patientTranslation,proto3" json:"patient_translation,omitempty"`
	StaffTranslation     *BridgedCallTranslationPreferences `protobuf:"bytes,14,opt,name=staff_translation,json=staffTranslation,proto3" json:"staff_translation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BridgedCallSession) Reset() {
	*x = BridgedCallSession{}
	mi := &file_patient_scheduling_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgedCallSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgedCallSession) ProtoMessage() {}

func (x *BridgedCallSession) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgedCallSession.ProtoReflect.Descriptor instead.
func (*BridgedCallSession) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{15}
}

func (x *BridgedCallSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BridgedCallSession) GetRoomSid() string {
	if x != nil {
		return x.RoomSid
	}
	return ""
}

func (x *BridgedCallSession) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *BridgedCallSession) GetHospitalId() string {
	if x != nil {
		return x.HospitalId
	}
	return ""
}

func (x *BridgedCallSession) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *BridgedCallSession) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BridgedCallSession) GetRequestedByActorType() string {
	if x != nil {
		return x.RequestedByActorType
	}
	return ""
}

func (x *BridgedCallSession) GetRequestedByActorId() string {
	if x != nil {
		return x.RequestedByActorId
	}
	return ""
}

func (x *BridgedCallSession) GetTransferReason() string {
	if x != nil {
		return x.TransferReason
	}
	return ""
}

func (x *BridgedCallSession) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

func (x *BridgedCallSession) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *BridgedCallSession) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *BridgedCallSession) GetPatientTranslation() *BridgedCallTranslationPreferences {
	if x != nil {
		return x.PatientTranslation
	}
	return nil
}

func (x *BridgedCallSession) GetStaffTranslation() *BridgedCallTranslationPreferences {
	if x != nil {
		return x.StaffTranslation
	}
	return nil
}

type RequestBridgedCallTransferRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomSid        string                 `protobuf:"bytes,2,opt,name=room_sid,json=roomSid,proto3" json:"room_sid,omitempty"`
	PatientId      string                 `protobuf:"bytes,3,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	HospitalId     string                 `protobuf:"bytes,4,opt,name=hospital_id,json=hospitalId,proto3" json:"hospital_id,omitempty"`
	StaffId        string                 `protobuf:"bytes,5,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	TransferReason string                 `protobuf:"bytes,6,opt,name=transfer_reason,json=transferReason,proto3" json:"transfer_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestBridgedCallTransferRequest) Reset() {
	*x = RequestBridgedCallTransferRequest{}
	mi := &file_patient_scheduling_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestBridgedCallTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBridgedCallTransferRequest) ProtoMessage() {}

func (x *RequestBridgedCallTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBridgedCallTransferRequest.ProtoReflect.Descriptor instead.
func (*RequestBridgedCallTransferRequest) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{16}
}

func (x *RequestBridgedCallTransferRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RequestBridgedCallTransferRequest) GetRoomSid() string {
	if x != nil {
		return x.RoomSid
	}
	return ""
}

func (x *RequestBridgedCallTransferRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *RequestBridgedCallTransferRequest) GetHospitalId() string {
	if x != nil {
		return x.HospitalId
	}
	return ""
}

func (x *RequestBridgedCallTransferRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *RequestBridgedCallTransferRequest) GetTransferReason() string {
	if x != nil {
		return x.TransferReason
	}
	return ""
}

type RequestBridgedCallTransferResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Session          *BridgedCallSession    `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	PatientRoomToken string                 `protobuf:"bytes,2,opt,name=patient_room_token,json=patientRoomToken,proto3" json:"patient_room_token,omitempty"`
	LivekitWsUrl     string                 `protobuf:"bytes,3,opt,name=livekit_ws_url,json=livekitWsUrl,proto3" json:"livekit_ws_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RequestBridgedCallTransferResponse) Reset() {
	*x = RequestBridgedCallTransferResponse{}
	mi := &file_patient_scheduling_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestBridgedCallTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBridgedCallTransferResponse) ProtoMessage() {}

func (x *RequestBridgedCallTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBridgedCallTransferResponse.ProtoReflect.Descriptor instead.
func (*RequestBridgedCallTransferResponse) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{17}
}

func (x *RequestBridgedCallTransferResponse) GetSession() *BridgedCallSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *RequestBridgedCallTransferResponse) GetPatientRoomToken() string {
	if x != nil {
		return x.PatientRoomToken
	}
	return ""
}

func (x *RequestBridgedCallTransferResponse) GetLivekitWsUrl() string {
	if x != nil {
		return x.LivekitWsUrl
	}
	return ""
}

type ConnectBridgedCallRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SessionId                string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StaffId                  string                 `protobuf:"bytes,2,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	StaffParticipantIdentity string                 `protobuf:"bytes,3,opt,name=staff_participant_identity,json=staffParticipantIdentity,proto3" json:"staff_participant_identity,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ConnectBridgedCallRequest) Reset() {
	*x = ConnectBridgedCallRequest{}
	mi := &file_patient_scheduling_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectBridgedCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectBridgedCallRequest) ProtoMessage() {}

func (x *ConnectBridgedCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectBridgedCallRequest.ProtoReflect.Descriptor instead.
func (*ConnectBridgedCallRequest) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{18}
}

func (x *ConnectBridgedCallRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConnectBridgedCallRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *ConnectBridgedCallRequest) GetStaffParticipantIdentity() string {
	if x != nil {
		return x.StaffParticipantIdentity
	}
	return ""
}

type ConnectBridgedCallResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Session *BridgedCallSession    `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// LiveKit join token for the connecting staff member (not persisted).
	StaffRoomToken   string `protobuf:"bytes,2,opt,name=staff_room_token,json=staffRoomToken,proto3" json:"staff_room_token,omitempty"`
	LivekitWsUrl     string `protobuf:"bytes,3,opt,name=livekit_ws_url,json=livekitWsUrl,proto3" json:"livekit_ws_url,omitempty"`
	PatientRoomToken string `protobuf:"bytes,4,opt,name=patient_room_token,json=patientRoomToken,proto3" json:"patient_room_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectBridgedCallResponse) Reset() {
	*x = ConnectBridgedCallResponse{}
	mi := &file_patient_scheduling_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectBridgedCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectBridgedCallResponse) ProtoMessage() {}

func (x *ConnectBridgedCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectBridgedCallResponse.ProtoReflect.Descriptor instead.
func (*ConnectBridgedCallResponse) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{19}
}

func (x *ConnectBridgedCallResponse) GetSession() *BridgedCallSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *ConnectBridgedCallResponse) GetStaffRoomToken() string {
	if x != nil {
		return x.StaffRoomToken
	}
	return ""
}

func (x *ConnectBridgedCallResponse) GetLivekitWsUrl() string {
	if x != nil {
		return x.LivekitWsUrl
	}
	return ""
}

func (x *ConnectBridgedCallResponse) GetPatientRoomToken() string {
	if x != nil {
		return x.PatientRoomToken
	}
	return ""
}

type GetBridgedCallSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBridgedCallSessionRequest) Reset() {
	*x = GetBridgedCallSessionRequest{}
	mi := &file_patient_scheduling_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBridgedCallSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBridgedCallSessionRequest) ProtoMessage() {}

func (x *GetBridgedCallSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBridgedCallSessionRequest.ProtoReflect.Descriptor instead.
func (*GetBridgedCallSessionRequest) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{20}
}

func (x *GetBridgedCallSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetBridgedCallSessionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Session          *BridgedCallSession    `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	PatientRoomToken string                 `protobuf:"bytes,2,opt,name=patient_room_token,json=patientRoomToken,proto3" json:"patient_room_token,omitempty"`
	LivekitWsUrl     string                 `protobuf:"bytes,3,opt,name=livekit_ws_url,json=livekitWsUrl,proto3" json:"livekit_ws_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetBridgedCallSessionResponse) Reset() {
	*x = GetBridgedCallSessionResponse{}
	mi := &file_patient_scheduling_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBridgedCallSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBridgedCallSessionResponse) ProtoMessage() {}

func (x *GetBridgedCallSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBridgedCallSessionResponse.ProtoReflect.Descriptor instead.
func (*GetBridgedCallSessionResponse) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{21}
}

func (x *GetBridgedCallSessionResponse) GetSession() *BridgedCallSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *GetBridgedCallSessionResponse) GetPatientRoomToken() string {
	if x != nil {
		return x.PatientRoomToken
	}
	return ""
}

func (x *GetBridgedCallSessionResponse) GetLivekitWsUrl() string {
	if x != nil {
		return x.LivekitWsUrl
	}
	return ""
}

type ListBridgedCallSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // optional: transfer_requested | connected | ended
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBridgedCallSessionsRequest) Reset() {
	*x = ListBridgedCallSessionsRequest{}
	mi := &file_patient_scheduling_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBridgedCallSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBridgedCallSessionsRequest) ProtoMessage() {}

func (x *ListBridgedCallSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBridgedCallSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListBridgedCallSessionsRequest) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{22}
}

func (x *ListBridgedCallSessionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListBridgedCallSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListBridgedCallSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*BridgedCallSession  `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBridgedCallSessionsResponse) Reset() {
	*x = ListBridgedCallSessionsResponse{}
	mi := &file_patient_scheduling_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBridgedCallSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBridgedCallSessionsResponse) ProtoMessage() {}

func (x *ListBridgedCallSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBridgedCallSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListBridgedCallSessionsResponse) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{23}
}

func (x *ListBridgedCallSessionsResponse) GetSessions() []*BridgedCallSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type UpdateBridgedCallTranslationRequest struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	SessionId     string                             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Participant   string                             `protobuf:"bytes,2,opt,name=participant,proto3" json:"participant,omitempty"` // patient | staff
	Translation   *BridgedCallTranslationPreferences `protobuf:"bytes,3,opt,name=translation,proto3" json:"translation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBridgedCallTranslationRequest) Reset() {
	*x = UpdateBridgedCallTranslationRequest{}
	mi := &file_patient_scheduling_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBridgedCallTranslationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBridgedCallTranslationRequest) ProtoMessage() {}

func (x *UpdateBridgedCallTranslationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBridgedCallTranslationRequest.ProtoReflect.Descriptor instead.
func (*UpdateBridgedCallTranslationRequest) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateBridgedCallTranslationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateBridgedCallTranslationRequest) GetParticipant() string {
	if x != nil {
		return x.Participant
	}
	return ""
}

func (x *UpdateBridgedCallTranslationRequest) GetTranslation() *BridgedCallTranslationPreferences {
	if x != nil {
		return x.Translation
	}
	return nil
}

type UpdateBridgedCallTranslationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *BridgedCallSession    `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBridgedCallTranslationResponse) Reset() {
	*x = UpdateBridgedCallTranslationResponse{}
	mi := &file_patient_scheduling_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBridgedCallTranslationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBridgedCallTranslationResponse) ProtoMessage() {}

func (x *UpdateBridgedCallTranslationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBridgedCallTranslationResponse.ProtoReflect.Descriptor instead.
func (*UpdateBridgedCallTranslationResponse) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateBridgedCallTranslationResponse) GetSession() *BridgedCallSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type EndBridgedCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndBridgedCallRequest) Reset() {
	*x = EndBridgedCallRequest{}
	mi := &file_patient_scheduling_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndBridgedCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndBridgedCallRequest) ProtoMessage() {}

func (x *EndBridgedCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndBridgedCallRequest.ProtoReflect.Descriptor instead.
func (*EndBridgedCallRequest) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{26}
}

func (x *EndBridgedCallRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndBridgedCallRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EndBridgedCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *BridgedCallSession    `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndBridgedCallResponse) Reset() {
	*x = EndBridgedCallResponse{}
	mi := &file_patient_scheduling_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndBridgedCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndBridgedCallResponse) ProtoMessage() {}

func (x *EndBridgedCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_scheduling_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndBridgedCallResponse.ProtoReflect.Descriptor instead.
func (*EndBridgedCallResponse) Descriptor() ([]byte, []int) {
	return file_patient_scheduling_proto_rawDescGZIP(), []int{27}
}

func (x *EndBridgedCallResponse) GetSession() *BridgedCallSession {
	if x != nil {
		return x.Session
	}
	return nil
}

var File_patient_scheduling_proto protoreflect.FileDescriptor

const file_patient_scheduling_proto_rawDesc = "" +
	"\n" +
	"\x18patient.scheduling.proto\x12\x12patient.scheduling\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x03\n" +
	"!ScheduleHealthStaffMeetingRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12\x19\n" +
	"\bstaff_id\x18\x02 \x01(\tR\astaffId\x12\x1f\n" +
	"\vhospital_id\x18\x03 \x01(\tR\n" +
	"hospitalId\x127\n" +
	"\tstarts_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x12)\n" +
	"\x10duration_minutes\x18\x05 \x01(\x05R\x0fdurationMinutes\x12\x1a\n" +
	"\btimezone\x18\x06 \x01(\tR\btimezone\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12\x14\n" +
	"\x05notes\x18\b \x01(\tR\x05notes\x12\x18\n" +
	"\achannel\x18\t \x01(\tR\achannel\x12%\n" +
	"\x0ecorrelation_id\x18\n" +
	" \x01(\tR\rcorrelationId\x12(\n" +
	"\x10voice_session_id\x18\v \x01(\tR\x0evoiceSessionId\x12\x19\n" +
	"\bsend_sms\x18\f \x01(\bR\asendSms\"\xdf\x03\n" +
	"\x10ScheduledMeeting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x19\n" +
	"\bstaff_id\x18\x03 \x01(\tR\astaffId\x12\x1f\n" +
	"\vhospital_id\x18\x04 \x01(\tR\n" +
	"hospitalId\x127\n" +
	"\tstarts_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x12)\n" +
	"\x10duration_minutes\x18\x06 \x01(\x05R\x0fdurationMinutes\x12\x1a\n" +
	"\btimezone\x18\a \x01(\tR\btimezone\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12\x19\n" +
	"\bjoin_url\x18\t \x01(\tR\ajoinUrl\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12%\n" +
	"\x0ecorrelation_id\x18\v \x01(\tR\rcorrelationId\x12*\n" +
	"\x11livekit_room_name\x18\f \x01(\tR\x0flivekitRoomName\x12#\n" +
	"\rpatient_token\x18\r \x01(\tR\fpatientToken\x12\x1f\n" +
	"\vstaff_token\x18\x0e \x01(\tR\n" +
	"staffToken\"d\n" +
	"\"ScheduleHealthStaffMeetingResponse\x12>\n" +
	"\ameeting\x18\x01 \x01(\v2$.patient.scheduling.ScheduledMeetingR\ameeting\">\n" +
	"\x1dAcceptScheduledMeetingRequest\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\"`\n" +
	"\x1eAcceptScheduledMeetingResponse\x12>\n" +
	"\ameeting\x18\x01 \x01(\v2$.patient.scheduling.ScheduledMeetingR\ameeting\"\xd8\x01\n" +
	"!RescheduleScheduledMeetingRequest\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x127\n" +
	"\tstarts_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x12)\n" +
	"\x10duration_minutes\x18\x03 \x01(\x05R\x0fdurationMinutes\x12\x1a\n" +
	"\btimezone\x18\x04 \x01(\tR\btimezone\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\"d\n" +
	"\"RescheduleScheduledMeetingResponse\x12>\n" +
	"\ameeting\x18\x01 \x01(\v2$.patient.scheduling.ScheduledMeetingR\ameeting\"\xbc\x01\n" +
	"\x1cListScheduledMeetingsRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12\x19\n" +
	"\bstaff_id\x18\x02 \x01(\tR\astaffId\x12\x1f\n" +
	"\vhospital_id\x18\x03 \x01(\tR\n" +
	"hospitalId\x12+\n" +
	"\x11include_cancelled\x18\x04 \x01(\bR\x10includeCancelled\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"a\n" +
	"\x1dListScheduledMeetingsResponse\x12@\n" +
	"\bmeetings\x18\x01 \x03(\v2$.patient.scheduling.ScheduledMeetingR\bmeetings\"V\n" +
	"\x1dCancelScheduledMeetingRequest\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"`\n" +
	"\x1eCancelScheduledMeetingResponse\x12>\n" +
	"\ameeting\x18\x01 \x01(\v2$.patient.scheduling.ScheduledMeetingR\ameeting\"]\n" +
	"\x1bListSchedulableStaffRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12\x1f\n" +
	"\vhospital_id\x18\x02 \x01(\tR\n" +
	"hospitalId\"\x88\x01\n" +
	"\fStaffSummary\x12\x19\n" +
	"\bstaff_id\x18\x01 \x01(\tR\astaffId\x12\x1f\n" +
	"\vhospital_id\x18\x02 \x01(\tR\n" +
	"hospitalId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\"V\n" +
	"\x1cListSchedulableStaffResponse\x126\n" +
	"\x05staff\x18\x01 \x03(\v2 .patient.scheduling.StaffSummaryR\x05staff\"\xf5\x01\n" +
	"!BridgedCallTranslationPreferences\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12#\n" +
	"\rlanguage_mode\x18\x02 \x01(\tR\flanguageMode\x12#\n" +
	"\rlanguage_code\x18\x03 \x01(\tR\flanguageCode\x121\n" +
	"\x14participant_identity\x18\x04 \x01(\tR\x13participantIdentity\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd5\x05\n" +
	"\x12BridgedCallSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\broom_sid\x18\x02 \x01(\tR\aroomSid\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x03 \x01(\tR\tpatientId\x12\x1f\n" +
	"\vhospital_id\x18\x04 \x01(\tR\n" +
	"hospitalId\x12\x19\n" +
	"\bstaff_id\x18\x05 \x01(\tR\astaffId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x125\n" +
	"\x17requested_by_actor_type\x18\a \x01(\tR\x14requestedByActorType\x121\n" +
	"\x15requested_by_actor_id\x18\b \x01(\tR\x12requestedByActorId\x12'\n" +
	"\x0ftransfer_reason\x18\t \x01(\tR\x0etransferReason\x12=\n" +
	"\frequested_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\x12=\n" +
	"\fconnected_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x125\n" +
	"\bended_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12f\n" +
	"\x13patient_translation\x18\r \x01(\v25.patient.scheduling.BridgedCallTranslationPreferencesR\x12patientTranslation\x12b\n" +
	"\x11staff_translation\x18\x0e \x01(\v25.patient.scheduling.BridgedCallTranslationPreferencesR\x10staffTranslation\"\xe1\x01\n" +
	"!RequestBridgedCallTransferRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\broom_sid\x18\x02 \x01(\tR\aroomSid\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x03 \x01(\tR\tpatientId\x12\x1f\n" +
	"\vhospital_id\x18\x04 \x01(\tR\n" +
	"hospitalId\x12\x19\n" +
	"\bstaff_id\x18\x05 \x01(\tR\astaffId\x12'\n" +
	"\x0ftransfer_reason\x18\x06 \x01(\tR\x0etransferReason\"\xba\x01\n" +
	"\"RequestBridgedCallTransferResponse\x12@\n" +
	"\asession\x18\x01 \x01(\v2&.patient.scheduling.BridgedCallSessionR\asession\x12,\n" +
	"\x12patient_room_token\x18\x02 \x01(\tR\x10patientRoomToken\x12$\n" +
	"\x0elivekit_ws_url\x18\x03 \x01(\tR\flivekitWsUrl\"\x93\x01\n" +
	"\x19ConnectBridgedCallRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bstaff_id\x18\x02 \x01(\tR\astaffId\x12<\n" +
	"\x1astaff_participant_identity\x18\x03 \x01(\tR\x18staffParticipantIdentity\"\xdc\x01\n" +
	"\x1aConnectBridgedCallResponse\x12@\n" +
	"\asession\x18\x01 \x01(\v2&.patient.scheduling.BridgedCallSessionR\asession\x12(\n" +
	"\x10staff_room_token\x18\x02 \x01(\tR\x0estaffRoomToken\x12$\n" +
	"\x0elivekit_ws_url\x18\x03 \x01(\tR\flivekitWsUrl\x12,\n" +
	"\x12patient_room_token\x18\x04 \x01(\tR\x10patientRoomToken\"=\n" +
	"\x1cGetBridgedCallSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xb5\x01\n" +
	"\x1dGetBridgedCallSessionResponse\x12@\n" +
	"\asession\x18\x01 \x01(\v2&.patient.scheduling.BridgedCallSessionR\asession\x12,\n" +
	"\x12patient_room_token\x18\x02 \x01(\tR\x10patientRoomToken\x12$\n" +
	"\x0elivekit_ws_url\x18\x03 \x01(\tR\flivekitWsUrl\"N\n" +
	"\x1eListBridgedCallSessionsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"e\n" +
	"\x1fListBridgedCallSessionsResponse\x12B\n" +
	"\bsessions\x18\x01 \x03(\v2&.patient.scheduling.BridgedCallSessionR\bsessions\"\xbf\x01\n" +
	"#UpdateBridgedCallTranslationRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12 \n" +
	"\vparticipant\x18\x02 \x01(\tR\vparticipant\x12W\n" +
	"\vtranslation\x18\x03 \x01(\v25.patient.scheduling.BridgedCallTranslationPreferencesR\vtranslation\"h\n" +
	"$UpdateBridgedCallTranslationResponse\x12@\n" +
	"\asession\x18\x01 \x01(\v2&.patient.scheduling.BridgedCallSessionR\asession\"N\n" +
	"\x15EndBridgedCallRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"Z\n" +
	"\x16EndBridgedCallResponse\x12@\n" +
	"\asession\x18\x01 \x01(\v2&.patient.scheduling.BridgedCallSessionR\asession2\xad\f\n" +
	"\x11SchedulingService\x12\x8b\x01\n" +
	"\x1aScheduleHealthStaffMeeting\x125.patient.scheduling.ScheduleHealthStaffMeetingRequest\x1a6.patient.scheduling.ScheduleHealthStaffMeetingResponse\x12\x7f\n" +
	"\x16AcceptScheduledMeeting\x121.patient.scheduling.AcceptScheduledMeetingRequest\x1a2.patient.scheduling.AcceptScheduledMeetingResponse\x12\x8b\x01\n" +
	"\x1aRescheduleScheduledMeeting\x125.patient.scheduling.RescheduleScheduledMeetingRequest\x1a6.patient.scheduling.RescheduleScheduledMeetingResponse\x12|\n" +
	"\x15ListScheduledMeetings\x120.patient.scheduling.ListScheduledMeetingsRequest\x1a1.patient.scheduling.ListScheduledMeetingsResponse\x12\x7f\n" +
	"\x16CancelScheduledMeeting\x121.patient.scheduling.CancelScheduledMeetingRequest\x1a2.patient.scheduling.CancelScheduledMeetingResponse\x12y\n" +
	"\x14ListSchedulableStaff\x12/.patient.scheduling.ListSchedulableStaffRequest\x1a0.patient.scheduling.ListSchedulableStaffResponse\x12\x8b\x01\n" +
	"\x1aRequestBridgedCallTransfer\x125.patient.scheduling.RequestBridgedCallTransferRequest\x1a6.patient.scheduling.RequestBridgedCallTransferResponse\x12s\n" +
	"\x12ConnectBridgedCall\x12-.patient.scheduling.ConnectBridgedCallRequest\x1a..patient.scheduling.ConnectBridgedCallResponse\x12|\n" +
	"\x15GetBridgedCallSession\x120.patient.scheduling.GetBridgedCallSessionRequest\x1a1.patient.scheduling.GetBridgedCallSessionResponse\x12\x82\x01\n" +
	"\x17ListBridgedCallSessions\x122.patient.scheduling.ListBridgedCallSessionsRequest\x1a3.patient.scheduling.ListBridgedCallSessionsResponse\x12\x91\x01\n" +
	"\x1cUpdateBridgedCallTranslation\x127.patient.scheduling.UpdateBridgedCallTranslationRequest\x1a8.patient.scheduling.UpdateBridgedCallTranslationResponse\x12g\n" +
	"\x0eEndBridgedCall\x12).patient.scheduling.EndBridgedCallRequest\x1a*.patient.scheduling.EndBridgedCallResponseB,Z*shared/proto/patient/scheduling;schedulingb\x06proto3"

var (
	file_patient_scheduling_proto_rawDescOnce sync.Once
	file_patient_scheduling_proto_rawDescData []byte
)

func file_patient_scheduling_proto_rawDescGZIP() []byte {
	file_patient_scheduling_proto_rawDescOnce.Do(func() {
		file_patient_scheduling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_patient_scheduling_proto_rawDesc), len(file_patient_scheduling_proto_rawDesc)))
	})
	return file_patient_scheduling_proto_rawDescData
}

var file_patient_scheduling_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_patient_scheduling_proto_goTypes = []any{
	(*ScheduleHealthStaffMeetingRequest)(nil),    // 0: patient.scheduling.ScheduleHealthStaffMeetingRequest
	(*ScheduledMeeting)(nil),                     // 1: patient.scheduling.ScheduledMeeting
	(*ScheduleHealthStaffMeetingResponse)(nil),   // 2: patient.scheduling.ScheduleHealthStaffMeetingResponse
	(*AcceptScheduledMeetingRequest)(nil),        // 3: patient.scheduling.AcceptScheduledMeetingRequest
	(*AcceptScheduledMeetingResponse)(nil),       // 4: patient.scheduling.AcceptScheduledMeetingResponse
	(*RescheduleScheduledMeetingRequest)(nil),    // 5: patient.scheduling.RescheduleScheduledMeetingRequest
	(*RescheduleScheduledMeetingResponse)(nil),   // 6: patient.scheduling.RescheduleScheduledMeetingResponse
	(*ListScheduledMeetingsRequest)(nil),         // 7: patient.scheduling.ListScheduledMeetingsRequest
	(*ListScheduledMeetingsResponse)(nil),        // 8: patient.scheduling.ListScheduledMeetingsResponse
	(*CancelScheduledMeetingRequest)(nil),        // 9: patient.scheduling.CancelScheduledMeetingRequest
	(*CancelScheduledMeetingResponse)(nil),       // 10: patient.scheduling.CancelScheduledMeetingResponse
	(*ListSchedulableStaffRequest)(nil),          // 11: patient.scheduling.ListSchedulableStaffRequest
	(*StaffSummary)(nil),                         // 12: patient.scheduling.StaffSummary
	(*ListSchedulableStaffResponse)(nil),         // 13: patient.scheduling.ListSchedulableStaffResponse
	(*BridgedCallTranslationPreferences)(nil),    // 14: patient.scheduling.BridgedCallTranslationPreferences
	(*BridgedCallSession)(nil),                   // 15: patient.scheduling.BridgedCallSession
	(*RequestBridgedCallTransferRequest)(nil),    // 16: patient.scheduling.RequestBridgedCallTransferRequest
	(*RequestBridgedCallTransferResponse)(nil),   // 17: patient.scheduling.RequestBridgedCallTransferResponse
	(*ConnectBridgedCallRequest)(nil),            // 18: patient.scheduling.ConnectBridgedCallRequest
	(*ConnectBridgedCallResponse)(nil),           // 19: patient.scheduling.ConnectBridgedCallResponse
	(*GetBridgedCallSessionRequest)(nil),         // 20: patient.scheduling.GetBridgedCallSessionRequest
	(*GetBridgedCallSessionResponse)(nil),        // 21: patient.scheduling.GetBridgedCallSessionResponse
	(*ListBridgedCallSessionsRequest)(nil),       // 22: patient.scheduling.ListBridgedCallSessionsRequest
	(*ListBridgedCallSessionsResponse)(nil),      // 23: patient.scheduling.ListBridgedCallSessionsResponse
	(*UpdateBridgedCallTranslationRequest)(nil),  // 24: patient.scheduling.UpdateBridgedCallTranslationRequest
	(*UpdateBridgedCallTranslationResponse)(nil), // 25: patient.scheduling.UpdateBridgedCallTranslationResponse
	(*EndBridgedCallRequest)(nil),                // 26: patient.scheduling.EndBridgedCallRequest
	(*EndBridgedCallResponse)(nil),               // 27: patient.scheduling.EndBridgedCallResponse
	(*timestamppb.Timestamp)(nil),                // 28: google.protobuf.Timestamp
}
var file_patient_scheduling_proto_depIdxs = []int32{
	28, // 0: patient.scheduling.ScheduleHealthStaffMeetingRequest.starts_at:type_name -> google.protobuf.Timestamp
	28, // 1: patient.scheduling.ScheduledMeeting.starts_at:type_name -> google.protobuf.Timestamp
	1,  // 2: patient.scheduling.ScheduleHealthStaffMeetingResponse.meeting:type_name -> patient.scheduling.ScheduledMeeting
	1,  // 3: patient.scheduling.AcceptScheduledMeetingResponse.meeting:type_name -> patient.scheduling.ScheduledMeeting
	28, // 4: patient.scheduling.RescheduleScheduledMeetingRequest.starts_at:type_name -> google.protobuf.Timestamp
	1,  // 5: patient.scheduling.RescheduleScheduledMeetingResponse.meeting:type_name -> patient.scheduling.ScheduledMeeting
	1,  // 6: patient.scheduling.ListScheduledMeetingsResponse.meetings:type_name -> patient.scheduling.ScheduledMeeting
	1,  // 7: patient.scheduling.CancelScheduledMeetingResponse.meeting:type_name -> patient.scheduling.ScheduledMeeting
	12, // 8: patient.scheduling.ListSchedulableStaffResponse.staff:type_name -> patient.scheduling.StaffSummary
	28, // 9: patient.scheduling.BridgedCallTranslationPreferences.updated_at:type_name -> google.protobuf.Timestamp
	28, // 10: patient.scheduling.BridgedCallSession.requested_at:type_name -> google.protobuf.Timestamp
	28, // 11: patient.scheduling.BridgedCallSession.connected_at:type_name -> google.protobuf.Timestamp
	28, // 12: patient.scheduling.BridgedCallSession.ended_at:type_name -> google.protobuf.Timestamp
	14, // 13: patient.scheduling.BridgedCallSession.patient_translation:type_name -> patient.scheduling.BridgedCallTranslationPreferences
	14, // 14: patient.scheduling.BridgedCallSession.staff_translation:type_name -> patient.scheduling.BridgedCallTranslationPreferences
	15, // 15: patient.scheduling.RequestBridgedCallTransferResponse.session:type_name -> patient.scheduling.BridgedCallSession
	15, // 16: patient.scheduling.ConnectBridgedCallResponse.session:type_name -> patient.scheduling.BridgedCallSession
	15, // 17: patient.scheduling.GetBridgedCallSessionResponse.session:type_name -> patient.scheduling.BridgedCallSession
	15, // 18: patient.scheduling.ListBridgedCallSessionsResponse.sessions:type_name -> patient.scheduling.BridgedCallSession
	14, // 19: patient.scheduling.UpdateBridgedCallTranslationRequest.translation:type_name -> patient.scheduling.BridgedCallTranslationPreferences
	15, // 20: patient.scheduling.UpdateBridgedCallTranslationResponse.session:type_name -> patient.scheduling.BridgedCallSession
	15, // 21: patient.scheduling.EndBridgedCallResponse.session:type_name -> patient.scheduling.BridgedCallSession
	0,  // 22: patient.scheduling.SchedulingService.ScheduleHealthStaffMeeting:input_type -> patient.scheduling.ScheduleHealthStaffMeetingRequest
	3,  // 23: patient.scheduling.SchedulingService.AcceptScheduledMeeting:input_type -> patient.scheduling.AcceptScheduledMeetingRequest
	5,  // 24: patient.scheduling.SchedulingService.RescheduleScheduledMeeting:input_type -> patient.scheduling.RescheduleScheduledMeetingRequest
	7,  // 25: patient.scheduling.SchedulingService.ListScheduledMeetings:input_type -> patient.scheduling.ListScheduledMeetingsRequest
	9,  // 26: patient.scheduling.SchedulingService.CancelScheduledMeeting:input_type -> patient.scheduling.CancelScheduledMeetingRequest
	11, // 27: patient.scheduling.SchedulingService.ListSchedulableStaff:input_type -> patient.scheduling.ListSchedulableStaffRequest
	16, // 28: patient.scheduling.SchedulingService.RequestBridgedCallTransfer:input_type -> patient.scheduling.RequestBridgedCallTransferRequest
	18, // 29: patient.scheduling.SchedulingService.ConnectBridgedCall:input_type -> patient.scheduling.ConnectBridgedCallRequest
	20, // 30: patient.scheduling.SchedulingService.GetBridgedCallSession:input_type -> patient.scheduling.GetBridgedCallSessionRequest
	22, // 31: patient.scheduling.SchedulingService.ListBridgedCallSessions:input_type -> patient.scheduling.ListBridgedCallSessionsRequest
	24, // 32: patient.scheduling.SchedulingService.UpdateBridgedCallTranslation:input_type -> patient.scheduling.UpdateBridgedCallTranslationRequest
	26, // 33: patient.scheduling.SchedulingService.EndBridgedCall:input_type -> patient.scheduling.EndBridgedCallRequest
	2,  // 34: patient.scheduling.SchedulingService.ScheduleHealthStaffMeeting:output_type -> patient.scheduling.ScheduleHealthStaffMeetingResponse
	4,  // 35: patient.scheduling.SchedulingService.AcceptScheduledMeeting:output_type -> patient.scheduling.AcceptScheduledMeetingResponse
	6,  // 36: patient.scheduling.SchedulingService.RescheduleScheduledMeeting:output_type -> patient.scheduling.RescheduleScheduledMeetingResponse
	8,  // 37: patient.scheduling.SchedulingService.ListScheduledMeetings:output_type -> patient.scheduling.ListScheduledMeetingsResponse
	10, // 38: patient.scheduling.SchedulingService.CancelScheduledMeeting:output_type -> patient.scheduling.CancelScheduledMeetingResponse
	13, // 39: patient.scheduling.SchedulingService.ListSchedulableStaff:output_type -> patient.scheduling.ListSchedulableStaffResponse
	17, // 40: patient.scheduling.SchedulingService.RequestBridgedCallTransfer:output_type -> patient.scheduling.RequestBridgedCallTransferResponse
	19, // 41: patient.scheduling.SchedulingService.ConnectBridgedCall:output_type -> patient.scheduling.ConnectBridgedCallResponse
	21, // 42: patient.scheduling.SchedulingService.GetBridgedCallSession:output_type -> patient.scheduling.GetBridgedCallSessionResponse
	23, // 43: patient.scheduling.SchedulingService.ListBridgedCallSessions:output_type -> patient.scheduling.ListBridgedCallSessionsResponse
	25, // 44: patient.scheduling.SchedulingService.UpdateBridgedCallTranslation:output_type -> patient.scheduling.UpdateBridgedCallTranslationResponse
	27, // 45: patient.scheduling.SchedulingService.EndBridgedCall:output_type -> patient.scheduling.EndBridgedCallResponse
	34, // [34:46] is the sub-list for method output_type
	22, // [22:34] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_patient_scheduling_proto_init() }
func file_patient_scheduling_proto_init() {
	if File_patient_scheduling_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patient_scheduling_proto_rawDesc), len(file_patient_scheduling_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_patient_scheduling_proto_goTypes,
		DependencyIndexes: file_patient_scheduling_proto_depIdxs,
		MessageInfos:      file_patient_scheduling_proto_msgTypes,
	}.Build()
	File_patient_scheduling_proto = out.File
	file_patient_scheduling_proto_goTypes = nil
	file_patient_scheduling_proto_depIdxs = nil
}
