image:
  repository: interpretation-service
  tag: latest
  pullPolicy: IfNotPresent
replicaCount: 1
ports:
  - containerPort: 8095
    name: http
env:
  - name: ENVIRONMENT
    valueFrom:
      configMapKeyRef:
        key: ENVIRONMENT
        name: app-config
  - name: JAEGER_ENDPOINT
    valueFrom:
      configMapKeyRef:
        key: JAEGER_ENDPOINT
        name: app-config
  - name: INTERPRETATION_SERVICE_HTTP_ADDR
    valueFrom:
      configMapKeyRef:
        key: INTERPRETATION_SERVICE_HTTP_ADDR
        name: app-config
  - name: TRANSLATION_SERVICE_GRPC_ADDR
    valueFrom:
      configMapKeyRef:
        key: TRANSLATION_SERVICE_GRPC_ADDR
        name: app-config
  - name: AUDIT_SERVICE_GRPC_ADDR
    valueFrom:
      configMapKeyRef:
        key: AUDIT_SERVICE_GRPC_ADDR
        name: app-config
  - name: REDIS_ADDR
    valueFrom:
      configMapKeyRef:
        key: REDIS_ADDR
        name: app-config
  - name: INTERNAL_SERVICE_SECRET
    valueFrom:
      secretKeyRef:
        key: INTERNAL_SERVICE_SECRET
        name: app-secrets
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        key: REDIS_PASSWORD
        name: app-secrets
resources:
  requests:
    memory: 128Mi
    cpu: 50m
  limits:
    memory: 256Mi
    cpu: 250m
service:
  type: ClusterIP
  ports:
    - port: 8095
      targetPort: 8095
      name: http
