DELETE FROM audit.audit_event_types WHERE event_type IN (
    'VOICE_OTP_WAIT_REGISTERED',
    'VOICE_INBOUND_SMS_PROCESSED',
    'VOICE_OTP_VERIFY_FAILED',
    'CALL_TRANSFER_REQUESTED',
    'CALL_TRANSFER_CONNECTED',
    'CALL_BRIDGED_ENDED',
    'INTERPRETATION_SESSION_STARTED',
    'INTERPRETATION_SESSION_ENDED',
    'INTERPRETATION_PREFERENCES_UPDATED',
    'INTERPRETATION_SEGMENT_PROCESSED'
);
