// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditEvent = `-- name: AppendAuditEvent :one
INSERT INTO audit.audit_events (
  event_id,
  event_type,
  actor_type,
  actor_id,
  patient_id,
  service_name,
  resource_type,
  resource_id,
  event_timestamp,
  request_id,
  correlation_id,
  ip_address,
  tool_name,
  model_name,
  provider_name,
  success_status,
  failure_reason,
  metadata_json
) VALUES (
  $1,
  $2,
  $3,
  $4,
  NULLIF($5, ''),
  $6,
  NULLIF($7, ''),
  NULLIF($8, ''),
  $9,
  NULLIF($10, ''),
  NULLIF($11, ''),
  NULLIF($12, ''),
  NULLIF($13, ''),
  NULLIF($14, ''),
  NULLIF($15, ''),
  $16,
  NULLIF($17, ''),
  $18::jsonb
)
RETURNING id, event_id, event_type, actor_type, actor_id, patient_id, service_name, resource_type, resource_id, event_timestamp, request_id, correlation_id, ip_address, tool_name, model_name, provider_name, success_status, failure_reason, metadata_json, created_at
`

type AppendAuditEventParams struct {
	EventID        pgtype.UUID        `json:"event_id"`
	EventType      string             `json:"event_type"`
	ActorType      string             `json:"actor_type"`
	ActorID        string             `json:"actor_id"`
	PatientID      interface{}        `json:"patient_id"`
	ServiceName    string             `json:"service_name"`
	ResourceType   interface{}        `json:"resource_type"`
	ResourceID     interface{}        `json:"resource_id"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	RequestID      interface{}        `json:"request_id"`
	CorrelationID  interface{}        `json:"correlation_id"`
	IpAddress      interface{}        `json:"ip_address"`
	ToolName       interface{}        `json:"tool_name"`
	ModelName      interface{}        `json:"model_name"`
	ProviderName   interface{}        `json:"provider_name"`
	SuccessStatus  bool               `json:"success_status"`
	FailureReason  interface{}        `json:"failure_reason"`
	MetadataJson   []byte             `json:"metadata_json"`
}

func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (AuditAuditEvent, error) {
	row := q.db.QueryRow(ctx, appendAuditEvent,
		arg.EventID,
		arg.EventType,
		arg.ActorType,
		arg.ActorID,
		arg.PatientID,
		arg.ServiceName,
		arg.ResourceType,
		arg.ResourceID,
		arg.EventTimestamp,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.ToolName,
		arg.ModelName,
		arg.ProviderName,
		arg.SuccessStatus,
		arg.FailureReason,
		arg.MetadataJson,
	)
	var i AuditAuditEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventType,
		&i.ActorType,
		&i.ActorID,
		&i.PatientID,
		&i.ServiceName,
		&i.ResourceType,
		&i.ResourceID,
		&i.EventTimestamp,
		&i.RequestID,
		&i.CorrelationID,
		&i.IpAddress,
		&i.ToolName,
		&i.ModelName,
		&i.ProviderName,
		&i.SuccessStatus,
		&i.FailureReason,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const checkHospitalConsentAccess = `-- name: CheckHospitalConsentAccess :one
SELECT EXISTS (
  SELECT 1
  FROM patient_hospital_consents
  WHERE patient_id = $1::uuid
    AND hospital_id = $2::uuid
    AND revoked_at IS NULL
)
`

type CheckHospitalConsentAccessParams struct {
	PatientID  pgtype.UUID `json:"patient_id"`
	HospitalID pgtype.UUID `json:"hospital_id"`
}

func (q *Queries) CheckHospitalConsentAccess(ctx context.Context, arg CheckHospitalConsentAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkHospitalConsentAccess, arg.PatientID, arg.HospitalID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getLatestMatchingConsent = `-- name: GetLatestMatchingConsent :one
SELECT id, patient_id, consent_type, granted_by, granted_at, revoked_at, scope, expiration_time, source, metadata_json
FROM audit.consents
WHERE patient_id = $1
  AND consent_type = $2
  AND ($3 = '' OR scope = $3 OR scope = '')
ORDER BY granted_at DESC
LIMIT 1
`

type GetLatestMatchingConsentParams struct {
	PatientID   string      `json:"patient_id"`
	ConsentType string      `json:"consent_type"`
	ScopeValue  interface{} `json:"scope_value"`
}

func (q *Queries) GetLatestMatchingConsent(ctx context.Context, arg GetLatestMatchingConsentParams) (AuditConsent, error) {
	row := q.db.QueryRow(ctx, getLatestMatchingConsent, arg.PatientID, arg.ConsentType, arg.ScopeValue)
	var i AuditConsent
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.ConsentType,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.Scope,
		&i.ExpirationTime,
		&i.Source,
		&i.MetadataJson,
	)
	return i, err
}

const grantConsent = `-- name: GrantConsent :one
INSERT INTO audit.consents (
  id,
  patient_id,
  consent_type,
  granted_by,
  granted_at,
  scope,
  expiration_time,
  source,
  metadata_json
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9::jsonb
)
RETURNING id, patient_id, consent_type, granted_by, granted_at, revoked_at, scope, expiration_time, source, metadata_json
`

type GrantConsentParams struct {
	ID             pgtype.UUID        `json:"id"`
	PatientID      string             `json:"patient_id"`
	ConsentType    string             `json:"consent_type"`
	GrantedBy      string             `json:"granted_by"`
	GrantedAt      pgtype.Timestamptz `json:"granted_at"`
	Scope          string             `json:"scope"`
	ExpirationTime pgtype.Timestamptz `json:"expiration_time"`
	Source         string             `json:"source"`
	MetadataJson   []byte             `json:"metadata_json"`
}

func (q *Queries) GrantConsent(ctx context.Context, arg GrantConsentParams) (AuditConsent, error) {
	row := q.db.QueryRow(ctx, grantConsent,
		arg.ID,
		arg.PatientID,
		arg.ConsentType,
		arg.GrantedBy,
		arg.GrantedAt,
		arg.Scope,
		arg.ExpirationTime,
		arg.Source,
		arg.MetadataJson,
	)
	var i AuditConsent
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.ConsentType,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.Scope,
		&i.ExpirationTime,
		&i.Source,
		&i.MetadataJson,
	)
	return i, err
}

const listConsents = `-- name: ListConsents :many
SELECT id, patient_id, consent_type, granted_by, granted_at, revoked_at, scope, expiration_time, source, metadata_json
FROM audit.consents
WHERE ($1 = '' OR patient_id = $1)
  AND ($2 = '' OR consent_type = $2)
  AND ($3::bool OR revoked_at IS NULL)
ORDER BY granted_at DESC
LIMIT $4
`

type ListConsentsParams struct {
	PatientID      interface{} `json:"patient_id"`
	ConsentType    interface{} `json:"consent_type"`
	IncludeRevoked bool        `json:"include_revoked"`
	ResultLimit    int32       `json:"result_limit"`
}

func (q *Queries) ListConsents(ctx context.Context, arg ListConsentsParams) ([]AuditConsent, error) {
	rows, err := q.db.Query(ctx, listConsents,
		arg.PatientID,
		arg.ConsentType,
		arg.IncludeRevoked,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditConsent{}
	for rows.Next() {
		var i AuditConsent
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.ConsentType,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.RevokedAt,
			&i.Scope,
			&i.ExpirationTime,
			&i.Source,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHospitalPortalIncidents = `-- name: ListHospitalPortalIncidents :many
SELECT id, event_id, event_type, actor_type, actor_id, patient_id, service_name, resource_type, resource_id, event_timestamp, request_id, correlation_id, ip_address, tool_name, model_name, provider_name, success_status, failure_reason, metadata_json, created_at
FROM audit.audit_events
WHERE event_type = $1
ORDER BY event_timestamp DESC
LIMIT $2
`

type ListHospitalPortalIncidentsParams struct {
	EventType   string `json:"event_type"`
	ResultLimit int32  `json:"result_limit"`
}

func (q *Queries) ListHospitalPortalIncidents(ctx context.Context, arg ListHospitalPortalIncidentsParams) ([]AuditAuditEvent, error) {
	rows, err := q.db.Query(ctx, listHospitalPortalIncidents, arg.EventType, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditAuditEvent{}
	for rows.Next() {
		var i AuditAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventType,
			&i.ActorType,
			&i.ActorID,
			&i.PatientID,
			&i.ServiceName,
			&i.ResourceType,
			&i.ResourceID,
			&i.EventTimestamp,
			&i.RequestID,
			&i.CorrelationID,
			&i.IpAddress,
			&i.ToolName,
			&i.ModelName,
			&i.ProviderName,
			&i.SuccessStatus,
			&i.FailureReason,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientPortalAuditEvents = `-- name: ListPatientPortalAuditEvents :many
SELECT id, event_id, event_type, actor_type, actor_id, patient_id, service_name, resource_type, resource_id, event_timestamp, request_id, correlation_id, ip_address, tool_name, model_name, provider_name, success_status, failure_reason, metadata_json, created_at
FROM audit.audit_events
WHERE patient_id = $1
ORDER BY event_timestamp DESC
LIMIT $2
`

type ListPatientPortalAuditEventsParams struct {
	PatientID   pgtype.Text `json:"patient_id"`
	ResultLimit int32       `json:"result_limit"`
}

func (q *Queries) ListPatientPortalAuditEvents(ctx context.Context, arg ListPatientPortalAuditEventsParams) ([]AuditAuditEvent, error) {
	rows, err := q.db.Query(ctx, listPatientPortalAuditEvents, arg.PatientID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditAuditEvent{}
	for rows.Next() {
		var i AuditAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventType,
			&i.ActorType,
			&i.ActorID,
			&i.PatientID,
			&i.ServiceName,
			&i.ResourceType,
			&i.ResourceID,
			&i.EventTimestamp,
			&i.RequestID,
			&i.CorrelationID,
			&i.IpAddress,
			&i.ToolName,
			&i.ModelName,
			&i.ProviderName,
			&i.SuccessStatus,
			&i.FailureReason,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientPortalConsents = `-- name: ListPatientPortalConsents :many
SELECT id, patient_id, consent_type, granted_by, granted_at, revoked_at, scope, expiration_time, source, metadata_json
FROM audit.consents
WHERE patient_id = $1
  AND ($2::bool OR revoked_at IS NULL)
ORDER BY granted_at DESC
LIMIT $3
`

type ListPatientPortalConsentsParams struct {
	PatientID      string `json:"patient_id"`
	IncludeRevoked bool   `json:"include_revoked"`
	ResultLimit    int32  `json:"result_limit"`
}

func (q *Queries) ListPatientPortalConsents(ctx context.Context, arg ListPatientPortalConsentsParams) ([]AuditConsent, error) {
	rows, err := q.db.Query(ctx, listPatientPortalConsents, arg.PatientID, arg.IncludeRevoked, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditConsent{}
	for rows.Next() {
		var i AuditConsent
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.ConsentType,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.RevokedAt,
			&i.Scope,
			&i.ExpirationTime,
			&i.Source,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAuditEvents = `-- name: QueryAuditEvents :many
SELECT id, event_id, event_type, actor_type, actor_id, patient_id, service_name, resource_type, resource_id, event_timestamp, request_id, correlation_id, ip_address, tool_name, model_name, provider_name, success_status, failure_reason, metadata_json, created_at
FROM audit.audit_events
WHERE ($1 = '' OR event_type = $1)
  AND ($2 = '' OR actor_type = $2)
  AND ($3 = '' OR actor_id = $3)
  AND ($4 = '' OR patient_id = $4)
  AND ($5 = '' OR service_name = $5)
  AND ($6 = '' OR correlation_id = $6)
ORDER BY event_timestamp DESC
LIMIT $7
`

type QueryAuditEventsParams struct {
	EventType     interface{} `json:"event_type"`
	ActorType     interface{} `json:"actor_type"`
	ActorID       interface{} `json:"actor_id"`
	PatientID     interface{} `json:"patient_id"`
	ServiceName   interface{} `json:"service_name"`
	CorrelationID interface{} `json:"correlation_id"`
	ResultLimit   int32       `json:"result_limit"`
}

func (q *Queries) QueryAuditEvents(ctx context.Context, arg QueryAuditEventsParams) ([]AuditAuditEvent, error) {
	rows, err := q.db.Query(ctx, queryAuditEvents,
		arg.EventType,
		arg.ActorType,
		arg.ActorID,
		arg.PatientID,
		arg.ServiceName,
		arg.CorrelationID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditAuditEvent{}
	for rows.Next() {
		var i AuditAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventType,
			&i.ActorType,
			&i.ActorID,
			&i.PatientID,
			&i.ServiceName,
			&i.ResourceType,
			&i.ResourceID,
			&i.EventTimestamp,
			&i.RequestID,
			&i.CorrelationID,
			&i.IpAddress,
			&i.ToolName,
			&i.ModelName,
			&i.ProviderName,
			&i.SuccessStatus,
			&i.FailureReason,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeConsent = `-- name: RevokeConsent :one
UPDATE audit.consents AS c
SET revoked_at = now(),
    source = CASE WHEN $1 <> '' THEN $1 ELSE c.source END,
    metadata_json = $2::jsonb
WHERE id = (
  SELECT c2.id
  FROM audit.consents AS c2
  WHERE c2.patient_id = $3
    AND c2.consent_type = $4
    AND ($5 = '' OR c2.scope = $5 OR c2.scope = '')
    AND c2.revoked_at IS NULL
  ORDER BY c2.granted_at DESC
  LIMIT 1
)
RETURNING id, patient_id, consent_type, granted_by, granted_at, revoked_at, scope, expiration_time, source, metadata_json
`

type RevokeConsentParams struct {
	Source       interface{} `json:"source"`
	MetadataJson []byte      `json:"metadata_json"`
	PatientID    string      `json:"patient_id"`
	ConsentType  string      `json:"consent_type"`
	ScopeValue   interface{} `json:"scope_value"`
}

func (q *Queries) RevokeConsent(ctx context.Context, arg RevokeConsentParams) (AuditConsent, error) {
	row := q.db.QueryRow(ctx, revokeConsent,
		arg.Source,
		arg.MetadataJson,
		arg.PatientID,
		arg.ConsentType,
		arg.ScopeValue,
	)
	var i AuditConsent
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.ConsentType,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.Scope,
		&i.ExpirationTime,
		&i.Source,
		&i.MetadataJson,
	)
	return i, err
}
