image:
  repository: analytics-service
  tag: latest
  pullPolicy: IfNotPresent
replicaCount: 1
ports:
  - containerPort: 50054
    name: grpc
env:
  - name: ENVIRONMENT
    valueFrom:
      configMapKeyRef:
        key: ENVIRONMENT
        name: app-config
  - name: JAEGER_ENDPOINT
    valueFrom:
      configMapKeyRef:
        key: JAEGER_ENDPOINT
        name: app-config
  - name: ANALYTICS_SERVICE_GRPC_ADDR
    valueFrom:
      configMapKeyRef:
        key: ANALYTICS_SERVICE_GRPC_ADDR
        name: app-config
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        key: DATABASE_URL
        name: app-secrets
  - name: AUTH_SERVICE_JWT_SECRET
    valueFrom:
      secretKeyRef:
        key: AUTH_SERVICE_JWT_SECRET
        name: app-secrets
  - name: PATIENT_SERVICE_JWT_SECRET
    valueFrom:
      secretKeyRef:
        key: PATIENT_SERVICE_JWT_SECRET
        name: app-secrets
  - name: INTERNAL_SERVICE_SECRET
    valueFrom:
      secretKeyRef:
        key: INTERNAL_SERVICE_SECRET
        name: app-secrets
resources:
  requests:
    memory: 128Mi
    cpu: 125m
  limits:
    memory: 256Mi
    cpu: 250m
service:
  type: ClusterIP
  ports:
    - port: 50054
      targetPort: 50054
      name: grpc
