// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation_turns.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createConversationTurn = `-- name: CreateConversationTurn :one

INSERT INTO conversation_turns (
  patient_id,
  session_id,
  role,
  content,
  embedding
) VALUES (
  $1, $2, $3, $4, $5::vector
)
RETURNING id, patient_id, session_id, role, content, embedding, created_at
`

type CreateConversationTurnParams struct {
	PatientID pgtype.UUID     `json:"patient_id"`
	SessionID string          `json:"session_id"`
	Role      string          `json:"role"`
	Content   string          `json:"content"`
	Column5   pgvector.Vector `json:"column_5"`
}

// Conversation memory for agent-worker sessions
func (q *Queries) CreateConversationTurn(ctx context.Context, arg CreateConversationTurnParams) (ConversationTurn, error) {
	row := q.db.QueryRow(ctx, createConversationTurn,
		arg.PatientID,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.Column5,
	)
	var i ConversationTurn
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

const deleteConversationTurnsByPatientID = `-- name: DeleteConversationTurnsByPatientID :exec
DELETE FROM conversation_turns
WHERE patient_id = $1
`

func (q *Queries) DeleteConversationTurnsByPatientID(ctx context.Context, patientID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversationTurnsByPatientID, patientID)
	return err
}

const listRecentConversationTurns = `-- name: ListRecentConversationTurns :many
SELECT id, patient_id, session_id, role, content, embedding, created_at
FROM conversation_turns
WHERE patient_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentConversationTurnsParams struct {
	PatientID pgtype.UUID `json:"patient_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListRecentConversationTurns(ctx context.Context, arg ListRecentConversationTurnsParams) ([]ConversationTurn, error) {
	rows, err := q.db.Query(ctx, listRecentConversationTurns, arg.PatientID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationTurn{}
	for rows.Next() {
		var i ConversationTurn
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentConversationTurnsBySession = `-- name: ListRecentConversationTurnsBySession :many
SELECT id, patient_id, session_id, role, content, embedding, created_at
FROM conversation_turns
WHERE patient_id = $1
  AND session_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListRecentConversationTurnsBySessionParams struct {
	PatientID pgtype.UUID `json:"patient_id"`
	SessionID string      `json:"session_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListRecentConversationTurnsBySession(ctx context.Context, arg ListRecentConversationTurnsBySessionParams) ([]ConversationTurn, error) {
	rows, err := q.db.Query(ctx, listRecentConversationTurnsBySession, arg.PatientID, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationTurn{}
	for rows.Next() {
		var i ConversationTurn
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
