// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuth = `-- name: CreateAuth :one
INSERT INTO auths (user_id)
VALUES ($1)
RETURNING id, user_id, auth_uuid
`

func (q *Queries) CreateAuth(ctx context.Context, userID pgtype.UUID) (Auth, error) {
	row := q.db.QueryRow(ctx, createAuth, userID)
	var i Auth
	err := row.Scan(&i.ID, &i.UserID, &i.AuthUuid)
	return i, err
}

const deleteAuth = `-- name: DeleteAuth :exec
DELETE FROM auths
WHERE id = $1 and user_id = $2
`

type DeleteAuthParams struct {
	ID     int64       `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteAuth(ctx context.Context, arg DeleteAuthParams) error {
	_, err := q.db.Exec(ctx, deleteAuth, arg.ID, arg.UserID)
	return err
}

const deleteAuthByUserIDAndAuthUUID = `-- name: DeleteAuthByUserIDAndAuthUUID :exec
DELETE FROM auths
WHERE user_id = $1 AND auth_uuid = $2
`

type DeleteAuthByUserIDAndAuthUUIDParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	AuthUuid pgtype.UUID `json:"auth_uuid"`
}

func (q *Queries) DeleteAuthByUserIDAndAuthUUID(ctx context.Context, arg DeleteAuthByUserIDAndAuthUUIDParams) error {
	_, err := q.db.Exec(ctx, deleteAuthByUserIDAndAuthUUID, arg.UserID, arg.AuthUuid)
	return err
}

const fetchAuth = `-- name: FetchAuth :one
SELECT id, user_id, auth_uuid FROM auths
WHERE id = $1 and user_id = $2 LIMIT 1
`

type FetchAuthParams struct {
	ID     int64       `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) FetchAuth(ctx context.Context, arg FetchAuthParams) (Auth, error) {
	row := q.db.QueryRow(ctx, fetchAuth, arg.ID, arg.UserID)
	var i Auth
	err := row.Scan(&i.ID, &i.UserID, &i.AuthUuid)
	return i, err
}

const getAuthByUserIDAndAuthUUID = `-- name: GetAuthByUserIDAndAuthUUID :one
SELECT id, user_id, auth_uuid FROM auths
WHERE user_id = $1 AND auth_uuid = $2 LIMIT 1
`

type GetAuthByUserIDAndAuthUUIDParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	AuthUuid pgtype.UUID `json:"auth_uuid"`
}

func (q *Queries) GetAuthByUserIDAndAuthUUID(ctx context.Context, arg GetAuthByUserIDAndAuthUUIDParams) (Auth, error) {
	row := q.db.QueryRow(ctx, getAuthByUserIDAndAuthUUID, arg.UserID, arg.AuthUuid)
	var i Auth
	err := row.Scan(&i.ID, &i.UserID, &i.AuthUuid)
	return i, err
}
