global:
  environment: development
  nodeAffinityUserMode: false

ingress:
  enabled: false
  rules: []

ingress-nginx:
  enabled: true
  controller:
    service:
      type: LoadBalancer
    publishService:
      enabled: true
