// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patient_analytics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPatientCalls = `-- name: CountPatientCalls :one
SELECT COUNT(*)::int
FROM calls
WHERE patient_id = $1::uuid
`

func (q *Queries) CountPatientCalls(ctx context.Context, patientID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPatientCalls, patientID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getPatientCallHistoryRows = `-- name: GetPatientCallHistoryRows :many
SELECT
  ca.started_at AS started_at,
  CASE
    WHEN ca.ended_at IS NULL OR ca.started_at IS NULL OR ca.ended_at < ca.started_at THEN 'unknown'
    WHEN EXTRACT(EPOCH FROM (ca.ended_at - ca.started_at)) < 60
      THEN CONCAT(EXTRACT(EPOCH FROM (ca.ended_at - ca.started_at))::int, ' sec')
    ELSE CONCAT(
      FLOOR(EXTRACT(EPOCH FROM (ca.ended_at - ca.started_at)) / 60)::int,
      ' min ',
      MOD(EXTRACT(EPOCH FROM (ca.ended_at - ca.started_at))::int, 60),
      ' sec'
    )
  END AS duration,
  COALESCE(ca.summary, '') AS summary,
  EXISTS (
    SELECT 1
    FROM mcp_audit_log al
    WHERE al.session_id = ca.livekit_room_id
      AND al.tool = 'trigger_emergency'
      AND al.outcome = 'success'
  ) AS had_emergency
FROM calls ca
WHERE ca.patient_id = $1::uuid
  AND ca.started_at IS NOT NULL
ORDER BY ca.started_at DESC NULLS LAST
LIMIT $2
`

type GetPatientCallHistoryRowsParams struct {
	PatientID   pgtype.UUID `json:"patient_id"`
	ResultLimit int32       `json:"result_limit"`
}

type GetPatientCallHistoryRowsRow struct {
	StartedAt    pgtype.Timestamp `json:"started_at"`
	Duration     interface{}      `json:"duration"`
	Summary      string           `json:"summary"`
	HadEmergency bool             `json:"had_emergency"`
}

func (q *Queries) GetPatientCallHistoryRows(ctx context.Context, arg GetPatientCallHistoryRowsParams) ([]GetPatientCallHistoryRowsRow, error) {
	rows, err := q.db.Query(ctx, getPatientCallHistoryRows, arg.PatientID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPatientCallHistoryRowsRow{}
	for rows.Next() {
		var i GetPatientCallHistoryRowsRow
		if err := rows.Scan(
			&i.StartedAt,
			&i.Duration,
			&i.Summary,
			&i.HadEmergency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
