// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: record_chunks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createRecordChunk = `-- name: CreateRecordChunk :one

INSERT INTO records.record_chunks (
  patient_id,
  record_id,
  fhir_resource_type,
  source_system,
  source_file,
  chunk_index,
  chunk_text,
  chunk_hash,
  access_level,
  embedding_model,
  embedding
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11::vector
)
RETURNING chunk_id, patient_id, record_id, fhir_resource_type, source_system, source_file, chunk_index, chunk_text, chunk_hash, access_level, embedding_model, embedding, created_at, updated_at
`

type CreateRecordChunkParams struct {
	PatientID        pgtype.UUID     `json:"patient_id"`
	RecordID         pgtype.UUID     `json:"record_id"`
	FhirResourceType pgtype.Text     `json:"fhir_resource_type"`
	SourceSystem     pgtype.Text     `json:"source_system"`
	SourceFile       string          `json:"source_file"`
	ChunkIndex       int32           `json:"chunk_index"`
	ChunkText        string          `json:"chunk_text"`
	ChunkHash        string          `json:"chunk_hash"`
	AccessLevel      string          `json:"access_level"`
	EmbeddingModel   string          `json:"embedding_model"`
	Column11         pgvector.Vector `json:"column_11"`
}

// Vector search and ingestion for records.record_chunks
func (q *Queries) CreateRecordChunk(ctx context.Context, arg CreateRecordChunkParams) (RecordsRecordChunk, error) {
	row := q.db.QueryRow(ctx, createRecordChunk,
		arg.PatientID,
		arg.RecordID,
		arg.FhirResourceType,
		arg.SourceSystem,
		arg.SourceFile,
		arg.ChunkIndex,
		arg.ChunkText,
		arg.ChunkHash,
		arg.AccessLevel,
		arg.EmbeddingModel,
		arg.Column11,
	)
	var i RecordsRecordChunk
	err := row.Scan(
		&i.ChunkID,
		&i.PatientID,
		&i.RecordID,
		&i.FhirResourceType,
		&i.SourceSystem,
		&i.SourceFile,
		&i.ChunkIndex,
		&i.ChunkText,
		&i.ChunkHash,
		&i.AccessLevel,
		&i.EmbeddingModel,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecordChunksByPatientID = `-- name: DeleteRecordChunksByPatientID :exec
DELETE FROM records.record_chunks
WHERE patient_id = $1
`

func (q *Queries) DeleteRecordChunksByPatientID(ctx context.Context, patientID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecordChunksByPatientID, patientID)
	return err
}

const fetchChunksForSummary = `-- name: FetchChunksForSummary :many
SELECT
  chunk_text
FROM records.record_chunks
WHERE patient_id = $1
  AND (
    $2 = '' OR
    $2 = 'full' OR
    lower(chunk_text) LIKE '%' || lower($2) || '%'
  )
ORDER BY chunk_index
LIMIT $3
`

type FetchChunksForSummaryParams struct {
	PatientID pgtype.UUID `json:"patient_id"`
	Column2   interface{} `json:"column_2"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) FetchChunksForSummary(ctx context.Context, arg FetchChunksForSummaryParams) ([]string, error) {
	rows, err := q.db.Query(ctx, fetchChunksForSummary, arg.PatientID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var chunk_text string
		if err := rows.Scan(&chunk_text); err != nil {
			return nil, err
		}
		items = append(items, chunk_text)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hospitalSearchRecordChunksByEmbedding = `-- name: HospitalSearchRecordChunksByEmbedding :many
SELECT
  rc.chunk_id,
  rc.chunk_text,
  rc.source_file,
  rc.record_id,
  rc.fhir_resource_type,
  (1 - (rc.embedding <=> $3::vector))::float4 AS score
FROM records.record_chunks rc
WHERE rc.patient_id = $1
  AND rc.access_level IN ('patient', 'provider')
  AND EXISTS (
    SELECT 1
    FROM patient_hospital_consents phc
    WHERE phc.patient_id = $1
      AND phc.hospital_id = $2
      AND phc.revoked_at IS NULL
  )
ORDER BY rc.embedding <=> $3::vector
LIMIT $4
`

type HospitalSearchRecordChunksByEmbeddingParams struct {
	PatientID  pgtype.UUID     `json:"patient_id"`
	HospitalID pgtype.UUID     `json:"hospital_id"`
	Column3    pgvector.Vector `json:"column_3"`
	Limit      int32           `json:"limit"`
}

type HospitalSearchRecordChunksByEmbeddingRow struct {
	ChunkID          pgtype.UUID `json:"chunk_id"`
	ChunkText        string      `json:"chunk_text"`
	SourceFile       string      `json:"source_file"`
	RecordID         pgtype.UUID `json:"record_id"`
	FhirResourceType pgtype.Text `json:"fhir_resource_type"`
	Score            float32     `json:"score"`
}

func (q *Queries) HospitalSearchRecordChunksByEmbedding(ctx context.Context, arg HospitalSearchRecordChunksByEmbeddingParams) ([]HospitalSearchRecordChunksByEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, hospitalSearchRecordChunksByEmbedding,
		arg.PatientID,
		arg.HospitalID,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HospitalSearchRecordChunksByEmbeddingRow{}
	for rows.Next() {
		var i HospitalSearchRecordChunksByEmbeddingRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.ChunkText,
			&i.SourceFile,
			&i.RecordID,
			&i.FhirResourceType,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordChunksByPatientID = `-- name: ListRecordChunksByPatientID :many
SELECT chunk_id, patient_id, record_id, fhir_resource_type, source_system, source_file, chunk_index, chunk_text, chunk_hash, access_level, embedding_model, embedding, created_at, updated_at
FROM records.record_chunks
WHERE patient_id = $1
ORDER BY created_at DESC, chunk_index ASC
LIMIT $2 OFFSET $3
`

type ListRecordChunksByPatientIDParams struct {
	PatientID pgtype.UUID `json:"patient_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListRecordChunksByPatientID(ctx context.Context, arg ListRecordChunksByPatientIDParams) ([]RecordsRecordChunk, error) {
	rows, err := q.db.Query(ctx, listRecordChunksByPatientID, arg.PatientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecordsRecordChunk{}
	for rows.Next() {
		var i RecordsRecordChunk
		if err := rows.Scan(
			&i.ChunkID,
			&i.PatientID,
			&i.RecordID,
			&i.FhirResourceType,
			&i.SourceSystem,
			&i.SourceFile,
			&i.ChunkIndex,
			&i.ChunkText,
			&i.ChunkHash,
			&i.AccessLevel,
			&i.EmbeddingModel,
			&i.Embedding,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRecordChunksByEmbedding = `-- name: SearchRecordChunksByEmbedding :many
SELECT
  chunk_id,
  chunk_text,
  source_file,
  record_id,
  fhir_resource_type,
  (1 - (embedding <=> $2::vector))::float4 AS score
FROM records.record_chunks
WHERE patient_id = $1
  AND ($4 = '' OR fhir_resource_type = $4)
  AND access_level IN ('patient', 'provider')
ORDER BY embedding <=> $2::vector
LIMIT $3
`

type SearchRecordChunksByEmbeddingParams struct {
	PatientID pgtype.UUID     `json:"patient_id"`
	Column2   pgvector.Vector `json:"column_2"`
	Limit     int32           `json:"limit"`
	Column4   interface{}     `json:"column_4"`
}

type SearchRecordChunksByEmbeddingRow struct {
	ChunkID          pgtype.UUID `json:"chunk_id"`
	ChunkText        string      `json:"chunk_text"`
	SourceFile       string      `json:"source_file"`
	RecordID         pgtype.UUID `json:"record_id"`
	FhirResourceType pgtype.Text `json:"fhir_resource_type"`
	Score            float32     `json:"score"`
}

func (q *Queries) SearchRecordChunksByEmbedding(ctx context.Context, arg SearchRecordChunksByEmbeddingParams) ([]SearchRecordChunksByEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, searchRecordChunksByEmbedding,
		arg.PatientID,
		arg.Column2,
		arg.Limit,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchRecordChunksByEmbeddingRow{}
	for rows.Next() {
		var i SearchRecordChunksByEmbeddingRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.ChunkText,
			&i.SourceFile,
			&i.RecordID,
			&i.FhirResourceType,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRecordChunksCandidates = `-- name: SearchRecordChunksCandidates :many
SELECT
  chunk_id,
  chunk_text,
  source_file,
  record_id,
  fhir_resource_type,
  (1 - (embedding <=> $2::vector))::float4 AS score
FROM records.record_chunks
WHERE patient_id = $1
  AND access_level IN ('patient', 'provider')
ORDER BY embedding <=> $2::vector
LIMIT $3
`

type SearchRecordChunksCandidatesParams struct {
	PatientID pgtype.UUID     `json:"patient_id"`
	Column2   pgvector.Vector `json:"column_2"`
	Limit     int32           `json:"limit"`
}

type SearchRecordChunksCandidatesRow struct {
	ChunkID          pgtype.UUID `json:"chunk_id"`
	ChunkText        string      `json:"chunk_text"`
	SourceFile       string      `json:"source_file"`
	RecordID         pgtype.UUID `json:"record_id"`
	FhirResourceType pgtype.Text `json:"fhir_resource_type"`
	Score            float32     `json:"score"`
}

func (q *Queries) SearchRecordChunksCandidates(ctx context.Context, arg SearchRecordChunksCandidatesParams) ([]SearchRecordChunksCandidatesRow, error) {
	rows, err := q.db.Query(ctx, searchRecordChunksCandidates, arg.PatientID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchRecordChunksCandidatesRow{}
	for rows.Next() {
		var i SearchRecordChunksCandidatesRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.ChunkText,
			&i.SourceFile,
			&i.RecordID,
			&i.FhirResourceType,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
