// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: call.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCallsByPatientID = `-- name: CountCallsByPatientID :one
SELECT COUNT(*) FROM calls
WHERE patient_id = $1
`

func (q *Queries) CountCallsByPatientID(ctx context.Context, patientID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCallsByPatientID, patientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCall = `-- name: CreateCall :one
INSERT INTO calls (
  patient_id,
  livekit_room_id,
  status,
  started_at
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, patient_id, livekit_room_id, status, started_at, ended_at, recording_s3_url, summary
`

type CreateCallParams struct {
	PatientID     pgtype.UUID      `json:"patient_id"`
	LivekitRoomID pgtype.Text      `json:"livekit_room_id"`
	Status        pgtype.Text      `json:"status"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
}

func (q *Queries) CreateCall(ctx context.Context, arg CreateCallParams) (Call, error) {
	row := q.db.QueryRow(ctx, createCall,
		arg.PatientID,
		arg.LivekitRoomID,
		arg.Status,
		arg.StartedAt,
	)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.LivekitRoomID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.RecordingS3Url,
		&i.Summary,
	)
	return i, err
}

const deleteCall = `-- name: DeleteCall :exec
DELETE FROM calls
WHERE id = $1
`

func (q *Queries) DeleteCall(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCall, id)
	return err
}

const endCall = `-- name: EndCall :one
UPDATE calls
SET
  status = 'ended',
  ended_at = $2,
  recording_s3_url = COALESCE($3, recording_s3_url),
  summary = COALESCE($4, summary)
WHERE id = $1
RETURNING id, patient_id, livekit_room_id, status, started_at, ended_at, recording_s3_url, summary
`

type EndCallParams struct {
	ID             int64            `json:"id"`
	EndedAt        pgtype.Timestamp `json:"ended_at"`
	RecordingS3Url pgtype.Text      `json:"recording_s3_url"`
	Summary        pgtype.Text      `json:"summary"`
}

func (q *Queries) EndCall(ctx context.Context, arg EndCallParams) (Call, error) {
	row := q.db.QueryRow(ctx, endCall,
		arg.ID,
		arg.EndedAt,
		arg.RecordingS3Url,
		arg.Summary,
	)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.LivekitRoomID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.RecordingS3Url,
		&i.Summary,
	)
	return i, err
}

const getCallByID = `-- name: GetCallByID :one
SELECT id, patient_id, livekit_room_id, status, started_at, ended_at, recording_s3_url, summary FROM calls
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCallByID(ctx context.Context, id int64) (Call, error) {
	row := q.db.QueryRow(ctx, getCallByID, id)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.LivekitRoomID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.RecordingS3Url,
		&i.Summary,
	)
	return i, err
}

const getCallByLivekitRoomID = `-- name: GetCallByLivekitRoomID :one
SELECT id, patient_id, livekit_room_id, status, started_at, ended_at, recording_s3_url, summary FROM calls
WHERE livekit_room_id = $1 LIMIT 1
`

func (q *Queries) GetCallByLivekitRoomID(ctx context.Context, livekitRoomID pgtype.Text) (Call, error) {
	row := q.db.QueryRow(ctx, getCallByLivekitRoomID, livekitRoomID)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.LivekitRoomID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.RecordingS3Url,
		&i.Summary,
	)
	return i, err
}

const getCallWithPatient = `-- name: GetCallWithPatient :one
SELECT 
  c.id, c.patient_id, c.livekit_room_id, c.status, c.started_at, c.ended_at, c.recording_s3_url, c.summary,
  p.phone_number,
  p.full_name as patient_name,
  p.email as patient_email
FROM calls c
INNER JOIN patients p ON c.patient_id = p.id
WHERE c.id = $1
LIMIT 1
`

type GetCallWithPatientRow struct {
	ID             int64            `json:"id"`
	PatientID      pgtype.UUID      `json:"patient_id"`
	LivekitRoomID  pgtype.Text      `json:"livekit_room_id"`
	Status         pgtype.Text      `json:"status"`
	StartedAt      pgtype.Timestamp `json:"started_at"`
	EndedAt        pgtype.Timestamp `json:"ended_at"`
	RecordingS3Url pgtype.Text      `json:"recording_s3_url"`
	Summary        pgtype.Text      `json:"summary"`
	PhoneNumber    string           `json:"phone_number"`
	PatientName    pgtype.Text      `json:"patient_name"`
	PatientEmail   pgtype.Text      `json:"patient_email"`
}

func (q *Queries) GetCallWithPatient(ctx context.Context, id int64) (GetCallWithPatientRow, error) {
	row := q.db.QueryRow(ctx, getCallWithPatient, id)
	var i GetCallWithPatientRow
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.LivekitRoomID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.RecordingS3Url,
		&i.Summary,
		&i.PhoneNumber,
		&i.PatientName,
		&i.PatientEmail,
	)
	return i, err
}

const getCallsInDateRange = `-- name: GetCallsInDateRange :many
SELECT id, patient_id, livekit_room_id, status, started_at, ended_at, recording_s3_url, summary FROM calls
WHERE started_at BETWEEN $1 AND $2
ORDER BY started_at DESC
`

type GetCallsInDateRangeParams struct {
	StartedAt   pgtype.Timestamp `json:"started_at"`
	StartedAt_2 pgtype.Timestamp `json:"started_at_2"`
}

func (q *Queries) GetCallsInDateRange(ctx context.Context, arg GetCallsInDateRangeParams) ([]Call, error) {
	rows, err := q.db.Query(ctx, getCallsInDateRange, arg.StartedAt, arg.StartedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Call{}
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.LivekitRoomID,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.RecordingS3Url,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentCalls = `-- name: GetRecentCalls :many
SELECT id, patient_id, livekit_room_id, status, started_at, ended_at, recording_s3_url, summary FROM calls
ORDER BY started_at DESC
LIMIT $1 OFFSET $2
`

type GetRecentCallsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetRecentCalls(ctx context.Context, arg GetRecentCallsParams) ([]Call, error) {
	rows, err := q.db.Query(ctx, getRecentCalls, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Call{}
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.LivekitRoomID,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.RecordingS3Url,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCallsByPatientID = `-- name: ListCallsByPatientID :many
SELECT id, patient_id, livekit_room_id, status, started_at, ended_at, recording_s3_url, summary FROM calls
WHERE patient_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListCallsByPatientIDParams struct {
	PatientID pgtype.UUID `json:"patient_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListCallsByPatientID(ctx context.Context, arg ListCallsByPatientIDParams) ([]Call, error) {
	rows, err := q.db.Query(ctx, listCallsByPatientID, arg.PatientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Call{}
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.LivekitRoomID,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.RecordingS3Url,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCallsByStatus = `-- name: ListCallsByStatus :many
SELECT id, patient_id, livekit_room_id, status, started_at, ended_at, recording_s3_url, summary FROM calls
WHERE status = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListCallsByStatusParams struct {
	Status pgtype.Text `json:"status"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListCallsByStatus(ctx context.Context, arg ListCallsByStatusParams) ([]Call, error) {
	rows, err := q.db.Query(ctx, listCallsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Call{}
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.LivekitRoomID,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.RecordingS3Url,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCallRecordingURL = `-- name: UpdateCallRecordingURL :one
UPDATE calls
SET recording_s3_url = $2
WHERE id = $1
RETURNING id, patient_id, livekit_room_id, status, started_at, ended_at, recording_s3_url, summary
`

type UpdateCallRecordingURLParams struct {
	ID             int64       `json:"id"`
	RecordingS3Url pgtype.Text `json:"recording_s3_url"`
}

func (q *Queries) UpdateCallRecordingURL(ctx context.Context, arg UpdateCallRecordingURLParams) (Call, error) {
	row := q.db.QueryRow(ctx, updateCallRecordingURL, arg.ID, arg.RecordingS3Url)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.LivekitRoomID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.RecordingS3Url,
		&i.Summary,
	)
	return i, err
}

const updateCallStatus = `-- name: UpdateCallStatus :one
UPDATE calls
SET status = $2
WHERE id = $1
RETURNING id, patient_id, livekit_room_id, status, started_at, ended_at, recording_s3_url, summary
`

type UpdateCallStatusParams struct {
	ID     int64       `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateCallStatus(ctx context.Context, arg UpdateCallStatusParams) (Call, error) {
	row := q.db.QueryRow(ctx, updateCallStatus, arg.ID, arg.Status)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.LivekitRoomID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.RecordingS3Url,
		&i.Summary,
	)
	return i, err
}

const updateCallSummary = `-- name: UpdateCallSummary :one
UPDATE calls
SET summary = $2
WHERE id = $1
RETURNING id, patient_id, livekit_room_id, status, started_at, ended_at, recording_s3_url, summary
`

type UpdateCallSummaryParams struct {
	ID      int64       `json:"id"`
	Summary pgtype.Text `json:"summary"`
}

func (q *Queries) UpdateCallSummary(ctx context.Context, arg UpdateCallSummaryParams) (Call, error) {
	row := q.db.QueryRow(ctx, updateCallSummary, arg.ID, arg.Summary)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.LivekitRoomID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.RecordingS3Url,
		&i.Summary,
	)
	return i, err
}
