// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForBulkCreateActionItems implements pgx.CopyFromSource.
type iteratorForBulkCreateActionItems struct {
	rows                 []BulkCreateActionItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateActionItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateActionItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CallID,
		r.rows[0].TaskDescription,
		r.rows[0].IsCompleted,
		r.rows[0].DueDate,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForBulkCreateActionItems) Err() error {
	return nil
}

func (q *Queries) BulkCreateActionItems(ctx context.Context, arg []BulkCreateActionItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"action_items"}, []string{"call_id", "task_description", "is_completed", "due_date", "created_at"}, &iteratorForBulkCreateActionItems{rows: arg})
}
