// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patient.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPatients = `-- name: CountPatients :one
SELECT COUNT(*) FROM patients
`

func (q *Queries) CountPatients(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPatients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (
  user_id,
  phone_number,
  email,
  full_name,
  date_of_birth,
  medical_notes,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, phone_number, email, full_name, date_of_birth, medical_notes, created_at, updated_at, user_id
`

type CreatePatientParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	PhoneNumber  string             `json:"phone_number"`
	Email        pgtype.Text        `json:"email"`
	FullName     pgtype.Text        `json:"full_name"`
	DateOfBirth  pgtype.Date        `json:"date_of_birth"`
	MedicalNotes pgtype.Text        `json:"medical_notes"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.UserID,
		arg.PhoneNumber,
		arg.Email,
		arg.FullName,
		arg.DateOfBirth,
		arg.MedicalNotes,
		arg.UpdatedAt,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FullName,
		&i.DateOfBirth,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deletePatient = `-- name: DeletePatient :exec
DELETE FROM patients
WHERE id = $1
`

func (q *Queries) DeletePatient(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePatient, id)
	return err
}

const getPatientByEmail = `-- name: GetPatientByEmail :one
SELECT id, phone_number, email, full_name, date_of_birth, medical_notes, created_at, updated_at, user_id FROM patients
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetPatientByEmail(ctx context.Context, email pgtype.Text) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatientByEmail, email)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FullName,
		&i.DateOfBirth,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getPatientByID = `-- name: GetPatientByID :one
SELECT id, phone_number, email, full_name, date_of_birth, medical_notes, created_at, updated_at, user_id FROM patients
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPatientByID(ctx context.Context, id pgtype.UUID) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatientByID, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FullName,
		&i.DateOfBirth,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getPatientByPhoneNumber = `-- name: GetPatientByPhoneNumber :one
SELECT id, phone_number, email, full_name, date_of_birth, medical_notes, created_at, updated_at, user_id FROM patients
WHERE phone_number = $1 LIMIT 1
`

func (q *Queries) GetPatientByPhoneNumber(ctx context.Context, phoneNumber string) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatientByPhoneNumber, phoneNumber)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FullName,
		&i.DateOfBirth,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getPatientByUserID = `-- name: GetPatientByUserID :one
SELECT id, phone_number, email, full_name, date_of_birth, medical_notes, created_at, updated_at, user_id FROM patients
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetPatientByUserID(ctx context.Context, userID pgtype.UUID) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatientByUserID, userID)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FullName,
		&i.DateOfBirth,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getPatientsWithRecentCalls = `-- name: GetPatientsWithRecentCalls :many
SELECT DISTINCT p.id, p.phone_number, p.email, p.full_name, p.date_of_birth, p.medical_notes, p.created_at, p.updated_at, p.user_id
FROM patients p
INNER JOIN calls c ON p.id = c.patient_id
WHERE c.started_at >= $1
ORDER BY p.full_name
`

func (q *Queries) GetPatientsWithRecentCalls(ctx context.Context, startedAt pgtype.Timestamp) ([]Patient, error) {
	rows, err := q.db.Query(ctx, getPatientsWithRecentCalls, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patient{}
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.PhoneNumber,
			&i.Email,
			&i.FullName,
			&i.DateOfBirth,
			&i.MedicalNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatients = `-- name: ListPatients :many
SELECT id, phone_number, email, full_name, date_of_birth, medical_notes, created_at, updated_at, user_id FROM patients
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPatientsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPatients(ctx context.Context, arg ListPatientsParams) ([]Patient, error) {
	rows, err := q.db.Query(ctx, listPatients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patient{}
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.PhoneNumber,
			&i.Email,
			&i.FullName,
			&i.DateOfBirth,
			&i.MedicalNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPatientsByName = `-- name: SearchPatientsByName :many
SELECT id, phone_number, email, full_name, date_of_birth, medical_notes, created_at, updated_at, user_id FROM patients
WHERE full_name ILIKE '%' || $1 || '%'
ORDER BY full_name
LIMIT $2 OFFSET $3
`

type SearchPatientsByNameParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchPatientsByName(ctx context.Context, arg SearchPatientsByNameParams) ([]Patient, error) {
	rows, err := q.db.Query(ctx, searchPatientsByName, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patient{}
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.PhoneNumber,
			&i.Email,
			&i.FullName,
			&i.DateOfBirth,
			&i.MedicalNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatient = `-- name: UpdatePatient :one
UPDATE patients
SET
  email = COALESCE($3, email),
  full_name = COALESCE($4, full_name),
  date_of_birth = COALESCE($5, date_of_birth),
  medical_notes = COALESCE($6, medical_notes),
  updated_at = $2
WHERE id = $1
RETURNING id, phone_number, email, full_name, date_of_birth, medical_notes, created_at, updated_at, user_id
`

type UpdatePatientParams struct {
	ID           pgtype.UUID        `json:"id"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Email        pgtype.Text        `json:"email"`
	FullName     pgtype.Text        `json:"full_name"`
	DateOfBirth  pgtype.Date        `json:"date_of_birth"`
	MedicalNotes pgtype.Text        `json:"medical_notes"`
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, updatePatient,
		arg.ID,
		arg.UpdatedAt,
		arg.Email,
		arg.FullName,
		arg.DateOfBirth,
		arg.MedicalNotes,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FullName,
		&i.DateOfBirth,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const updatePatientMedicalNotes = `-- name: UpdatePatientMedicalNotes :one
UPDATE patients
SET
  medical_notes = $2,
  updated_at = $3
WHERE id = $1
RETURNING id, phone_number, email, full_name, date_of_birth, medical_notes, created_at, updated_at, user_id
`

type UpdatePatientMedicalNotesParams struct {
	ID           pgtype.UUID        `json:"id"`
	MedicalNotes pgtype.Text        `json:"medical_notes"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePatientMedicalNotes(ctx context.Context, arg UpdatePatientMedicalNotesParams) (Patient, error) {
	row := q.db.QueryRow(ctx, updatePatientMedicalNotes, arg.ID, arg.MedicalNotes, arg.UpdatedAt)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Email,
		&i.FullName,
		&i.DateOfBirth,
		&i.MedicalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
