global:
  environment: production

ingress:
  enabled: true
  rules:
    - host: api.zorbahealth.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: api-gateway
          servicePort: 8081
    - host: zorbahealth.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: web
          servicePort: 3000
    - host: mobile.zorbahealth.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: mobile
          servicePort: 8084

infra:
  postgres:
    resources:
      requests:
        memory: 1Gi
        cpu: 1000m
      limits:
        memory: 2Gi
        cpu: 2000m
  redis:
    resources:
      requests:
        memory: 256Mi
        cpu: 200m
      limits:
        memory: 512Mi
        cpu: 500m
  rabbitmq:
    resources:
      requests:
        memory: 2Gi
        cpu: 1000m
      limits:
        memory: 4Gi
        cpu: 2000m

patient-service:
  replicas: 3
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

auth-service:
  replicas: 3
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m

api-gateway:
  replicas: 3
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

notification-service:
  replicas: 3
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

health-records-service:
  replicas: 3
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

analytics-service:
  replicas: 3
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1000m

audit-service:
  replicas: 3
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

location-service:
  replicas: 3
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

mcp-server:
  replicas: 3
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 512Mi
      cpu: 500m

voice-agent-service:
  replicaCount: 2
  resources:
    requests:
      memory: 4Gi
      cpu: 4000m
    limits:
      memory: 8Gi
      cpu: 8000m

web:
  replicas: 3
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 512Mi
      cpu: 500m

mobile:
  replicas: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 1000m
