apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-worker-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent-worker-service
  template:
    metadata:
      labels:
        app: agent-worker-service
    spec:
      containers:
        - name: agent-worker-service
          image: europe-west1-docker.pkg.dev/{{PROJECT_ID}}/zorba-health/agent-worker-service
          ports:
            - containerPort: 50051
              name: grpc
          env:
            - name: GRPC_ADDR
              valueFrom:
                configMapKeyRef:
                  key: AGENT_WORKER_GRPC_ADDR
                  name: app-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: agent-worker-service
spec:
  type: ClusterIP
  ports:
    - port: 50051
      targetPort: 50051
      name: grpc
  selector:
    app: agent-worker-service
