// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: audit/audit.proto

package audit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ActorType     string                 `protobuf:"bytes,3,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorId       string                 `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	PatientId     string                 `protobuf:"bytes,5,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,6,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ResourceType  string                 `protobuf:"bytes,7,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,8,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RequestId     string                 `protobuf:"bytes,10,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,11,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,12,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	ToolName      string                 `protobuf:"bytes,13,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ModelName     string                 `protobuf:"bytes,14,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ProviderName  string                 `protobuf:"bytes,15,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	SuccessStatus bool                   `protobuf:"varint,16,opt,name=success_status,json=successStatus,proto3" json:"success_status,omitempty"`
	FailureReason string                 `protobuf:"bytes,17,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,18,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_audit_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AuditEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AuditEvent) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *AuditEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AuditEvent) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *AuditEvent) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *AuditEvent) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *AuditEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *AuditEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AuditEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuditEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AuditEvent) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AuditEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *AuditEvent) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *AuditEvent) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *AuditEvent) GetSuccessStatus() bool {
	if x != nil {
		return x.SuccessStatus
	}
	return false
}

func (x *AuditEvent) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *AuditEvent) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AppendAuditEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *AuditEvent            `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendAuditEventRequest) Reset() {
	*x = AppendAuditEventRequest{}
	mi := &file_audit_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendAuditEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendAuditEventRequest) ProtoMessage() {}

func (x *AppendAuditEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendAuditEventRequest.ProtoReflect.Descriptor instead.
func (*AppendAuditEventRequest) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{1}
}

func (x *AppendAuditEventRequest) GetEvent() *AuditEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type AppendAuditEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *AuditEvent            `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendAuditEventResponse) Reset() {
	*x = AppendAuditEventResponse{}
	mi := &file_audit_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendAuditEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendAuditEventResponse) ProtoMessage() {}

func (x *AppendAuditEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendAuditEventResponse.ProtoReflect.Descriptor instead.
func (*AppendAuditEventResponse) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{2}
}

func (x *AppendAuditEventResponse) GetEvent() *AuditEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type QueryAuditEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ActorType     string                 `protobuf:"bytes,2,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorId       string                 `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	PatientId     string                 `protobuf:"bytes,4,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	CorrelationId string                 `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Limit         int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAuditEventsRequest) Reset() {
	*x = QueryAuditEventsRequest{}
	mi := &file_audit_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAuditEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAuditEventsRequest) ProtoMessage() {}

func (x *QueryAuditEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAuditEventsRequest.ProtoReflect.Descriptor instead.
func (*QueryAuditEventsRequest) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{3}
}

func (x *QueryAuditEventsRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *QueryAuditEventsRequest) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *QueryAuditEventsRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *QueryAuditEventsRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *QueryAuditEventsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *QueryAuditEventsRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *QueryAuditEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QueryAuditEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AuditEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAuditEventsResponse) Reset() {
	*x = QueryAuditEventsResponse{}
	mi := &file_audit_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAuditEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAuditEventsResponse) ProtoMessage() {}

func (x *QueryAuditEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAuditEventsResponse.ProtoReflect.Descriptor instead.
func (*QueryAuditEventsResponse) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{4}
}

func (x *QueryAuditEventsResponse) GetEvents() []*AuditEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type Consent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConsentId      string                 `protobuf:"bytes,1,opt,name=consent_id,json=consentId,proto3" json:"consent_id,omitempty"`
	PatientId      string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	ConsentType    string                 `protobuf:"bytes,3,opt,name=consent_type,json=consentType,proto3" json:"consent_type,omitempty"`
	GrantedBy      string                 `protobuf:"bytes,4,opt,name=granted_by,json=grantedBy,proto3" json:"granted_by,omitempty"`
	GrantedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=granted_at,json=grantedAt,proto3" json:"granted_at,omitempty"`
	RevokedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	Scope          string                 `protobuf:"bytes,7,opt,name=scope,proto3" json:"scope,omitempty"`
	ExpirationTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expiration_time,json=expirationTime,proto3" json:"expiration_time,omitempty"`
	Source         string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	Metadata       *structpb.Struct       `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Consent) Reset() {
	*x = Consent{}
	mi := &file_audit_audit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consent) ProtoMessage() {}

func (x *Consent) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consent.ProtoReflect.Descriptor instead.
func (*Consent) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{5}
}

func (x *Consent) GetConsentId() string {
	if x != nil {
		return x.ConsentId
	}
	return ""
}

func (x *Consent) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *Consent) GetConsentType() string {
	if x != nil {
		return x.ConsentType
	}
	return ""
}

func (x *Consent) GetGrantedBy() string {
	if x != nil {
		return x.GrantedBy
	}
	return ""
}

func (x *Consent) GetGrantedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GrantedAt
	}
	return nil
}

func (x *Consent) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *Consent) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Consent) GetExpirationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationTime
	}
	return nil
}

func (x *Consent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Consent) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CheckConsentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	ConsentType   string                 `protobuf:"bytes,2,opt,name=consent_type,json=consentType,proto3" json:"consent_type,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConsentRequest) Reset() {
	*x = CheckConsentRequest{}
	mi := &file_audit_audit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConsentRequest) ProtoMessage() {}

func (x *CheckConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConsentRequest.ProtoReflect.Descriptor instead.
func (*CheckConsentRequest) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{6}
}

func (x *CheckConsentRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *CheckConsentRequest) GetConsentType() string {
	if x != nil {
		return x.ConsentType
	}
	return ""
}

func (x *CheckConsentRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type CheckConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	DenialReason  string                 `protobuf:"bytes,2,opt,name=denial_reason,json=denialReason,proto3" json:"denial_reason,omitempty"`
	Consent       *Consent               `protobuf:"bytes,3,opt,name=consent,proto3" json:"consent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConsentResponse) Reset() {
	*x = CheckConsentResponse{}
	mi := &file_audit_audit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConsentResponse) ProtoMessage() {}

func (x *CheckConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConsentResponse.ProtoReflect.Descriptor instead.
func (*CheckConsentResponse) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{7}
}

func (x *CheckConsentResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckConsentResponse) GetDenialReason() string {
	if x != nil {
		return x.DenialReason
	}
	return ""
}

func (x *CheckConsentResponse) GetConsent() *Consent {
	if x != nil {
		return x.Consent
	}
	return nil
}

type GrantConsentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PatientId      string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	ConsentType    string                 `protobuf:"bytes,2,opt,name=consent_type,json=consentType,proto3" json:"consent_type,omitempty"`
	GrantedBy      string                 `protobuf:"bytes,3,opt,name=granted_by,json=grantedBy,proto3" json:"granted_by,omitempty"`
	Scope          string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	ExpirationTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expiration_time,json=expirationTime,proto3" json:"expiration_time,omitempty"`
	Source         string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Metadata       *structpb.Struct       `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GrantConsentRequest) Reset() {
	*x = GrantConsentRequest{}
	mi := &file_audit_audit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantConsentRequest) ProtoMessage() {}

func (x *GrantConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantConsentRequest.ProtoReflect.Descriptor instead.
func (*GrantConsentRequest) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{8}
}

func (x *GrantConsentRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *GrantConsentRequest) GetConsentType() string {
	if x != nil {
		return x.ConsentType
	}
	return ""
}

func (x *GrantConsentRequest) GetGrantedBy() string {
	if x != nil {
		return x.GrantedBy
	}
	return ""
}

func (x *GrantConsentRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GrantConsentRequest) GetExpirationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationTime
	}
	return nil
}

func (x *GrantConsentRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GrantConsentRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GrantConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consent       *Consent               `protobuf:"bytes,1,opt,name=consent,proto3" json:"consent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantConsentResponse) Reset() {
	*x = GrantConsentResponse{}
	mi := &file_audit_audit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantConsentResponse) ProtoMessage() {}

func (x *GrantConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantConsentResponse.ProtoReflect.Descriptor instead.
func (*GrantConsentResponse) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{9}
}

func (x *GrantConsentResponse) GetConsent() *Consent {
	if x != nil {
		return x.Consent
	}
	return nil
}

type RevokeConsentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	ConsentType   string                 `protobuf:"bytes,2,opt,name=consent_type,json=consentType,proto3" json:"consent_type,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	RevokedBy     string                 `protobuf:"bytes,4,opt,name=revoked_by,json=revokedBy,proto3" json:"revoked_by,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeConsentRequest) Reset() {
	*x = RevokeConsentRequest{}
	mi := &file_audit_audit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeConsentRequest) ProtoMessage() {}

func (x *RevokeConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeConsentRequest.ProtoReflect.Descriptor instead.
func (*RevokeConsentRequest) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeConsentRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *RevokeConsentRequest) GetConsentType() string {
	if x != nil {
		return x.ConsentType
	}
	return ""
}

func (x *RevokeConsentRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *RevokeConsentRequest) GetRevokedBy() string {
	if x != nil {
		return x.RevokedBy
	}
	return ""
}

func (x *RevokeConsentRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RevokeConsentRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RevokeConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consent       *Consent               `protobuf:"bytes,1,opt,name=consent,proto3" json:"consent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeConsentResponse) Reset() {
	*x = RevokeConsentResponse{}
	mi := &file_audit_audit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeConsentResponse) ProtoMessage() {}

func (x *RevokeConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeConsentResponse.ProtoReflect.Descriptor instead.
func (*RevokeConsentResponse) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeConsentResponse) GetConsent() *Consent {
	if x != nil {
		return x.Consent
	}
	return nil
}

type ListConsentsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PatientId      string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	ConsentType    string                 `protobuf:"bytes,2,opt,name=consent_type,json=consentType,proto3" json:"consent_type,omitempty"`
	IncludeRevoked bool                   `protobuf:"varint,3,opt,name=include_revoked,json=includeRevoked,proto3" json:"include_revoked,omitempty"`
	Limit          int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListConsentsRequest) Reset() {
	*x = ListConsentsRequest{}
	mi := &file_audit_audit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsentsRequest) ProtoMessage() {}

func (x *ListConsentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsentsRequest.ProtoReflect.Descriptor instead.
func (*ListConsentsRequest) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{12}
}

func (x *ListConsentsRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ListConsentsRequest) GetConsentType() string {
	if x != nil {
		return x.ConsentType
	}
	return ""
}

func (x *ListConsentsRequest) GetIncludeRevoked() bool {
	if x != nil {
		return x.IncludeRevoked
	}
	return false
}

func (x *ListConsentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListConsentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consents      []*Consent             `protobuf:"bytes,1,rep,name=consents,proto3" json:"consents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsentsResponse) Reset() {
	*x = ListConsentsResponse{}
	mi := &file_audit_audit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsentsResponse) ProtoMessage() {}

func (x *ListConsentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_audit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsentsResponse.ProtoReflect.Descriptor instead.
func (*ListConsentsResponse) Descriptor() ([]byte, []int) {
	return file_audit_audit_proto_rawDescGZIP(), []int{13}
}

func (x *ListConsentsResponse) GetConsents() []*Consent {
	if x != nil {
		return x.Consents
	}
	return nil
}

var File_audit_audit_proto protoreflect.FileDescriptor

const file_audit_audit_proto_rawDesc = "" +
	"\n" +
	"\x11audit/audit.proto\x12\x05audit\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x05\n" +
	"\n" +
	"AuditEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x03 \x01(\tR\tactorType\x12\x19\n" +
	"\bactor_id\x18\x04 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x05 \x01(\tR\tpatientId\x12!\n" +
	"\fservice_name\x18\x06 \x01(\tR\vserviceName\x12#\n" +
	"\rresource_type\x18\a \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\b \x01(\tR\n" +
	"resourceId\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"request_id\x18\n" +
	" \x01(\tR\trequestId\x12%\n" +
	"\x0ecorrelation_id\x18\v \x01(\tR\rcorrelationId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\f \x01(\tR\tipAddress\x12\x1b\n" +
	"\ttool_name\x18\r \x01(\tR\btoolName\x12\x1d\n" +
	"\n" +
	"model_name\x18\x0e \x01(\tR\tmodelName\x12#\n" +
	"\rprovider_name\x18\x0f \x01(\tR\fproviderName\x12%\n" +
	"\x0esuccess_status\x18\x10 \x01(\bR\rsuccessStatus\x12%\n" +
	"\x0efailure_reason\x18\x11 \x01(\tR\rfailureReason\x123\n" +
	"\bmetadata\x18\x12 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"B\n" +
	"\x17AppendAuditEventRequest\x12'\n" +
	"\x05event\x18\x01 \x01(\v2\x11.audit.AuditEventR\x05event\"C\n" +
	"\x18AppendAuditEventResponse\x12'\n" +
	"\x05event\x18\x01 \x01(\v2\x11.audit.AuditEventR\x05event\"\xf1\x01\n" +
	"\x17QueryAuditEventsRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x02 \x01(\tR\tactorType\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x04 \x01(\tR\tpatientId\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\"E\n" +
	"\x18QueryAuditEventsResponse\x12)\n" +
	"\x06events\x18\x01 \x03(\v2\x11.audit.AuditEventR\x06events\"\xa7\x03\n" +
	"\aConsent\x12\x1d\n" +
	"\n" +
	"consent_id\x18\x01 \x01(\tR\tconsentId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12!\n" +
	"\fconsent_type\x18\x03 \x01(\tR\vconsentType\x12\x1d\n" +
	"\n" +
	"granted_by\x18\x04 \x01(\tR\tgrantedBy\x129\n" +
	"\n" +
	"granted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tgrantedAt\x129\n" +
	"\n" +
	"revoked_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x12\x14\n" +
	"\x05scope\x18\a \x01(\tR\x05scope\x12C\n" +
	"\x0fexpiration_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0eexpirationTime\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\x123\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\bmetadata\"m\n" +
	"\x13CheckConsentRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12!\n" +
	"\fconsent_type\x18\x02 \x01(\tR\vconsentType\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\"\x7f\n" +
	"\x14CheckConsentResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12#\n" +
	"\rdenial_reason\x18\x02 \x01(\tR\fdenialReason\x12(\n" +
	"\aconsent\x18\x03 \x01(\v2\x0e.audit.ConsentR\aconsent\"\x9e\x02\n" +
	"\x13GrantConsentRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12!\n" +
	"\fconsent_type\x18\x02 \x01(\tR\vconsentType\x12\x1d\n" +
	"\n" +
	"granted_by\x18\x03 \x01(\tR\tgrantedBy\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12C\n" +
	"\x0fexpiration_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0eexpirationTime\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x17.google.protobuf.StructR\bmetadata\"@\n" +
	"\x14GrantConsentResponse\x12(\n" +
	"\aconsent\x18\x01 \x01(\v2\x0e.audit.ConsentR\aconsent\"\xda\x01\n" +
	"\x14RevokeConsentRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12!\n" +
	"\fconsent_type\x18\x02 \x01(\tR\vconsentType\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x1d\n" +
	"\n" +
	"revoked_by\x18\x04 \x01(\tR\trevokedBy\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"A\n" +
	"\x15RevokeConsentResponse\x12(\n" +
	"\aconsent\x18\x01 \x01(\v2\x0e.audit.ConsentR\aconsent\"\x96\x01\n" +
	"\x13ListConsentsRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12!\n" +
	"\fconsent_type\x18\x02 \x01(\tR\vconsentType\x12'\n" +
	"\x0finclude_revoked\x18\x03 \x01(\bR\x0eincludeRevoked\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"B\n" +
	"\x14ListConsentsResponse\x12*\n" +
	"\bconsents\x18\x01 \x03(\v2\x0e.audit.ConsentR\bconsents2\xdf\x03\n" +
	"\fAuditService\x12S\n" +
	"\x10AppendAuditEvent\x12\x1e.audit.AppendAuditEventRequest\x1a\x1f.audit.AppendAuditEventResponse\x12S\n" +
	"\x10QueryAuditEvents\x12\x1e.audit.QueryAuditEventsRequest\x1a\x1f.audit.QueryAuditEventsResponse\x12G\n" +
	"\fCheckConsent\x12\x1a.audit.CheckConsentRequest\x1a\x1b.audit.CheckConsentResponse\x12G\n" +
	"\fGrantConsent\x12\x1a.audit.GrantConsentRequest\x1a\x1b.audit.GrantConsentResponse\x12J\n" +
	"\rRevokeConsent\x12\x1b.audit.RevokeConsentRequest\x1a\x1c.audit.RevokeConsentResponse\x12G\n" +
	"\fListConsents\x12\x1a.audit.ListConsentsRequest\x1a\x1b.audit.ListConsentsResponseB\x1aZ\x18shared/proto/audit;auditb\x06proto3"

var (
	file_audit_audit_proto_rawDescOnce sync.Once
	file_audit_audit_proto_rawDescData []byte
)

func file_audit_audit_proto_rawDescGZIP() []byte {
	file_audit_audit_proto_rawDescOnce.Do(func() {
		file_audit_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_audit_proto_rawDesc), len(file_audit_audit_proto_rawDesc)))
	})
	return file_audit_audit_proto_rawDescData
}

var file_audit_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_audit_audit_proto_goTypes = []any{
	(*AuditEvent)(nil),               // 0: audit.AuditEvent
	(*AppendAuditEventRequest)(nil),  // 1: audit.AppendAuditEventRequest
	(*AppendAuditEventResponse)(nil), // 2: audit.AppendAuditEventResponse
	(*QueryAuditEventsRequest)(nil),  // 3: audit.QueryAuditEventsRequest
	(*QueryAuditEventsResponse)(nil), // 4: audit.QueryAuditEventsResponse
	(*Consent)(nil),                  // 5: audit.Consent
	(*CheckConsentRequest)(nil),      // 6: audit.CheckConsentRequest
	(*CheckConsentResponse)(nil),     // 7: audit.CheckConsentResponse
	(*GrantConsentRequest)(nil),      // 8: audit.GrantConsentRequest
	(*GrantConsentResponse)(nil),     // 9: audit.GrantConsentResponse
	(*RevokeConsentRequest)(nil),     // 10: audit.RevokeConsentRequest
	(*RevokeConsentResponse)(nil),    // 11: audit.RevokeConsentResponse
	(*ListConsentsRequest)(nil),      // 12: audit.ListConsentsRequest
	(*ListConsentsResponse)(nil),     // 13: audit.ListConsentsResponse
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
	(*structpb.Struct)(nil),          // 15: google.protobuf.Struct
}
var file_audit_audit_proto_depIdxs = []int32{
	14, // 0: audit.AuditEvent.timestamp:type_name -> google.protobuf.Timestamp
	15, // 1: audit.AuditEvent.metadata:type_name -> google.protobuf.Struct
	0,  // 2: audit.AppendAuditEventRequest.event:type_name -> audit.AuditEvent
	0,  // 3: audit.AppendAuditEventResponse.event:type_name -> audit.AuditEvent
	0,  // 4: audit.QueryAuditEventsResponse.events:type_name -> audit.AuditEvent
	14, // 5: audit.Consent.granted_at:type_name -> google.protobuf.Timestamp
	14, // 6: audit.Consent.revoked_at:type_name -> google.protobuf.Timestamp
	14, // 7: audit.Consent.expiration_time:type_name -> google.protobuf.Timestamp
	15, // 8: audit.Consent.metadata:type_name -> google.protobuf.Struct
	5,  // 9: audit.CheckConsentResponse.consent:type_name -> audit.Consent
	14, // 10: audit.GrantConsentRequest.expiration_time:type_name -> google.protobuf.Timestamp
	15, // 11: audit.GrantConsentRequest.metadata:type_name -> google.protobuf.Struct
	5,  // 12: audit.GrantConsentResponse.consent:type_name -> audit.Consent
	15, // 13: audit.RevokeConsentRequest.metadata:type_name -> google.protobuf.Struct
	5,  // 14: audit.RevokeConsentResponse.consent:type_name -> audit.Consent
	5,  // 15: audit.ListConsentsResponse.consents:type_name -> audit.Consent
	1,  // 16: audit.AuditService.AppendAuditEvent:input_type -> audit.AppendAuditEventRequest
	3,  // 17: audit.AuditService.QueryAuditEvents:input_type -> audit.QueryAuditEventsRequest
	6,  // 18: audit.AuditService.CheckConsent:input_type -> audit.CheckConsentRequest
	8,  // 19: audit.AuditService.GrantConsent:input_type -> audit.GrantConsentRequest
	10, // 20: audit.AuditService.RevokeConsent:input_type -> audit.RevokeConsentRequest
	12, // 21: audit.AuditService.ListConsents:input_type -> audit.ListConsentsRequest
	2,  // 22: audit.AuditService.AppendAuditEvent:output_type -> audit.AppendAuditEventResponse
	4,  // 23: audit.AuditService.QueryAuditEvents:output_type -> audit.QueryAuditEventsResponse
	7,  // 24: audit.AuditService.CheckConsent:output_type -> audit.CheckConsentResponse
	9,  // 25: audit.AuditService.GrantConsent:output_type -> audit.GrantConsentResponse
	11, // 26: audit.AuditService.RevokeConsent:output_type -> audit.RevokeConsentResponse
	13, // 27: audit.AuditService.ListConsents:output_type -> audit.ListConsentsResponse
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_audit_audit_proto_init() }
func file_audit_audit_proto_init() {
	if File_audit_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_audit_proto_rawDesc), len(file_audit_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audit_audit_proto_goTypes,
		DependencyIndexes: file_audit_audit_proto_depIdxs,
		MessageInfos:      file_audit_audit_proto_msgTypes,
	}.Build()
	File_audit_audit_proto = out.File
	file_audit_audit_proto_goTypes = nil
	file_audit_audit_proto_depIdxs = nil
}
