// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hospital_analytics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHospitalCallVolume = `-- name: GetHospitalCallVolume :many
WITH consented_patients AS (
  SELECT c.patient_id
  FROM patient_hospital_consents c
  WHERE c.hospital_id = $4::uuid
    AND c.revoked_at IS NULL
),
hospital_calls AS (
  SELECT
    ca.started_at,
    CASE
      WHEN ca.ended_at IS NOT NULL AND ca.started_at IS NOT NULL AND ca.ended_at >= ca.started_at
        THEN EXTRACT(EPOCH FROM (ca.ended_at - ca.started_at))::double precision
      ELSE NULL::double precision
    END AS duration_seconds,
    (ca.status = 'ended') AS completed,
    EXISTS (
      SELECT 1
      FROM mcp_audit_log al
      WHERE al.session_id = ca.livekit_room_id
        AND al.tool = 'trigger_emergency'
        AND al.outcome = 'success'
    ) AS had_emergency
  FROM calls ca
  INNER JOIN consented_patients cp ON cp.patient_id = ca.patient_id
  WHERE ca.started_at IS NOT NULL
)
SELECT
  CASE
    WHEN $1::text = 'week' THEN date_trunc('week', hc.started_at)
    WHEN $1::text = 'month' THEN date_trunc('month', hc.started_at)
    ELSE date_trunc('day', hc.started_at)
  END AS date,
  COUNT(*)::int AS total_calls,
  COUNT(*) FILTER (WHERE hc.completed)::int AS completed_calls,
  COUNT(*) FILTER (WHERE hc.had_emergency)::int AS emergency_calls,
  COALESCE(AVG(hc.duration_seconds), 0)::double precision AS avg_duration_sec
FROM hospital_calls hc
WHERE hc.started_at >= $2::timestamp
  AND hc.started_at < $3::timestamp + INTERVAL '1 day'
  AND $1::text IN ('day', 'week', 'month')
GROUP BY 1
ORDER BY 1 ASC
`

type GetHospitalCallVolumeParams struct {
	Granularity string           `json:"granularity"`
	FromDate    pgtype.Timestamp `json:"from_date"`
	ToDate      pgtype.Timestamp `json:"to_date"`
	HospitalID  pgtype.UUID      `json:"hospital_id"`
}

type GetHospitalCallVolumeRow struct {
	Date           interface{} `json:"date"`
	TotalCalls     int32       `json:"total_calls"`
	CompletedCalls int32       `json:"completed_calls"`
	EmergencyCalls int32       `json:"emergency_calls"`
	AvgDurationSec float64     `json:"avg_duration_sec"`
}

func (q *Queries) GetHospitalCallVolume(ctx context.Context, arg GetHospitalCallVolumeParams) ([]GetHospitalCallVolumeRow, error) {
	rows, err := q.db.Query(ctx, getHospitalCallVolume,
		arg.Granularity,
		arg.FromDate,
		arg.ToDate,
		arg.HospitalID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHospitalCallVolumeRow{}
	for rows.Next() {
		var i GetHospitalCallVolumeRow
		if err := rows.Scan(
			&i.Date,
			&i.TotalCalls,
			&i.CompletedCalls,
			&i.EmergencyCalls,
			&i.AvgDurationSec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHospitalRecentActivity = `-- name: GetHospitalRecentActivity :many
SELECT
  al.timestamp,
  al.tool,
  al.actor_type,
  al.outcome,
  al.session_id
FROM mcp_audit_log al
WHERE al.hospital_id = $1::text
ORDER BY al.timestamp DESC
LIMIT $2
`

type GetHospitalRecentActivityParams struct {
	HospitalID  string `json:"hospital_id"`
	ResultLimit int32  `json:"result_limit"`
}

type GetHospitalRecentActivityRow struct {
	Timestamp pgtype.Timestamptz `json:"timestamp"`
	Tool      string             `json:"tool"`
	ActorType string             `json:"actor_type"`
	Outcome   string             `json:"outcome"`
	SessionID string             `json:"session_id"`
}

func (q *Queries) GetHospitalRecentActivity(ctx context.Context, arg GetHospitalRecentActivityParams) ([]GetHospitalRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, getHospitalRecentActivity, arg.HospitalID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHospitalRecentActivityRow{}
	for rows.Next() {
		var i GetHospitalRecentActivityRow
		if err := rows.Scan(
			&i.Timestamp,
			&i.Tool,
			&i.ActorType,
			&i.Outcome,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHospitalSummary = `-- name: GetHospitalSummary :one
WITH consented_patients AS (
  SELECT c.patient_id
  FROM patient_hospital_consents c
  WHERE c.hospital_id = $1::uuid
    AND c.revoked_at IS NULL
),
hospital_calls AS (
  SELECT
    ca.patient_id,
    ca.started_at,
    ca.started_at::date AS call_date,
    ca.status,
    CASE
      WHEN ca.ended_at IS NOT NULL AND ca.started_at IS NOT NULL AND ca.ended_at >= ca.started_at
        THEN EXTRACT(EPOCH FROM (ca.ended_at - ca.started_at))::double precision
      ELSE NULL::double precision
    END AS duration_seconds,
    EXISTS (
      SELECT 1
      FROM mcp_audit_log al
      WHERE al.session_id = ca.livekit_room_id
        AND al.tool = 'trigger_emergency'
        AND al.outcome = 'success'
    ) AS had_emergency
  FROM calls ca
  INNER JOIN consented_patients cp ON cp.patient_id = ca.patient_id
  WHERE ca.started_at IS NOT NULL
)
SELECT
  $1::text AS hospital_id,
  (SELECT COUNT(*)::int FROM consented_patients) AS total_consented_patients,
  (
    SELECT COUNT(*)::int
    FROM hospital_calls hc
    WHERE hc.started_at >= now() - INTERVAL '30 days'
  ) AS total_calls_30d,
  (
    SELECT COUNT(*)::int
    FROM hospital_calls hc
    WHERE hc.started_at >= now() - INTERVAL '30 days'
      AND hc.had_emergency
  ) AS emergency_events_30d,
  (
    SELECT COALESCE(AVG(hc.duration_seconds), 0)::double precision
    FROM hospital_calls hc
    WHERE hc.started_at >= now() - INTERVAL '30 days'
  ) AS avg_call_duration_seconds,
  (
    SELECT COUNT(rc.id)::int
    FROM record_chunks rc
    INNER JOIN consented_patients cp ON cp.patient_id = rc.patient_id
  ) AS records_indexed,
  (
    SELECT COUNT(DISTINCT ca.patient_id)::int
    FROM calls ca
    INNER JOIN consented_patients cp ON cp.patient_id = ca.patient_id
    WHERE ca.started_at >= now() - INTERVAL '7 days'
  ) AS active_patients_7d
`

type GetHospitalSummaryRow struct {
	HospitalID             string  `json:"hospital_id"`
	TotalConsentedPatients int32   `json:"total_consented_patients"`
	TotalCalls30d          int32   `json:"total_calls_30d"`
	EmergencyEvents30d     int32   `json:"emergency_events_30d"`
	AvgCallDurationSeconds float64 `json:"avg_call_duration_seconds"`
	RecordsIndexed         int32   `json:"records_indexed"`
	ActivePatients7d       int32   `json:"active_patients_7d"`
}

func (q *Queries) GetHospitalSummary(ctx context.Context, hospitalID string) (GetHospitalSummaryRow, error) {
	row := q.db.QueryRow(ctx, getHospitalSummary, hospitalID)
	var i GetHospitalSummaryRow
	err := row.Scan(
		&i.HospitalID,
		&i.TotalConsentedPatients,
		&i.TotalCalls30d,
		&i.EmergencyEvents30d,
		&i.AvgCallDurationSeconds,
		&i.RecordsIndexed,
		&i.ActivePatients7d,
	)
	return i, err
}

const getHospitalToolUsage = `-- name: GetHospitalToolUsage :many
SELECT
  al.tool,
  COUNT(*) FILTER (WHERE al.outcome = 'success')::int AS success_count,
  COUNT(*) FILTER (WHERE al.outcome = 'error')::int AS error_count,
  COUNT(*) FILTER (WHERE al.outcome IN ('forbidden', 'consent-denied'))::int AS denied_count,
  CASE
    WHEN COUNT(*) > 0
      THEN (
        COUNT(*) FILTER (WHERE al.outcome = 'success')::double precision
        / COUNT(*)::double precision
      ) * 100
    ELSE 0::double precision
  END AS success_rate
FROM mcp_audit_log al
WHERE al.hospital_id = $1::text
  AND al.timestamp >= $2
GROUP BY al.tool
ORDER BY success_count DESC, al.tool ASC
`

type GetHospitalToolUsageParams struct {
	HospitalID string             `json:"hospital_id"`
	FromTime   pgtype.Timestamptz `json:"from_time"`
}

type GetHospitalToolUsageRow struct {
	Tool         string  `json:"tool"`
	SuccessCount int32   `json:"success_count"`
	ErrorCount   int32   `json:"error_count"`
	DeniedCount  int32   `json:"denied_count"`
	SuccessRate  float64 `json:"success_rate"`
}

func (q *Queries) GetHospitalToolUsage(ctx context.Context, arg GetHospitalToolUsageParams) ([]GetHospitalToolUsageRow, error) {
	rows, err := q.db.Query(ctx, getHospitalToolUsage, arg.HospitalID, arg.FromTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHospitalToolUsageRow{}
	for rows.Next() {
		var i GetHospitalToolUsageRow
		if err := rows.Scan(
			&i.Tool,
			&i.SuccessCount,
			&i.ErrorCount,
			&i.DeniedCount,
			&i.SuccessRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHospitalTopConditions = `-- name: GetHospitalTopConditions :many
WITH total_patients AS (
  SELECT COUNT(*)::int AS total
  FROM patient_hospital_consents c
  WHERE c.hospital_id = $1::uuid
    AND c.revoked_at IS NULL
)
SELECT
  f.resource_json->'code'->>'text' AS condition_name,
  COUNT(DISTINCT c.patient_id)::int AS patient_count,
  CASE
    WHEN tp.total > 0 THEN (COUNT(DISTINCT c.patient_id)::double precision / tp.total::double precision) * 100
    ELSE 0::double precision
  END AS percentage
FROM patient_hospital_consents c
INNER JOIN fhir_resources f ON f.patient_id = c.patient_id
CROSS JOIN total_patients tp
WHERE c.hospital_id = $1::uuid
  AND c.revoked_at IS NULL
  AND f.resource_type = 'Condition'
  AND f.resource_json->'clinicalStatus'->'coding'->0->>'code' = 'active'
GROUP BY f.resource_json->'code'->>'text', tp.total
ORDER BY patient_count DESC, condition_name ASC
LIMIT $2
`

type GetHospitalTopConditionsParams struct {
	HospitalID  pgtype.UUID `json:"hospital_id"`
	ResultLimit int32       `json:"result_limit"`
}

type GetHospitalTopConditionsRow struct {
	ConditionName interface{} `json:"condition_name"`
	PatientCount  int32       `json:"patient_count"`
	Percentage    float64     `json:"percentage"`
}

func (q *Queries) GetHospitalTopConditions(ctx context.Context, arg GetHospitalTopConditionsParams) ([]GetHospitalTopConditionsRow, error) {
	rows, err := q.db.Query(ctx, getHospitalTopConditions, arg.HospitalID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHospitalTopConditionsRow{}
	for rows.Next() {
		var i GetHospitalTopConditionsRow
		if err := rows.Scan(&i.ConditionName, &i.PatientCount, &i.Percentage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
