// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountPatientCalls(ctx context.Context, patientID pgtype.UUID) (int32, error)
	GetHospitalCallVolume(ctx context.Context, arg GetHospitalCallVolumeParams) ([]GetHospitalCallVolumeRow, error)
	GetHospitalRecentActivity(ctx context.Context, arg GetHospitalRecentActivityParams) ([]GetHospitalRecentActivityRow, error)
	GetHospitalSummary(ctx context.Context, hospitalID string) (GetHospitalSummaryRow, error)
	GetHospitalToolUsage(ctx context.Context, arg GetHospitalToolUsageParams) ([]GetHospitalToolUsageRow, error)
	GetHospitalTopConditions(ctx context.Context, arg GetHospitalTopConditionsParams) ([]GetHospitalTopConditionsRow, error)
	GetPatientCallHistoryRows(ctx context.Context, arg GetPatientCallHistoryRowsParams) ([]GetPatientCallHistoryRowsRow, error)
	GetPlatformHospitalBreakdown(ctx context.Context, arg GetPlatformHospitalBreakdownParams) ([]GetPlatformHospitalBreakdownRow, error)
	GetPlatformSummary(ctx context.Context) (GetPlatformSummaryRow, error)
}

var _ Querier = (*Queries)(nil)
