// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: patient.portal.proto

package patientportal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PatientPortalService_GetProfile_FullMethodName                = "/patientportal.PatientPortalService/GetProfile"
	PatientPortalService_ListCallSummaries_FullMethodName         = "/patientportal.PatientPortalService/ListCallSummaries"
	PatientPortalService_CreateWelfareCheck_FullMethodName        = "/patientportal.PatientPortalService/CreateWelfareCheck"
	PatientPortalService_ListWelfareChecks_FullMethodName         = "/patientportal.PatientPortalService/ListWelfareChecks"
	PatientPortalService_CancelWelfareCheck_FullMethodName        = "/patientportal.PatientPortalService/CancelWelfareCheck"
	PatientPortalService_UpdateWelfareRunLifecycle_FullMethodName = "/patientportal.PatientPortalService/UpdateWelfareRunLifecycle"
)

// PatientPortalServiceClient is the client API for PatientPortalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PatientPortalServiceClient interface {
	GetProfile(ctx context.Context, in *GetPatientProfileRequest, opts ...grpc.CallOption) (*GetPatientProfileResponse, error)
	ListCallSummaries(ctx context.Context, in *ListPatientCallSummariesRequest, opts ...grpc.CallOption) (*ListPatientCallSummariesResponse, error)
	CreateWelfareCheck(ctx context.Context, in *CreateWelfareCheckRequest, opts ...grpc.CallOption) (*CreateWelfareCheckResponse, error)
	ListWelfareChecks(ctx context.Context, in *ListWelfareChecksRequest, opts ...grpc.CallOption) (*ListWelfareChecksResponse, error)
	CancelWelfareCheck(ctx context.Context, in *CancelWelfareCheckRequest, opts ...grpc.CallOption) (*CancelWelfareCheckResponse, error)
	// Internal lifecycle updates from voice-agent/MCP after outbound welfare calls.
	UpdateWelfareRunLifecycle(ctx context.Context, in *UpdateWelfareRunLifecycleRequest, opts ...grpc.CallOption) (*UpdateWelfareRunLifecycleResponse, error)
}

type patientPortalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPatientPortalServiceClient(cc grpc.ClientConnInterface) PatientPortalServiceClient {
	return &patientPortalServiceClient{cc}
}

func (c *patientPortalServiceClient) GetProfile(ctx context.Context, in *GetPatientProfileRequest, opts ...grpc.CallOption) (*GetPatientProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPatientProfileResponse)
	err := c.cc.Invoke(ctx, PatientPortalService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientPortalServiceClient) ListCallSummaries(ctx context.Context, in *ListPatientCallSummariesRequest, opts ...grpc.CallOption) (*ListPatientCallSummariesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPatientCallSummariesResponse)
	err := c.cc.Invoke(ctx, PatientPortalService_ListCallSummaries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientPortalServiceClient) CreateWelfareCheck(ctx context.Context, in *CreateWelfareCheckRequest, opts ...grpc.CallOption) (*CreateWelfareCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWelfareCheckResponse)
	err := c.cc.Invoke(ctx, PatientPortalService_CreateWelfareCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientPortalServiceClient) ListWelfareChecks(ctx context.Context, in *ListWelfareChecksRequest, opts ...grpc.CallOption) (*ListWelfareChecksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWelfareChecksResponse)
	err := c.cc.Invoke(ctx, PatientPortalService_ListWelfareChecks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientPortalServiceClient) CancelWelfareCheck(ctx context.Context, in *CancelWelfareCheckRequest, opts ...grpc.CallOption) (*CancelWelfareCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelWelfareCheckResponse)
	err := c.cc.Invoke(ctx, PatientPortalService_CancelWelfareCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientPortalServiceClient) UpdateWelfareRunLifecycle(ctx context.Context, in *UpdateWelfareRunLifecycleRequest, opts ...grpc.CallOption) (*UpdateWelfareRunLifecycleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWelfareRunLifecycleResponse)
	err := c.cc.Invoke(ctx, PatientPortalService_UpdateWelfareRunLifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PatientPortalServiceServer is the server API for PatientPortalService service.
// All implementations must embed UnimplementedPatientPortalServiceServer
// for forward compatibility.
type PatientPortalServiceServer interface {
	GetProfile(context.Context, *GetPatientProfileRequest) (*GetPatientProfileResponse, error)
	ListCallSummaries(context.Context, *ListPatientCallSummariesRequest) (*ListPatientCallSummariesResponse, error)
	CreateWelfareCheck(context.Context, *CreateWelfareCheckRequest) (*CreateWelfareCheckResponse, error)
	ListWelfareChecks(context.Context, *ListWelfareChecksRequest) (*ListWelfareChecksResponse, error)
	CancelWelfareCheck(context.Context, *CancelWelfareCheckRequest) (*CancelWelfareCheckResponse, error)
	// Internal lifecycle updates from voice-agent/MCP after outbound welfare calls.
	UpdateWelfareRunLifecycle(context.Context, *UpdateWelfareRunLifecycleRequest) (*UpdateWelfareRunLifecycleResponse, error)
	mustEmbedUnimplementedPatientPortalServiceServer()
}

// UnimplementedPatientPortalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPatientPortalServiceServer struct{}

func (UnimplementedPatientPortalServiceServer) GetProfile(context.Context, *GetPatientProfileRequest) (*GetPatientProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedPatientPortalServiceServer) ListCallSummaries(context.Context, *ListPatientCallSummariesRequest) (*ListPatientCallSummariesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCallSummaries not implemented")
}
func (UnimplementedPatientPortalServiceServer) CreateWelfareCheck(context.Context, *CreateWelfareCheckRequest) (*CreateWelfareCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWelfareCheck not implemented")
}
func (UnimplementedPatientPortalServiceServer) ListWelfareChecks(context.Context, *ListWelfareChecksRequest) (*ListWelfareChecksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWelfareChecks not implemented")
}
func (UnimplementedPatientPortalServiceServer) CancelWelfareCheck(context.Context, *CancelWelfareCheckRequest) (*CancelWelfareCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelWelfareCheck not implemented")
}
func (UnimplementedPatientPortalServiceServer) UpdateWelfareRunLifecycle(context.Context, *UpdateWelfareRunLifecycleRequest) (*UpdateWelfareRunLifecycleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWelfareRunLifecycle not implemented")
}
func (UnimplementedPatientPortalServiceServer) mustEmbedUnimplementedPatientPortalServiceServer() {}
func (UnimplementedPatientPortalServiceServer) testEmbeddedByValue()                              {}

// UnsafePatientPortalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PatientPortalServiceServer will
// result in compilation errors.
type UnsafePatientPortalServiceServer interface {
	mustEmbedUnimplementedPatientPortalServiceServer()
}

func RegisterPatientPortalServiceServer(s grpc.ServiceRegistrar, srv PatientPortalServiceServer) {
	// If the following call pancis, it indicates UnimplementedPatientPortalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PatientPortalService_ServiceDesc, srv)
}

func _PatientPortalService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPatientProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientPortalServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatientPortalService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientPortalServiceServer).GetProfile(ctx, req.(*GetPatientProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatientPortalService_ListCallSummaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPatientCallSummariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientPortalServiceServer).ListCallSummaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatientPortalService_ListCallSummaries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientPortalServiceServer).ListCallSummaries(ctx, req.(*ListPatientCallSummariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatientPortalService_CreateWelfareCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWelfareCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientPortalServiceServer).CreateWelfareCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatientPortalService_CreateWelfareCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientPortalServiceServer).CreateWelfareCheck(ctx, req.(*CreateWelfareCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatientPortalService_ListWelfareChecks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWelfareChecksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientPortalServiceServer).ListWelfareChecks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatientPortalService_ListWelfareChecks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientPortalServiceServer).ListWelfareChecks(ctx, req.(*ListWelfareChecksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatientPortalService_CancelWelfareCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelWelfareCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientPortalServiceServer).CancelWelfareCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatientPortalService_CancelWelfareCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientPortalServiceServer).CancelWelfareCheck(ctx, req.(*CancelWelfareCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatientPortalService_UpdateWelfareRunLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWelfareRunLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientPortalServiceServer).UpdateWelfareRunLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatientPortalService_UpdateWelfareRunLifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientPortalServiceServer).UpdateWelfareRunLifecycle(ctx, req.(*UpdateWelfareRunLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PatientPortalService_ServiceDesc is the grpc.ServiceDesc for PatientPortalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PatientPortalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "patientportal.PatientPortalService",
	HandlerType: (*PatientPortalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfile",
			Handler:    _PatientPortalService_GetProfile_Handler,
		},
		{
			MethodName: "ListCallSummaries",
			Handler:    _PatientPortalService_ListCallSummaries_Handler,
		},
		{
			MethodName: "CreateWelfareCheck",
			Handler:    _PatientPortalService_CreateWelfareCheck_Handler,
		},
		{
			MethodName: "ListWelfareChecks",
			Handler:    _PatientPortalService_ListWelfareChecks_Handler,
		},
		{
			MethodName: "CancelWelfareCheck",
			Handler:    _PatientPortalService_CancelWelfareCheck_Handler,
		},
		{
			MethodName: "UpdateWelfareRunLifecycle",
			Handler:    _PatientPortalService_UpdateWelfareRunLifecycle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "patient.portal.proto",
}
