// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: patient.portal.proto

package patientportal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPatientProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientProfileRequest) Reset() {
	*x = GetPatientProfileRequest{}
	mi := &file_patient_portal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientProfileRequest) ProtoMessage() {}

func (x *GetPatientProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_portal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientProfileRequest.ProtoReflect.Descriptor instead.
func (*GetPatientProfileRequest) Descriptor() ([]byte, []int) {
	return file_patient_portal_proto_rawDescGZIP(), []int{0}
}

func (x *GetPatientProfileRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type PatientProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,5,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	MedicalNotes  string                 `protobuf:"bytes,6,opt,name=medical_notes,json=medicalNotes,proto3" json:"medical_notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatientProfile) Reset() {
	*x = PatientProfile{}
	mi := &file_patient_portal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientProfile) ProtoMessage() {}

func (x *PatientProfile) ProtoReflect() protoreflect.Message {
	mi := &file_patient_portal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientProfile.ProtoReflect.Descriptor instead.
func (*PatientProfile) Descriptor() ([]byte, []int) {
	return file_patient_portal_proto_rawDescGZIP(), []int{1}
}

func (x *PatientProfile) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *PatientProfile) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *PatientProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PatientProfile) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *PatientProfile) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *PatientProfile) GetMedicalNotes() string {
	if x != nil {
		return x.MedicalNotes
	}
	return ""
}

type GetPatientProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *PatientProfile        `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientProfileResponse) Reset() {
	*x = GetPatientProfileResponse{}
	mi := &file_patient_portal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientProfileResponse) ProtoMessage() {}

func (x *GetPatientProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_portal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientProfileResponse.ProtoReflect.Descriptor instead.
func (*GetPatientProfileResponse) Descriptor() ([]byte, []int) {
	return file_patient_portal_proto_rawDescGZIP(), []int{2}
}

func (x *GetPatientProfileResponse) GetProfile() *PatientProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type ListPatientCallSummariesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPatientCallSummariesRequest) Reset() {
	*x = ListPatientCallSummariesRequest{}
	mi := &file_patient_portal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPatientCallSummariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPatientCallSummariesRequest) ProtoMessage() {}

func (x *ListPatientCallSummariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patient_portal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPatientCallSummariesRequest.ProtoReflect.Descriptor instead.
func (*ListPatientCallSummariesRequest) Descriptor() ([]byte, []int) {
	return file_patient_portal_proto_rawDescGZIP(), []int{3}
}

func (x *ListPatientCallSummariesRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ListPatientCallSummariesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPatientCallSummariesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type PatientCallSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	RecordingUrl  string                 `protobuf:"bytes,5,opt,name=recording_url,json=recordingUrl,proto3" json:"recording_url,omitempty"`
	Summary       string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	LivekitRoomId string                 `protobuf:"bytes,7,opt,name=livekit_room_id,json=livekitRoomId,proto3" json:"livekit_room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatientCallSummary) Reset() {
	*x = PatientCallSummary{}
	mi := &file_patient_portal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientCallSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientCallSummary) ProtoMessage() {}

func (x *PatientCallSummary) ProtoReflect() protoreflect.Message {
	mi := &file_patient_portal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientCallSummary.ProtoReflect.Descriptor instead.
func (*PatientCallSummary) Descriptor() ([]byte, []int) {
	return file_patient_portal_proto_rawDescGZIP(), []int{4}
}

func (x *PatientCallSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PatientCallSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PatientCallSummary) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *PatientCallSummary) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *PatientCallSummary) GetRecordingUrl() string {
	if x != nil {
		return x.RecordingUrl
	}
	return ""
}

func (x *PatientCallSummary) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PatientCallSummary) GetLivekitRoomId() string {
	if x != nil {
		return x.LivekitRoomId
	}
	return ""
}

type ListPatientCallSummariesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Calls         []*PatientCallSummary  `protobuf:"bytes,1,rep,name=calls,proto3" json:"calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPatientCallSummariesResponse) Reset() {
	*x = ListPatientCallSummariesResponse{}
	mi := &file_patient_portal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPatientCallSummariesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPatientCallSummariesResponse) ProtoMessage() {}

func (x *ListPatientCallSummariesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patient_portal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPatientCallSummariesResponse.ProtoReflect.Descriptor instead.
func (*ListPatientCallSummariesResponse) Descriptor() ([]byte, []int) {
	return file_patient_portal_proto_rawDescGZIP(), []int{5}
}

func (x *ListPatientCallSummariesResponse) GetCalls() []*PatientCallSummary {
	if x != nil {
		return x.Calls
	}
	return nil
}

var File_patient_portal_proto protoreflect.FileDescriptor

const file_patient_portal_proto_rawDesc = "" +
	"\n" +
	"\x14patient.portal.proto\x12\rpatientportal\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n" +
	"\x18GetPatientProfileRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\"\xce\x01\n" +
	"\x0ePatientProfile\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12!\n" +
	"\fphone_number\x18\x02 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12\"\n" +
	"\rdate_of_birth\x18\x05 \x01(\tR\vdateOfBirth\x12#\n" +
	"\rmedical_notes\x18\x06 \x01(\tR\fmedicalNotes\"T\n" +
	"\x19GetPatientProfileResponse\x127\n" +
	"\aprofile\x18\x01 \x01(\v2\x1d.patientportal.PatientProfileR\aprofile\"n\n" +
	"\x1fListPatientCallSummariesRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x95\x02\n" +
	"\x12PatientCallSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12#\n" +
	"\rrecording_url\x18\x05 \x01(\tR\frecordingUrl\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x12&\n" +
	"\x0flivekit_room_id\x18\a \x01(\tR\rlivekitRoomId\"[\n" +
	" ListPatientCallSummariesResponse\x127\n" +
	"\x05calls\x18\x01 \x03(\v2!.patientportal.PatientCallSummaryR\x05calls2\xed\x01\n" +
	"\x14PatientPortalService\x12_\n" +
	"\n" +
	"GetProfile\x12'.patientportal.GetPatientProfileRequest\x1a(.patientportal.GetPatientProfileResponse\x12t\n" +
	"\x11ListCallSummaries\x12..patientportal.ListPatientCallSummariesRequest\x1a/.patientportal.ListPatientCallSummariesResponseB*Z(shared/proto/patientportal;patientportalb\x06proto3"

var (
	file_patient_portal_proto_rawDescOnce sync.Once
	file_patient_portal_proto_rawDescData []byte
)

func file_patient_portal_proto_rawDescGZIP() []byte {
	file_patient_portal_proto_rawDescOnce.Do(func() {
		file_patient_portal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_patient_portal_proto_rawDesc), len(file_patient_portal_proto_rawDesc)))
	})
	return file_patient_portal_proto_rawDescData
}

var file_patient_portal_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_patient_portal_proto_goTypes = []any{
	(*GetPatientProfileRequest)(nil),         // 0: patientportal.GetPatientProfileRequest
	(*PatientProfile)(nil),                   // 1: patientportal.PatientProfile
	(*GetPatientProfileResponse)(nil),        // 2: patientportal.GetPatientProfileResponse
	(*ListPatientCallSummariesRequest)(nil),  // 3: patientportal.ListPatientCallSummariesRequest
	(*PatientCallSummary)(nil),               // 4: patientportal.PatientCallSummary
	(*ListPatientCallSummariesResponse)(nil), // 5: patientportal.ListPatientCallSummariesResponse
	(*timestamppb.Timestamp)(nil),            // 6: google.protobuf.Timestamp
}
var file_patient_portal_proto_depIdxs = []int32{
	1, // 0: patientportal.GetPatientProfileResponse.profile:type_name -> patientportal.PatientProfile
	6, // 1: patientportal.PatientCallSummary.started_at:type_name -> google.protobuf.Timestamp
	6, // 2: patientportal.PatientCallSummary.ended_at:type_name -> google.protobuf.Timestamp
	4, // 3: patientportal.ListPatientCallSummariesResponse.calls:type_name -> patientportal.PatientCallSummary
	0, // 4: patientportal.PatientPortalService.GetProfile:input_type -> patientportal.GetPatientProfileRequest
	3, // 5: patientportal.PatientPortalService.ListCallSummaries:input_type -> patientportal.ListPatientCallSummariesRequest
	2, // 6: patientportal.PatientPortalService.GetProfile:output_type -> patientportal.GetPatientProfileResponse
	5, // 7: patientportal.PatientPortalService.ListCallSummaries:output_type -> patientportal.ListPatientCallSummariesResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_patient_portal_proto_init() }
func file_patient_portal_proto_init() {
	if File_patient_portal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patient_portal_proto_rawDesc), len(file_patient_portal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_patient_portal_proto_goTypes,
		DependencyIndexes: file_patient_portal_proto_depIdxs,
		MessageInfos:      file_patient_portal_proto_msgTypes,
	}.Build()
	File_patient_portal_proto = out.File
	file_patient_portal_proto_goTypes = nil
	file_patient_portal_proto_depIdxs = nil
}
