// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: patient.registration_verification.proto

package registration_verification

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegistrationVerificationService_StartRegistration_FullMethodName = "/patient.registration_verification.RegistrationVerificationService/StartRegistration"
	RegistrationVerificationService_VerifyPhoneOTP_FullMethodName    = "/patient.registration_verification.RegistrationVerificationService/VerifyPhoneOTP"
	RegistrationVerificationService_VerifyEmail_FullMethodName       = "/patient.registration_verification.RegistrationVerificationService/VerifyEmail"
)

// RegistrationVerificationServiceClient is the client API for RegistrationVerificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Registration with email verification: start flow (store in Redis, send verification email)
// then verify (token -> create user + patient).
type RegistrationVerificationServiceClient interface {
	// StartRegistration stores pending registration and sends verification email.
	// Client should direct the user to check email and use the link (token) in VerifyEmail.
	StartRegistration(ctx context.Context, in *StartRegistrationRequest, opts ...grpc.CallOption) (*StartRegistrationResponse, error)
	// VerifyPhoneOTP verifies the OTP sent to the user's phone number.
	VerifyPhoneOTP(ctx context.Context, in *VerifyPhoneOTPRequest, opts ...grpc.CallOption) (*VerifyPhoneOTPResponse, error)
	// VerifyEmail consumes the token from the verification link, creates user and patient, returns ids.
	VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*VerifyEmailResponse, error)
}

type registrationVerificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistrationVerificationServiceClient(cc grpc.ClientConnInterface) RegistrationVerificationServiceClient {
	return &registrationVerificationServiceClient{cc}
}

func (c *registrationVerificationServiceClient) StartRegistration(ctx context.Context, in *StartRegistrationRequest, opts ...grpc.CallOption) (*StartRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRegistrationResponse)
	err := c.cc.Invoke(ctx, RegistrationVerificationService_StartRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationVerificationServiceClient) VerifyPhoneOTP(ctx context.Context, in *VerifyPhoneOTPRequest, opts ...grpc.CallOption) (*VerifyPhoneOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPhoneOTPResponse)
	err := c.cc.Invoke(ctx, RegistrationVerificationService_VerifyPhoneOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationVerificationServiceClient) VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*VerifyEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyEmailResponse)
	err := c.cc.Invoke(ctx, RegistrationVerificationService_VerifyEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistrationVerificationServiceServer is the server API for RegistrationVerificationService service.
// All implementations must embed UnimplementedRegistrationVerificationServiceServer
// for forward compatibility.
//
// Registration with email verification: start flow (store in Redis, send verification email)
// then verify (token -> create user + patient).
type RegistrationVerificationServiceServer interface {
	// StartRegistration stores pending registration and sends verification email.
	// Client should direct the user to check email and use the link (token) in VerifyEmail.
	StartRegistration(context.Context, *StartRegistrationRequest) (*StartRegistrationResponse, error)
	// VerifyPhoneOTP verifies the OTP sent to the user's phone number.
	VerifyPhoneOTP(context.Context, *VerifyPhoneOTPRequest) (*VerifyPhoneOTPResponse, error)
	// VerifyEmail consumes the token from the verification link, creates user and patient, returns ids.
	VerifyEmail(context.Context, *VerifyEmailRequest) (*VerifyEmailResponse, error)
	mustEmbedUnimplementedRegistrationVerificationServiceServer()
}

// UnimplementedRegistrationVerificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistrationVerificationServiceServer struct{}

func (UnimplementedRegistrationVerificationServiceServer) StartRegistration(context.Context, *StartRegistrationRequest) (*StartRegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRegistration not implemented")
}
func (UnimplementedRegistrationVerificationServiceServer) VerifyPhoneOTP(context.Context, *VerifyPhoneOTPRequest) (*VerifyPhoneOTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyPhoneOTP not implemented")
}
func (UnimplementedRegistrationVerificationServiceServer) VerifyEmail(context.Context, *VerifyEmailRequest) (*VerifyEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyEmail not implemented")
}
func (UnimplementedRegistrationVerificationServiceServer) mustEmbedUnimplementedRegistrationVerificationServiceServer() {
}
func (UnimplementedRegistrationVerificationServiceServer) testEmbeddedByValue() {}

// UnsafeRegistrationVerificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistrationVerificationServiceServer will
// result in compilation errors.
type UnsafeRegistrationVerificationServiceServer interface {
	mustEmbedUnimplementedRegistrationVerificationServiceServer()
}

func RegisterRegistrationVerificationServiceServer(s grpc.ServiceRegistrar, srv RegistrationVerificationServiceServer) {
	// If the following call panics, it indicates UnimplementedRegistrationVerificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegistrationVerificationService_ServiceDesc, srv)
}

func _RegistrationVerificationService_StartRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationVerificationServiceServer).StartRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationVerificationService_StartRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationVerificationServiceServer).StartRegistration(ctx, req.(*StartRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistrationVerificationService_VerifyPhoneOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPhoneOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationVerificationServiceServer).VerifyPhoneOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationVerificationService_VerifyPhoneOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationVerificationServiceServer).VerifyPhoneOTP(ctx, req.(*VerifyPhoneOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistrationVerificationService_VerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationVerificationServiceServer).VerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationVerificationService_VerifyEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationVerificationServiceServer).VerifyEmail(ctx, req.(*VerifyEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistrationVerificationService_ServiceDesc is the grpc.ServiceDesc for RegistrationVerificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistrationVerificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "patient.registration_verification.RegistrationVerificationService",
	HandlerType: (*RegistrationVerificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRegistration",
			Handler:    _RegistrationVerificationService_StartRegistration_Handler,
		},
		{
			MethodName: "VerifyPhoneOTP",
			Handler:    _RegistrationVerificationService_VerifyPhoneOTP_Handler,
		},
		{
			MethodName: "VerifyEmail",
			Handler:    _RegistrationVerificationService_VerifyEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "patient.registration_verification.proto",
}
