// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: audit.portal.proto

package auditportal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditPortalService_ListPatientConsents_FullMethodName            = "/auditportal.AuditPortalService/ListPatientConsents"
	AuditPortalService_ListPatientAuditEvents_FullMethodName         = "/auditportal.AuditPortalService/ListPatientAuditEvents"
	AuditPortalService_ListHospitalIncidents_FullMethodName          = "/auditportal.AuditPortalService/ListHospitalIncidents"
	AuditPortalService_ListHospitalPatientAuditEvents_FullMethodName = "/auditportal.AuditPortalService/ListHospitalPatientAuditEvents"
)

// AuditPortalServiceClient is the client API for AuditPortalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuditPortalServiceClient interface {
	ListPatientConsents(ctx context.Context, in *ListPatientConsentsRequest, opts ...grpc.CallOption) (*ListPatientConsentsResponse, error)
	ListPatientAuditEvents(ctx context.Context, in *ListPatientAuditEventsRequest, opts ...grpc.CallOption) (*ListPatientAuditEventsResponse, error)
	ListHospitalIncidents(ctx context.Context, in *ListHospitalIncidentsRequest, opts ...grpc.CallOption) (*ListHospitalIncidentsResponse, error)
	ListHospitalPatientAuditEvents(ctx context.Context, in *ListHospitalPatientAuditEventsRequest, opts ...grpc.CallOption) (*ListHospitalPatientAuditEventsResponse, error)
}

type auditPortalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditPortalServiceClient(cc grpc.ClientConnInterface) AuditPortalServiceClient {
	return &auditPortalServiceClient{cc}
}

func (c *auditPortalServiceClient) ListPatientConsents(ctx context.Context, in *ListPatientConsentsRequest, opts ...grpc.CallOption) (*ListPatientConsentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPatientConsentsResponse)
	err := c.cc.Invoke(ctx, AuditPortalService_ListPatientConsents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditPortalServiceClient) ListPatientAuditEvents(ctx context.Context, in *ListPatientAuditEventsRequest, opts ...grpc.CallOption) (*ListPatientAuditEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPatientAuditEventsResponse)
	err := c.cc.Invoke(ctx, AuditPortalService_ListPatientAuditEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditPortalServiceClient) ListHospitalIncidents(ctx context.Context, in *ListHospitalIncidentsRequest, opts ...grpc.CallOption) (*ListHospitalIncidentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHospitalIncidentsResponse)
	err := c.cc.Invoke(ctx, AuditPortalService_ListHospitalIncidents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditPortalServiceClient) ListHospitalPatientAuditEvents(ctx context.Context, in *ListHospitalPatientAuditEventsRequest, opts ...grpc.CallOption) (*ListHospitalPatientAuditEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHospitalPatientAuditEventsResponse)
	err := c.cc.Invoke(ctx, AuditPortalService_ListHospitalPatientAuditEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditPortalServiceServer is the server API for AuditPortalService service.
// All implementations must embed UnimplementedAuditPortalServiceServer
// for forward compatibility.
type AuditPortalServiceServer interface {
	ListPatientConsents(context.Context, *ListPatientConsentsRequest) (*ListPatientConsentsResponse, error)
	ListPatientAuditEvents(context.Context, *ListPatientAuditEventsRequest) (*ListPatientAuditEventsResponse, error)
	ListHospitalIncidents(context.Context, *ListHospitalIncidentsRequest) (*ListHospitalIncidentsResponse, error)
	ListHospitalPatientAuditEvents(context.Context, *ListHospitalPatientAuditEventsRequest) (*ListHospitalPatientAuditEventsResponse, error)
	mustEmbedUnimplementedAuditPortalServiceServer()
}

// UnimplementedAuditPortalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditPortalServiceServer struct{}

func (UnimplementedAuditPortalServiceServer) ListPatientConsents(context.Context, *ListPatientConsentsRequest) (*ListPatientConsentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPatientConsents not implemented")
}
func (UnimplementedAuditPortalServiceServer) ListPatientAuditEvents(context.Context, *ListPatientAuditEventsRequest) (*ListPatientAuditEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPatientAuditEvents not implemented")
}
func (UnimplementedAuditPortalServiceServer) ListHospitalIncidents(context.Context, *ListHospitalIncidentsRequest) (*ListHospitalIncidentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHospitalIncidents not implemented")
}
func (UnimplementedAuditPortalServiceServer) ListHospitalPatientAuditEvents(context.Context, *ListHospitalPatientAuditEventsRequest) (*ListHospitalPatientAuditEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHospitalPatientAuditEvents not implemented")
}
func (UnimplementedAuditPortalServiceServer) mustEmbedUnimplementedAuditPortalServiceServer() {}
func (UnimplementedAuditPortalServiceServer) testEmbeddedByValue()                            {}

// UnsafeAuditPortalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditPortalServiceServer will
// result in compilation errors.
type UnsafeAuditPortalServiceServer interface {
	mustEmbedUnimplementedAuditPortalServiceServer()
}

func RegisterAuditPortalServiceServer(s grpc.ServiceRegistrar, srv AuditPortalServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuditPortalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditPortalService_ServiceDesc, srv)
}

func _AuditPortalService_ListPatientConsents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPatientConsentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditPortalServiceServer).ListPatientConsents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditPortalService_ListPatientConsents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditPortalServiceServer).ListPatientConsents(ctx, req.(*ListPatientConsentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditPortalService_ListPatientAuditEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPatientAuditEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditPortalServiceServer).ListPatientAuditEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditPortalService_ListPatientAuditEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditPortalServiceServer).ListPatientAuditEvents(ctx, req.(*ListPatientAuditEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditPortalService_ListHospitalIncidents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHospitalIncidentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditPortalServiceServer).ListHospitalIncidents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditPortalService_ListHospitalIncidents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditPortalServiceServer).ListHospitalIncidents(ctx, req.(*ListHospitalIncidentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditPortalService_ListHospitalPatientAuditEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHospitalPatientAuditEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditPortalServiceServer).ListHospitalPatientAuditEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditPortalService_ListHospitalPatientAuditEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditPortalServiceServer).ListHospitalPatientAuditEvents(ctx, req.(*ListHospitalPatientAuditEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditPortalService_ServiceDesc is the grpc.ServiceDesc for AuditPortalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditPortalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auditportal.AuditPortalService",
	HandlerType: (*AuditPortalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPatientConsents",
			Handler:    _AuditPortalService_ListPatientConsents_Handler,
		},
		{
			MethodName: "ListPatientAuditEvents",
			Handler:    _AuditPortalService_ListPatientAuditEvents_Handler,
		},
		{
			MethodName: "ListHospitalIncidents",
			Handler:    _AuditPortalService_ListHospitalIncidents_Handler,
		},
		{
			MethodName: "ListHospitalPatientAuditEvents",
			Handler:    _AuditPortalService_ListHospitalPatientAuditEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "audit.portal.proto",
}
